# ruff: noqa: E741
# generated by datamodel-codegen:
#   filename:  cfht.openapi3.json
#   timestamp: 2026-07-01T23:20:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import Base64Str, BaseModel, Field


class AllocationDataAgency(BaseModel):
    letter: str | None = None
    name: str | None = None


class CalibrationCalibrationMode(Enum):
    no_calibration_mode = 'no_calibration_mode'
    laser = 'laser'
    phase = 'phase'


class CalibrationCalibrationPosition(Enum):
    no_calibration_position = 'no_calibration_position'
    zenith = 'zenith'
    target = 'target'


class ConfigDithering(BaseModel):
    isStaring: bool | None = None


class EspadonsStatusGuiderSeeingProcessingResult(BaseModel):
    guiderSeeing: float | None = None


class ExposureDataAttribution(BaseModel):
    runid: str | None = None
    observing_block_label: Annotated[
        str | None,
        Field(
            title='If displaying the observing block to the user, this uniquely identifies it in the context\nof an observing group, i.e. OG3-2'
        ),
    ] = None
    observing_block_label_int: Annotated[
        int | None, Field(title='Label of the observing block')
    ] = None
    observingBlockToken: Annotated[
        str | None,
        Field(
            description='Token of the observing block this exposure is attributed to.'
        ),
    ] = None
    observingGroupLabel: Annotated[
        int | None,
        Field(
            description='Label of the observing group this exposure is attributed to.'
        ),
    ] = None
    observingGroupToken: Annotated[
        str | None,
        Field(
            description='Token of the observing group this exposure is attributed to.'
        ),
    ] = None
    observingComponentToken: Annotated[
        str | None,
        Field(
            description='Token of the observing component this exposure is attributed to.'
        ),
    ] = None
    exposureNumber: Annotated[
        int | None, Field(description='exposure number this exposure is attributed to.')
    ] = None
    instrument_run: Annotated[
        str | None, Field(title='the queue run this exposure was taken under')
    ] = None
    attributingAgency: Annotated[str | None, Field(title='the agency id')] = None
    tacRank: int | None = None
    tacGrade: str | None = None


class ExposureDataEspadonsStatusExposureMeterProcessingResult(BaseModel):
    snr: float | None = None


class ExposureDataSpirouStatusExposureMeterProcessingResult(BaseModel):
    flux: float | None = None
    snr: float | None = None
    midExposureDateMillis: float | None = None
    spemsnr: Annotated[float | None, Field(title='Calculated SNR')] = None
    spemsnrc: float | None = None


class ExposureDataWenaStatus(BaseModel):
    pass


class ExposureDataWircamStatus(BaseModel):
    iqUncertainty: float | None = None
    absorption: float | None = None
    absorptionUncertainty: float | None = None
    numberOfStarsIq: int | None = None
    numberOfStarsAbsorption: int | None = None
    absoluteSkyLevel: float | None = None
    elongation: float | None = None
    mdcoords: int | None = None
    mdrepeat: int | None = None
    actualFilter: str | None = None
    iq: float | None = None


class ExposureStatusFile(BaseModel):
    absolutePath: Annotated[
        str | None,
        Field(
            description='Absolute path to directory file is homed in. Starts with / and ends with /.'
        ),
    ] = None
    baseName: Annotated[str | None, Field(title='Name of file without extension')] = (
        None
    )
    ext: Annotated[str | None, Field(description='Name of extenion including .')] = None


class FindingChartDataApproval(BaseModel):
    approvedAtMillis: str | None = None
    approvedByUsertoken: str | None = None


class FixedTargetProperMotion(BaseModel):
    raMas: Annotated[
        float | None,
        Field(
            description='Motion in the right ascension axis in milliarcseconds/year.'
        ),
    ] = None
    decMas: Annotated[
        float | None,
        Field(description='Motion in the declination axis in milliarcseconds/year.'),
    ] = None


class InstrumentConfigurationDataEspadonsConfigurationDataOObservingMode(Enum):
    Polarimetry = 'Polarimetry'
    Spectroscopy_star_only = 'Spectroscopy_star_only'
    Spectroscopy_star_sky = 'Spectroscopy_star_sky'


class InstrumentConfigurationDataMegacamConfigurationDataBinning(Enum):
    one_one = 'one_one'
    two_two = 'two_two'
    three_three = 'three_three'
    four_four = 'four_four'


class InstrumentConfigurationDataMegacamConfigurationDataFilter(Enum):
    Unknown = 'Unknown'
    u = 'u'
    g = 'g'
    i = 'i'
    r = 'r'
    z = 'z'
    gri = 'gri'
    CaHK = 'CaHK'
    Ha = 'Ha'
    HaOFF = 'HaOFF'
    OIII = 'OIII'
    OIIIOFF = 'OIIIOFF'
    uS = 'uS'
    gS = 'gS'
    rS = 'rS'
    iS = 'iS'
    zS = 'zS'
    N393S = 'N393S'
    HaS = 'HaS'
    HaOFFS = 'HaOFFS'
    TiOS = 'TiOS'
    CNS = 'CNS'
    OIIIS = 'OIIIS'
    PHGS = 'PHGS'
    M4112 = 'M4112'
    M4376 = 'M4376'


class InstrumentConfigurationDataSitelleConfigurationDataBinning(Enum):
    one_one = 'one_one'
    two_two = 'two_two'
    three_three = 'three_three'


class InstrumentConfigurationDataSitelleConfigurationDataFilter(Enum):
    UNKNOWN = 'UNKNOWN'
    NONE = 'NONE'
    C1 = 'C1'
    C2 = 'C2'
    C3 = 'C3'
    C4 = 'C4'
    SN1 = 'SN1'
    SN2 = 'SN2'
    SN3 = 'SN3'
    SN4 = 'SN4'
    SN5 = 'SN5'
    SN6 = 'SN6'


class InstrumentConfigurationDataSpirouConfigurationDataOObservingMode(Enum):
    Polarimetry = 'Polarimetry'
    Star = 'Star'


class InstrumentConfigurationDataTracking(Enum):
    Unknown = 'Unknown'
    SID = 'SID'
    NONSID = 'NONSID'
    SID_NOG = 'SID_NOG'
    NONSID_G = 'NONSID_G'


class InstrumentConfigurationDataWenaConfigurationData(BaseModel):
    pass


class InstrumentConfigurationDataWircamConfigurationDataFilter(Enum):
    UNKNOWN = 'UNKNOWN'
    W = 'W'
    H = 'H'
    J = 'J'
    Ks = 'Ks'
    Y = 'Y'
    H2 = 'H2'
    KCont = 'KCont'
    CH4On = 'CH4On'
    CH4Off = 'CH4Off'
    LowOH1 = 'LowOH1'
    LowOH2 = 'LowOH2'
    BrG = 'BrG'
    CO = 'CO'
    COnar = 'COnar'


class MMode(Enum):
    Dark = 'Dark'
    Fabry_Perot = 'Fabry_Perot'
    Wave_Hc1 = 'Wave_Hc1'
    Wave_Hc2 = 'Wave_Hc2'
    FLAT = 'FLAT'


class MegacamConfigurationDataSnrMode(Enum):
    NONE = 'NONE'
    STANDARD = 'STANDARD'
    CUMULATIVE = 'CUMULATIVE'
    ZERO_POINT = 'ZERO_POINT'


class MegacamStatusElixirProcessingResult(BaseModel):
    iq: float | None = None
    skyBackground: float | None = None
    snr: float | None = None
    zeropoint: float | None = None


class ObservingBlockConditionRequisite(BaseModel):
    requisiteObservingBlockIndex: Annotated[
        int | None,
        Field(
            description='This should match the index of the observing block in the\nread_observing_block list.'
        ),
    ] = None
    waitPeriodMinMillis: Annotated[
        str | None,
        Field(
            description='Minimum time to wait after requisite observing block exposure has\nbeen taken.'
        ),
    ] = None
    waitPeriodMillis: Annotated[
        str | None,
        Field(
            description='Optimal to wait after requisite observing block exposure has\nbeen taken.'
        ),
    ] = None
    waitPeriodMaxMillis: Annotated[
        str | None,
        Field(
            description='Minimum time to wait after requisite observing block exposure has\nbeen taken.'
        ),
    ] = None
    unbounded: Annotated[
        bool | None,
        Field(
            description='If this observation can happen any time after the requisite.'
        ),
    ] = None


class ObservingBlockConditionWindow(BaseModel):
    observeAfter: Annotated[
        str | None,
        Field(
            description='Start of the observation window, in Unix time milliseconds.'
        ),
    ] = None
    observeBefore: Annotated[
        str | None,
        Field(description='End of the observation window, in Unix time milliseconds.'),
    ] = None


class ObservingBlockObservingComponent(BaseModel):
    targetToken: Annotated[
        str | None,
        Field(
            description='Unique identifier of the target used in this observing component.\n\nWhen creating or updating an observing group, this must be an\nexisting target, or on the map of the request to be created.'
        ),
    ] = None
    observingTemplateToken: Annotated[
        str | None,
        Field(
            description='Unique identifier of the observing template used in this\nobserving component.\n\nWhen creating or updating an observing group, this must be an\nexisting observing template, or on the map of the request to be\ncreated.'
        ),
    ] = None
    targetLabel: Annotated[
        int | None,
        Field(
            description='Label of the target used in this observing component.\nThis value is only set on the read_observing_block.\n\napi_visibility: read only'
        ),
    ] = None
    observingTemplateLabel: Annotated[
        int | None,
        Field(
            description='Label of the observing template used in this observing component.\nThis value is only set on the read_observing_block.\n\napi_visibility: read only'
        ),
    ] = None
    snrBlockToken: Annotated[
        str | None,
        Field(
            description='Unique identifier of the SNR block used in this observing\ncomponent, if any. Must be set if and only if the observing\ncomponent uses a MegaCam cumulative SNR mode observing template.\n\nIf this is set when creating or updating an observing group,\nthe observing component will be tied to the SNR block with this\ntoken if it already exists, otherwise a new SNR block will be\ncreated using this token.'
        ),
    ] = None


class ObservingGroupDataDitherScheme(Enum):
    NONE = 'NONE'
    STANDARD = 'STANDARD'
    GROUP = 'GROUP'


class ObservingGroupDataObservingBlock(BaseModel):
    observingComponent: Annotated[
        list[ObservingBlockObservingComponent] | None,
        Field(
            description='List of observing components that comprise this observing block.'
        ),
    ] = None
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier for the observing block.\n\napi_visibility: operations read only'
        ),
    ] = None
    label: Annotated[
        int | None,
        Field(
            description='Index of the observing block within the program, set by the system\nautomatically. Used for reference in communications with QSO staff.\n\nstorage: transient\napi_visibility: read only'
        ),
    ] = None


class ObservingGroupDataObservingGroupState(Enum):
    NOT_STARTED = 'NOT_STARTED'
    OBSERVED = 'OBSERVED'
    STARTED = 'STARTED'
    VALIDATED = 'VALIDATED'


class PhotometryAperture(BaseModel):
    optimalAperture: bool | None = None
    fixedAperture: Annotated[
        float | None, Field(title='Radius of the aperture in arcsec')
    ] = None
    ninetySixPercentFluxAperture: bool | None = None


class ProgramDataComments(BaseModel):
    question: str | None = None
    comment: str | None = None


class ProgramDataContactInfo(BaseModel):
    piFirstName: str | None = None
    piLastName: str | None = None
    piEmail: str | None = None
    userToken: str | None = None


class ProgramDataProgramType(Enum):
    REGULAR = 'REGULAR'
    TARGET_OF_OPPORTUNITY = 'TARGET_OF_OPPORTUNITY'
    CALIBRATION = 'CALIBRATION'
    SNAPSHOT = 'SNAPSHOT'


class ProgramInfoPiInfo(BaseModel):
    ldapUsername: str | None = None
    emailAddress: str | None = None
    firstName: str | None = None
    lastName: str | None = None
    legacyUsername: str | None = None
    userToken: str | None = None


class RReadoutMode(Enum):
    Normal = 'Normal'
    Slow = 'Slow'
    Fast = 'Fast'


class SitelleConfigurationDataCalibration(BaseModel):
    calibrationPosition: CalibrationCalibrationPosition | None = (
        CalibrationCalibrationPosition.no_calibration_position
    )
    calibrationMode: CalibrationCalibrationMode | None = (
        CalibrationCalibrationMode.no_calibration_mode
    )


class SitelleConfigurationDataResolutionMode(Enum):
    no_resolution_mode = 'no_resolution_mode'
    hires = 'hires'
    medres = 'medres'


class SitelleStatusCamera(BaseModel):
    iq: float | None = None
    iqRms: float | None = None
    pixelShiftX: float | None = None
    pixelShiftY: float | None = None
    numberOfStars: int | None = None
    me: float | None = None


class SpirouConfigurationDataSkyObservation(Enum):
    None_ = 'None'
    Before = 'Before'
    After = 'After'
    BeforeAndAfter = 'BeforeAndAfter'


class SpirouStatusGuiderProcessingResult(BaseModel):
    etime: float | None = None
    isustate: str | None = None
    sbdensP: float | None = None
    holePositionOffsetX: float | None = None
    holePositionOffsetY: float | None = None
    starToNullPositionOffsetX: float | None = None
    starToNullPositionOffsetY: float | None = None
    magnitudeEstimate: float | None = None
    seeingEstimate: float | None = None
    sgisust: Annotated[str | None, Field(title='per  160676372')] = None
    sggdst: str | None = None
    sgfrmrt: float | None = None
    sgetime: float | None = None
    sgnullx: float | None = None
    sgnully: float | None = None
    sgwinx0: float | None = None
    sgwiny0: float | None = None
    sgwinx1: float | None = None
    sgwiny1: float | None = None
    sgoffx0: float | None = None
    sgoffy0: float | None = None
    sgoffx1: float | None = None
    sgoffy1: float | None = None
    sgholex: float | None = None
    sgholey: float | None = None
    sgcholex: float | None = None
    sgcholey: float | None = None
    sgeholex: float | None = None
    sgeholey: float | None = None
    sgcstarx: float | None = None
    sgcstary: float | None = None
    sgestarx: float | None = None
    sgestary: float | None = None
    sgcnoffx: float | None = None
    sgcnoffy: float | None = None
    sgcsee: float | None = None
    sgesee: float | None = None
    sgcmagn: float | None = None
    sgemagn: float | None = None
    sgssee: float | None = None
    trgType: str | None = None


class SpirouStatusPipelineProcessingResult(BaseModel):
    snr10: float | None = None
    snr34: float | None = None
    snr44: float | None = None
    dprtype: str | None = None
    ccfmask: float | None = None
    ccfmacpp: float | None = None
    ccfrv: float | None = None
    ccfcontr: float | None = None
    ccfrvc: float | None = None
    ccffwhm: float | None = None
    ccfmaskStr: str | None = None


class TargetDataMagnitude(BaseModel):
    U: Annotated[float | None, Field(title='U-band magnitude')] = None
    B: Annotated[float | None, Field(title='B-band magnitude')] = None
    V: Annotated[
        float | None,
        Field(
            description='Required for targets observed with ESPaDonS.',
            title='V-band magnitude',
        ),
    ] = None
    R: Annotated[float | None, Field(title='R-band magnitude')] = None
    I: Annotated[float | None, Field(title='I-band magnitude')] = None
    G: Annotated[float | None, Field(title='G-band magnitude')] = None
    J: Annotated[float | None, Field(title='J-band magnitude')] = None
    H: Annotated[
        float | None,
        Field(
            description='Required for targets observed with SPIRou.',
            title='H-band magnitude',
        ),
    ] = None
    K: Annotated[float | None, Field(title='K-band magnitude')] = None
    uu: Annotated[float | None, Field(title='u-band magnitude')] = None
    gg: Annotated[float | None, Field(title='g-band magnitude')] = None
    rr: Annotated[float | None, Field(title='r-band magnitude')] = None
    ii: Annotated[float | None, Field(title='i-band magnitude')] = None
    zz: Annotated[float | None, Field(title='z-band magnitude')] = None
    AB: Annotated[
        float | None,
        Field(
            description='Required for targets observed with MegaCam.',
            title='AB magnitude',
        ),
    ] = None


class TargetListRequestTargetType(Enum):
    ALL = 'ALL'
    FIXED = 'FIXED'
    MOVING = 'MOVING'


class TargetTimeDataView(Enum):
    REQUESTED = 'REQUESTED'
    ACTUAL = 'ACTUAL'


class TimeAccountingDataTimeAccountingStatus(Enum):
    NOT_STARTED = 'NOT_STARTED'
    STARTED = 'STARTED'
    OBSERVED = 'OBSERVED'
    VALIDATED = 'VALIDATED'


class UpenaProcessingResulth2oMm(BaseModel):
    rawDensity: float | None = None
    atZenith: float | None = None


class HttpErrors(BaseModel):
    messages: list[str] | None = None


class ObservingObservingGroupDeleteResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None


class ObservingObservingTemplateDeleteResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None


class ObservingPointingOffsetDeleteResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None


class ObservingTargetDeleteResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None


class ObservingTelescopePatternDeleteResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None


class ObservingpersistenceTimeConstraint(BaseModel):
    window: Annotated[
        list[ObservingBlockConditionWindow] | None,
        Field(
            description='Time windows during which the observation can be made.\n\nWindows can not overlap, and will always be stored in temporal order.'
        ),
    ] = None


class PersistenceCatalogIdentifier(BaseModel):
    catalog: Annotated[str | None, Field(description='Catalog to reference.')] = None
    identifier: Annotated[
        str | None,
        Field(
            description='Valid identifier in the catalog.\n\nNote: this ID will contain a catalog name, because spacing matters in catalogs, the full ID for an object is like\nM    4. Catalog is M, id is identifier could be 4, but to reference m4, you need the spaces.\n\nNB: These identity values can not be set in fits headers because they do not have to conform to\nthe length restrictions.'
        ),
    ] = None


class PersistenceExposureTime(BaseModel):
    desiredSnr: float | None = None
    exposureTimeMs: str | None = None


class PersistenceFindingChartData(BaseModel):
    comment: str | None = None
    url: str | None = None
    token: str | None = None
    staffApproval: FindingChartDataApproval | None = None
    piApproval: FindingChartDataApproval | None = None
    targetToken: str | None = None


class PersistenceITimeData(BaseModel):
    exposureTimeMillis: Annotated[
        str | None,
        Field(description='Time spent collecting photons (in milliseconds).'),
    ] = None
    overheadTimeMillis: Annotated[
        str | None,
        Field(
            description='All other times required for taking the exposure (in milliseconds).'
        ),
    ] = None


class PersistenceListOfIdentifiers(BaseModel):
    catalogIdentifier: list[PersistenceCatalogIdentifier] | None = None


class PersistenceObservingBlockCondition(BaseModel):
    preRequisite: Annotated[
        list[ObservingBlockConditionRequisite] | None,
        Field(
            description='Pre-requisite conditions before each observing block can be started.\nThe index of items in this list corresponds directly to the index of the\nobserving block on the observing group i.e. this list is one-to-one with\nread_observing_block.'
        ),
    ] = None
    window: Annotated[
        list[ObservingBlockConditionWindow] | None,
        Field(
            description='Time windows during which the observing block can be observed.\n\nWindows can not overlap, and will always be stored in temporal order.'
        ),
    ] = None


class PersistenceObservingGroupPriority(Enum):
    UNKNOWN_OG_PRIORITY = 'UNKNOWN_OG_PRIORITY'
    HIGH = 'HIGH'
    MEDIUM = 'MEDIUM'
    LOW = 'LOW'
    INACTIVE = 'INACTIVE'


class PersistenceRollupValue(BaseModel):
    requested: str | None = None
    started: str | None = None
    observed: str | None = None
    validated: str | None = None


class PersistenceSingleObservingGroup(BaseModel):
    observingBlock: ObservingGroupDataObservingBlock | None = None


class PersistenceState(Enum):
    UNOBSERVED = 'UNOBSERVED'
    OBSERVED = 'OBSERVED'
    PROCESSED = 'PROCESSED'
    GRADED = 'GRADED'
    VALIDATED = 'VALIDATED'
    REJECTED = 'REJECTED'


class PersistenceStokesParameter(Enum):
    Q = 'Q'
    U = 'U'
    V = 'V'
    W = 'W'
    I = 'I'


class PersistenceSubTotalsData(BaseModel):
    etime: PersistenceRollupValue | None = None
    overheadtime: PersistenceRollupValue | None = None
    exposureCount: PersistenceRollupValue | None = None
    childCount: PersistenceRollupValue | None = None
    etimeConfigured: PersistenceRollupValue | None = None
    overheadTimeConfigured: PersistenceRollupValue | None = None
    completeness: Annotated[
        float | None, Field(description='Percentage completed for the entity.')
    ] = None


class PersistenceTargetIdentifiers(BaseModel):
    catalogIdentifier: Annotated[
        dict[str, PersistenceListOfIdentifiers] | None,
        Field(
            description='key: catalog name, catalog_identifier.key === catalog_identifier.get(key).catalog\nvalue: catalog identifier.',
            title='All catalogs resolved by simbad for this target',
        ),
    ] = None
    twoMass: PersistenceCatalogIdentifier | None = None
    gaia1: PersistenceCatalogIdentifier | None = None
    gaia2: PersistenceCatalogIdentifier | None = None
    resolvedCatalogIdentifier: PersistenceCatalogIdentifier | None = None


class PersistenceTargetTimeData(BaseModel):
    requestedIntegrationTime: PersistenceITimeData | None = None
    actualIntegrationTime: PersistenceITimeData | None = None
    view: TargetTimeDataView | None = TargetTimeDataView.REQUESTED
    exposureCount: Annotated[
        int | None,
        Field(
            description='The total number of exposures represented by the values here.\n\nThis value is the same for both views.'
        ),
    ] = None
    childCount: Annotated[
        int | None,
        Field(
            description='The total number of child entities represented by the values here.\n\nIf this is a program, these are observing groups.\nIf this is an observing group, these are observing blocks.\nIf this is an observing block, these are exposures.\n\nUseful for e.g. seeing the number of iterations configuredor completed on an Observing Group.\nThis value is the same for both views.'
        ),
    ] = None


class PersistenceTimeAccountingData(BaseModel):
    configuredTime: PersistenceTargetTimeData | None = None
    chargedTime: PersistenceTargetTimeData | None = None
    validatedTimeOnSky: PersistenceTargetTimeData | None = None
    timeOnSky: PersistenceTargetTimeData | None = None
    timeAccountingStatus: TimeAccountingDataTimeAccountingStatus | None = (
        TimeAccountingDataTimeAccountingStatus.NOT_STARTED
    )
    completionRatio: Annotated[
        float | None,
        Field(
            description='Entity completion ratio, representing how much of the time configured has been charged.\n\nEqual to total charged time (as requested) divided by total configured time. For programs, if the total configured time is greater than the time allocated to the program, we divide by the time allocated instead.\nNote that if a program has INACTIVE observing groups that already have charged time, this could result in an inflated value here.',
            le=1.0,
        ),
    ] = None


class ProtobufAny(BaseModel):
    typeUrl: str | None = None
    value: Annotated[
        Base64Str | None,
        Field(
            pattern='^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'
        ),
    ] = None


class RpcStatus(BaseModel):
    code: int | None = None
    message: str | None = None
    details: list[ProtobufAny] | None = None


class TypesBigInteger(BaseModel):
    value: str | None = None


class TypesDoubleMinMax(BaseModel):
    min: float | None = None
    max: float | None = None


class TypesDurationUnit(Enum):
    DAYS = 'DAYS'
    HOURS = 'HOURS'
    MINUTES = 'MINUTES'
    SECONDS = 'SECONDS'


class TypesExposureType(Enum):
    OBJECT = 'OBJECT'
    TARGET = 'TARGET'
    SKY = 'SKY'
    DARK = 'DARK'
    FLAT = 'FLAT'
    SNAP = 'SNAP'
    BIAS = 'BIAS'
    FOCUS = 'FOCUS'
    ALIGN = 'ALIGN'
    COMPARISON = 'COMPARISON'
    ACQUIRE = 'ACQUIRE'
    FABRY_PEROT = 'FABRY_PEROT'
    TWILIGHT_FLATS = 'TWILIGHT_FLATS'
    PHOTOMETRY = 'PHOTOMETRY'
    SFOCUS = 'SFOCUS'


class TypesInstrumentType(Enum):
    UNKNOWN = 'UNKNOWN'
    CFH12K = 'CFH12K'
    MEGACAM = 'MEGACAM'
    WIRCAM = 'WIRCAM'
    ESPADONS = 'ESPADONS'
    SITELLE = 'SITELLE'
    SPIROU = 'SPIROU'
    WENAOKEAO = 'WENAOKEAO'


class TypesOffsetCoordinate(BaseModel):
    raOffset: Annotated[
        float | None,
        Field(
            description='Offset in the Right Ascension axis in arcsec of degrees.',
            ge=-1296000.0,
            le=1296000.0,
            title='Right Ascension Offset',
        ),
    ] = None
    decOffset: Annotated[
        float | None,
        Field(
            description='Offset in the Declination axis in arcsec of degrees.',
            ge=-324000.0,
            le=324000.0,
            title='Declination Offset',
        ),
    ] = None
    exposureNumber: Annotated[
        float | None,
        Field(description='Exposure number', le=99.0, title='Exposure number'),
    ] = None


class TypesSkyCoordinate(BaseModel):
    ra: Annotated[
        float | None,
        Field(
            description='Right Ascension in degrees.', le=360.0, title='Right Ascension'
        ),
    ] = None
    dec: Annotated[
        float | None,
        Field(
            description='Declination in degrees.',
            ge=-90.0,
            le=90.0,
            title='Declination',
        ),
    ] = None


class ConfigNodding(BaseModel):
    startSequence: TypesExposureType | None = TypesExposureType.OBJECT
    targetDb: float | None = None


class EspadonsStatusUpenaProcessingResult(BaseModel):
    iq: float | None = None
    h2oColumnDensityFromTelluricLines: float | None = None
    radialVelocityCorrections: float | None = None
    snrPerCcdBin: float | None = None
    snrPerSpecBin: float | None = None
    actualWavelength: float | None = None
    snrPerCcdBinPolar: float | None = None
    snrPerSpecBinPolar: float | None = None
    h2oMmData: UpenaProcessingResulth2oMm | None = None


class ExposureDataEspadonsStatus(BaseModel):
    instrMode: str | None = None
    actualWavelength: float | None = None
    snrExpMeter: float | None = None
    snrWaveMeasInt: float | None = None
    snrWaveMeasPol: float | None = None
    snrMeasIntPerCcdBin: float | None = None
    snrMeasIntPerSpecBin: float | None = None
    snrMeasPolarCcdBin: float | None = None
    snrMeasPolarSpecBin: float | None = None
    trgType: str | None = None
    guiderSeeing: float | None = None
    guiderSeeingProcessingResults: (
        EspadonsStatusGuiderSeeingProcessingResult | None
    ) = None
    exposureMeterProcessingResults: (
        ExposureDataEspadonsStatusExposureMeterProcessingResult | None
    ) = None
    upenaProcessingResults: EspadonsStatusUpenaProcessingResult | None = None
    observationType: str | None = None


class ExposureDataMegacamStatus(BaseModel):
    iq: float | None = None
    skybg: float | None = None
    elixirEval: int | None = None
    elixirSeval: str | None = None
    snr: float | None = None
    atmosphericTransmission: float | None = None
    elixirZeropoint: float | None = None
    actualFilter: str | None = None
    elixirProcessingResult: MegacamStatusElixirProcessingResult | None = None


class ExposureDataSitelleStatus(BaseModel):
    cameraA: SitelleStatusCamera | None = None
    cameraB: SitelleStatusCamera | None = None
    relativeExtinction: float | None = None
    relativeExtinctionRms: float | None = None
    actualFilter: str | None = None


class ExposureDataSpirouStatus(BaseModel):
    acqtime: float | None = None
    acqtime1: str | None = None
    asicNum: str | None = None
    scaId: str | None = None
    muxtype: int | None = None
    noutputs: int | None = None
    nadcs: int | None = None
    pddector: int | None = None
    clkoff: int | None = None
    warmtst: int | None = None
    clocking: int | None = None
    glbreset: int | None = None
    frmode: int | None = None
    camlink: int | None = None
    expmode: int | None = None
    nresets: int | None = None
    frmtime: float | None = None
    exptime: float | None = None
    acqtype: int | None = None
    datamode: int | None = None
    datlevel: int | None = None
    asicgain: int | None = None
    nomgain: int | None = None
    ampreset: int | None = None
    ktcremov: int | None = None
    srccur: int | None = None
    ampinput: int | None = None
    v4v3v2v1: str | None = None
    units: str | None = None
    tstation: str | None = None
    hxrgver: str | None = None
    mclk: float | None = None
    inttime: float | None = None
    frameno: int | None = None
    sbAdcS: str | None = None
    sbadc1P: float | None = None
    sbadc2P: float | None = None
    sbcaliP: str | None = None
    sbdensP: float | None = None
    sbrhb1P: str | None = None
    sbrhb2P: str | None = None
    sbetemP: str | None = None
    sbInjT: float | None = None
    sbPolT: float | None = None
    sbCs1T: float | None = None
    sbCs2T: float | None = None
    sbCb1T: float | None = None
    sbCb2T: float | None = None
    sbiavl1s: str | None = None
    sbiavl2s: str | None = None
    sbetelS: str | None = None
    sbCscS: str | None = None
    sbcrefP: str | None = None
    sbccasP: str | None = None
    sbcdenP: float | None = None
    sbagitS: str | None = None
    sbcmirP: str | None = None
    sbclhc1s: str | None = None
    sbclhc1w: str | None = None
    sbclhc1c: float | None = None
    sbclhc2s: str | None = None
    sbclhc2w: str | None = None
    sbclhc2c: float | None = None
    sbclwlS: str | None = None
    sbclwlC: float | None = None
    sbwlshS: str | None = None
    sbctecS: str | None = None
    sbctecct: float | None = None
    sbctecht: float | None = None
    sbccprit: float | None = None
    sbcccuT: float | None = None
    sbccprot: float | None = None
    sbcfbiT: float | None = None
    sbcwlsT: float | None = None
    sbclsuat: float | None = None
    sbcfpiT: float | None = None
    sbcfpeT: float | None = None
    sbcfpbP: float | None = None
    sbvgaCp: float | None = None
    sbvgaIp: float | None = None
    sbvgbCp: float | None = None
    sbvgbIp: float | None = None
    sbmk00T: float | None = None
    sbmk01T: float | None = None
    sbmk02T: float | None = None
    sbmk03T: float | None = None
    sbmk04T: float | None = None
    sbmk05T: float | None = None
    sbmk06T: float | None = None
    sbmk07T: float | None = None
    sbls000t: float | None = None
    sbls001t: float | None = None
    sbls002t: float | None = None
    sbls003t: float | None = None
    sbls004t: float | None = None
    sbls005t: float | None = None
    sbls006t: float | None = None
    sbls007t: float | None = None
    sbls008t: float | None = None
    sbls009t: float | None = None
    sbls010t: float | None = None
    sbls011t: float | None = None
    sbls100t: float | None = None
    sbls101t: float | None = None
    sbls102t: float | None = None
    sbls103t: float | None = None
    sbls104t: float | None = None
    sbls105t: float | None = None
    sbls106t: float | None = None
    sbls107t: float | None = None
    sbls108t: float | None = None
    sbls109t: float | None = None
    sbls110t: float | None = None
    sbls111t: float | None = None
    sbl00iT: float | None = None
    sbl00hV: float | None = None
    sbl01iT: float | None = None
    sbl01hV: float | None = None
    sbl02iT: float | None = None
    sbl02hV: float | None = None
    sbl03iT: float | None = None
    sbl03hV: float | None = None
    sbl04iT: float | None = None
    sbl04hV: float | None = None
    sbl05iT: float | None = None
    sbl05hV: float | None = None
    sbl06iT: float | None = None
    sbl06hV: float | None = None
    sbl07iT: float | None = None
    sbl07hV: float | None = None
    sbl08iT: float | None = None
    sbl08hV: float | None = None
    sbl09iT: float | None = None
    sbl09hV: float | None = None
    sbl10iT: float | None = None
    sbl10hV: float | None = None
    sbl11iT: float | None = None
    sbl11hV: float | None = None
    sbl12iT: float | None = None
    sbl12hV: float | None = None
    sbl13iT: float | None = None
    sbl13hV: float | None = None
    seadc1P: float | None = None
    seadc2P: float | None = None
    sedens_p: int | None = None
    sedens_p_float: float | None = None
    seInjT: float | None = None
    sePolT: float | None = None
    seCs1T: float | None = None
    seCs2T: float | None = None
    seCb1T: float | None = None
    seCb2T: float | None = None
    sectecct: float | None = None
    sectecht: float | None = None
    seccprit: float | None = None
    secccuT: float | None = None
    seccprot: float | None = None
    secfbiT: float | None = None
    secwlsT: float | None = None
    seclhc1c: float | None = None
    seclhc2c: float | None = None
    seclwlC: float | None = None
    seclsuat: float | None = None
    secfpiT: float | None = None
    secfpeT: float | None = None
    secfpbP: float | None = None
    sevgaCp: float | None = None
    sevgaIp: float | None = None
    sevgbCp: float | None = None
    sevgbIp: float | None = None
    semk00T: float | None = None
    semk01T: float | None = None
    semk02T: float | None = None
    semk03T: float | None = None
    semk04T: float | None = None
    semk05T: float | None = None
    semk06T: float | None = None
    semk07T: float | None = None
    sels000t: float | None = None
    sels001t: float | None = None
    sels002t: float | None = None
    sels003t: float | None = None
    sels004t: float | None = None
    sels005t: float | None = None
    sels006t: float | None = None
    sels007t: float | None = None
    sels008t: float | None = None
    sels009t: float | None = None
    sels010t: float | None = None
    sels011t: float | None = None
    sels100t: float | None = None
    sels101t: float | None = None
    sels102t: float | None = None
    sels103t: float | None = None
    sels104t: float | None = None
    sels105t: float | None = None
    sels106t: float | None = None
    sels107t: float | None = None
    sels108t: float | None = None
    sels109t: float | None = None
    sels110t: float | None = None
    sels111t: float | None = None
    sel00iT: float | None = None
    sel00hV: float | None = None
    sel01iT: float | None = None
    sel01hV: float | None = None
    sel02iT: float | None = None
    sel02hV: float | None = None
    sel03iT: float | None = None
    sel03hV: float | None = None
    sel04iT: float | None = None
    sel04hV: float | None = None
    sel05iT: float | None = None
    sel05hV: float | None = None
    sel06iT: float | None = None
    sel06hV: float | None = None
    sel07iT: float | None = None
    sel07hV: float | None = None
    sel08iT: float | None = None
    sel08hV: float | None = None
    sel09iT: float | None = None
    sel09hV: float | None = None
    sel10iT: float | None = None
    sel10hV: float | None = None
    sel11iT: float | None = None
    sel11hV: float | None = None
    sel12iT: float | None = None
    sel12hV: float | None = None
    sel13iT: float | None = None
    sel13hV: float | None = None
    guiderProcessing: SpirouStatusGuiderProcessingResult | None = None
    exposureMeterProcessing: (
        ExposureDataSpirouStatusExposureMeterProcessingResult | None
    ) = None
    pipelineProcessing: SpirouStatusPipelineProcessingResult | None = None


class InstrumentConfigurationDataEspadonsConfigurationData(BaseModel):
    observingMode: (
        InstrumentConfigurationDataEspadonsConfigurationDataOObservingMode | None
    ) = InstrumentConfigurationDataEspadonsConfigurationDataOObservingMode.Polarimetry
    readoutMode: RReadoutMode | None = RReadoutMode.Normal
    stokesParameter: PersistenceStokesParameter | None = PersistenceStokesParameter.Q
    numberOfSequences: int | None = None
    numberOfExposures: int | None = None
    needs_snr: bool | None = None
    snrWave: float | None = None
    snr: float | None = None


class InstrumentConfigurationDataMegacamConfigurationDataPhotometry(BaseModel):
    aperture: PhotometryAperture | None = None
    psf: bool | None = None


class InstrumentConfigurationDataSitelleConfigurationData(BaseModel):
    filter: InstrumentConfigurationDataSitelleConfigurationDataFilter | None = (
        InstrumentConfigurationDataSitelleConfigurationDataFilter.UNKNOWN
    )
    binning: InstrumentConfigurationDataSitelleConfigurationDataBinning | None = (
        InstrumentConfigurationDataSitelleConfigurationDataBinning.one_one
    )
    resolution: int | None = None
    snrwavelength: Annotated[
        float | None,
        Field(title='This should be on target too , sitell, espedons, spirou'),
    ] = None
    calibration: SitelleConfigurationDataCalibration | None = None
    resolutionMode: SitelleConfigurationDataResolutionMode | None = (
        SitelleConfigurationDataResolutionMode.no_resolution_mode
    )
    needsPrecision: bool | None = None
    needsFluxCalibration: bool | None = None
    needsTargetCalibration: bool | None = None


class InstrumentConfigurationDataSpirouConfigurationData(BaseModel):
    templateName: Annotated[str | None, Field(title='Deprecated fields')] = None
    observingMode: (
        InstrumentConfigurationDataSpirouConfigurationDataOObservingMode | None
    ) = InstrumentConfigurationDataSpirouConfigurationDataOObservingMode.Polarimetry
    stokesParameter: PersistenceStokesParameter | None = PersistenceStokesParameter.Q
    mode: MMode | None = MMode.Dark
    skyObservation: SpirouConfigurationDataSkyObservation | None = (
        SpirouConfigurationDataSkyObservation.None_
    )
    numberOfSequences: Annotated[
        int | None,
        Field(
            title='Each sequence is 1 exposure for Star mode and 4 exposures for ObservingMode'
        ),
    ] = None
    useSnr: Annotated[
        bool | None, Field(title='when true - use SNR for stoping exposures')
    ] = None
    skyEtimeMillis: Annotated[
        str | None, Field(title='Used to override the etime for the sky_observation')
    ] = None


class InstrumentConfigurationDataWircamConfigurationData(BaseModel):
    filter: InstrumentConfigurationDataWircamConfigurationDataFilter | None = (
        InstrumentConfigurationDataWircamConfigurationDataFilter.UNKNOWN
    )
    isMicrodithering: bool | None = None
    exposuresPerDpPosition: Annotated[int | None, Field(title='Must always be > 0')] = (
        None
    )
    accuratePointing: bool | None = None
    defocus: float | None = None
    isStaring: bool | None = None


class MovingTargetEphemeris(BaseModel):
    mjd: Annotated[
        float | None,
        Field(
            description='Modified Julian date when the target is at this coordinate.'
        ),
    ] = None
    coordinate: TypesSkyCoordinate | None = None
    computedCoordinate: TypesSkyCoordinate | None = None


class TargetDataFixedTarget(BaseModel):
    coordinate: TypesSkyCoordinate | None = None
    properMotion: FixedTargetProperMotion | None = None
    computedCoordinate: TypesSkyCoordinate | None = None
    estimatedRadialVelocityKmps: Annotated[
        float | None,
        Field(
            description='Expected radial velocity of the target in kilometers/second.\n\nUsed for targets observed with SPIRou.'
        ),
    ] = None


class TargetDataLinkedTargetIdentifiers(BaseModel):
    piConfirmedIdentifiers: PersistenceTargetIdentifiers | None = None
    customTarget: Annotated[
        bool | None,
        Field(
            description='Used to indicate this is a target without known identifiers.'
        ),
    ] = None


class TargetDataMovingTarget(BaseModel):
    ephemerisPoint: Annotated[
        list[MovingTargetEphemeris] | None,
        Field(
            description="The ephemerides that define the path of motion for the target.\n\nMust be provided using topocentric astrometric coordinates.\nDo not provide apparent coordinates.\nCFHT strongly recommends the use of JPL Horizons System for\ngenerating the proper coordinates. CFHT's observatory code is T14.\n\nAt least five distinct positions must be provided that span the\ndesired observing period. The first position should be well in\nadvance of the observation. The positions do not need to be\nuniformly sampled throughout the desired observing period.\n\nThe points will be interpolated to determine the position of the\ntarget at the time of observation, at which point there must be\nat least one ephemeris point defined in the past, and at least\nfour defined in the future."
        ),
    ] = None


class TelescopePatternDataConfig(BaseModel):
    name: str | None = None
    description: str | None = None
    chargeModel: Annotated[
        str | None, Field(title='Used for calculating cost for this pattern')
    ] = None
    dithering: ConfigDithering | None = None
    nodding: ConfigNodding | None = None
    scale: float | None = None
    sybasePatId: TypesBigInteger | None = None
    isSystem: bool | None = None


class TelescopePatternDataOffset(BaseModel):
    exposureNumber: Annotated[
        int | None,
        Field(
            description='TODO: deprecate, no need to have duplicate information here.'
        ),
    ] = None
    offset: TypesOffsetCoordinate | None = None
    type: TypesExposureType | None = TypesExposureType.OBJECT


class ObservingRollupFields(BaseModel):
    iTime: PersistenceRollupValue | None = None
    iTimeConfigured: PersistenceRollupValue | None = None
    subTotals: PersistenceSubTotalsData | None = None


class PersistenceAllocationData(BaseModel):
    runId: str | None = None
    timeAllocatedMillis: str | None = None
    tacRank: int | None = None
    tacGrade: str | None = None
    instrument: TypesInstrumentType | None = TypesInstrumentType.UNKNOWN
    agency: AllocationDataAgency | None = None
    cfhtRank: int | None = None


class PersistenceConstraint(BaseModel):
    imageQuality: TypesDoubleMinMax | None = None
    skyBackgroundMax: float | None = None
    airmassMax: float | None = None
    extinctionMax: float | None = None
    moonDistanceArcLengthMin: float | None = None
    photometric: bool | None = None
    name: str | None = None
    sybaseConsId: TypesBigInteger | None = None
    h2oVaporMax: float | None = None
    readSkyBackgroundName: str | None = None
    skyBackgroundName: str | None = None


class PersistencePointingOffsetData(BaseModel):
    token: str | None = None
    name: str | None = None
    offset: TypesOffsetCoordinate | None = None
    label: int | None = None
    version: int | None = None
    userToken: Annotated[
        str | None,
        Field(
            title='this is the PI of the program that this entity will be recorded for\nif null should be derived using the program_data.contact_info.user_token\nif null, then a system ?? gross'
        ),
    ] = None
    instrument: TypesInstrumentType | None = TypesInstrumentType.UNKNOWN
    isSystem: bool | None = None


class PersistenceProgramData(BaseModel):
    title: str | None = None
    abstract: str | None = None
    contactInfo: ProgramDataContactInfo | None = None
    comment: list[ProgramDataComments] | None = None
    sybasePiUserId: str | None = None
    subTotals: PersistenceSubTotalsData | None = None
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier for the program. Used interchangeably with "runid".'
        ),
    ] = None
    timeAllocation: list[PersistenceAllocationData] | None = None
    releaseDateMillis: str | None = None
    metadataReleaseDateMillis: str | None = None
    commentField: str | None = None
    programType: ProgramDataProgramType | None = ProgramDataProgramType.REGULAR
    distributionHash: str | None = None
    timeAccounting: PersistenceTimeAccountingData | None = None
    operationsCommentField: str | None = None
    lastDataAcquisitionNotificationDateMillis: str | None = None


class PersistenceTargetData(BaseModel):
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier for the target.\n\nWhen creating a new target, this will be inferred from the request data\nif left blank here.\n\nMust begin with the program token followed by a dash, e.g.\n20AE01-0123456789'
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(
            description='Name for the target entered by PI, or primary name as resolved by CDS.\n\nWill become OBJECT in the FITS header.\n\nRequired.\nLength limited to 39 characters.\nAllowed characters are letters, numbers, spaces, or any of:\n!@#$%^&*()_-+.,?/[]<>'
        ),
    ] = None
    label: Annotated[
        int | None,
        Field(
            description='Index of the target within the program, set by the system automatically.\nUsed for reference to targets in communications with QSO staff.\n\nstorage: transient\napi_visibility: read only'
        ),
    ] = None
    version: Annotated[
        int | None,
        Field(
            description='Increments when this object updates.\n\nstorage: transient\napi_visibility: read only, incremented by the server'
        ),
    ] = None
    fixedTarget: TargetDataFixedTarget | None = None
    movingTarget: TargetDataMovingTarget | None = None
    magnitude: TargetDataMagnitude | None = None
    temperatureEffective: Annotated[
        float | None,
        Field(
            description='The estimated/measured effective temperature, in Kelvin.\n\nRequired for targets observed with SPIRou or ESPaDOnS.\nNot used for MegaCam.'
        ),
    ] = None
    standardStar: Annotated[
        bool | None,
        Field(
            description='Whether the star is a "standard" star, to be observed each time other\nscience targets are observed.\n\nNot used for MegaCam.'
        ),
    ] = None
    linkedTargetIdentifiers: TargetDataLinkedTargetIdentifiers | None = None
    findingChart: Annotated[
        list[PersistenceFindingChartData] | None,
        Field(
            description='A read-only view of the finding charts for this target.\nTo create or update finding charts, see the FindingChartService.\n\nstorage: transient\napi_visibility: read only'
        ),
    ] = None
    pointingOffsetToken: Annotated[
        str | None,
        Field(
            description='The token of a pointing offset which should be used when observing\nthis target.\n\nTo view or manage pointing offsets, see the PointingOffsetService.'
        ),
    ] = None
    pointingOffset: PersistencePointingOffsetData | None = None


class PersistenceTelescopePatternData(BaseModel):
    offsets: Annotated[
        list[TelescopePatternDataOffset] | None,
        Field(
            title='Should only be set if manually specifying custom dithering patterns'
        ),
    ] = None
    config: TelescopePatternDataConfig | None = None
    token: str | None = None
    label: int | None = None
    version: int | None = None
    userToken: str | None = None
    instrument: TypesInstrumentType | None = TypesInstrumentType.UNKNOWN
    isSystem: bool | None = None
    name: str | None = None
    offsetCoordinate: list[TypesOffsetCoordinate] | None = None


class TypesDuration(BaseModel):
    millis: str | None = None
    displayUnit: TypesDurationUnit | None = TypesDurationUnit.DAYS


class ExposureDataExposureStatus(BaseModel):
    megacamStatus: ExposureDataMegacamStatus | None = None
    wircamStatus: ExposureDataWircamStatus | None = None
    espadonsStatus: ExposureDataEspadonsStatus | None = None
    sitelleStatus: ExposureDataSitelleStatus | None = None
    spirouStatus: ExposureDataSpirouStatus | None = None
    wenaStatus: ExposureDataWenaStatus | None = None
    exposureTime: PersistenceExposureTime | None = None
    expDateMjd: float | None = None
    queueName: str | None = None
    expType: str | None = None
    expStatus: PersistenceState | None = PersistenceState.UNOBSERVED
    isPhotometric: bool | None = None
    obsComment: str | None = None
    seqComment: str | None = None
    actualPointing: TypesSkyCoordinate | None = None
    actualSky: float | None = None
    actualAirmass: float | None = None
    actualMoondist: float | None = None
    observerComment: str | None = None
    qcComment: str | None = None
    file: ExposureStatusFile | None = None
    creditedQcoordinator: str | None = None
    creditedObserver: str | None = None
    grade: int | None = None
    readObsDateUtc: str | None = None
    readObsDateHst: str | None = None
    readActualSkyName: str | None = None
    ra: Annotated[str | None, Field(title='Values from headers')] = None
    dec: str | None = None
    cmmtobs: str | None = None
    cmmtseq: str | None = None
    piName: str | None = None
    nexp: str | None = None
    cmpltexp: str | None = None
    ha: str | None = None
    readObsDateMillis: str | None = None
    object: str | None = None


class InstrumentConfigurationDataMegacamConfigurationData(BaseModel):
    filter: InstrumentConfigurationDataMegacamConfigurationDataFilter | None = (
        InstrumentConfigurationDataMegacamConfigurationDataFilter.Unknown
    )
    binning: InstrumentConfigurationDataMegacamConfigurationDataBinning | None = (
        InstrumentConfigurationDataMegacamConfigurationDataBinning.one_one
    )
    isDynamicExposureTime: Annotated[
        bool | None,
        Field(
            title="TODO: is this needed billy? Can we use presence of snr or not to decide?\nI THINK SO.  We have the capability to calculate SNR on every exposure, but we aren't necessarily doing SNR mode observations with everything"
        ),
    ] = None
    minimumExposures: int | None = None
    minExptimeMs: str | None = None
    maxExptimeMs: str | None = None
    magAB: Annotated[
        float | None,
        Field(
            title='TODO: interesting field here because associated with the target, but in the legacy mp snr mode, the mag is carried with the IC! so have to go back to this :('
        ),
    ] = None
    snrMode: MegacamConfigurationDataSnrMode | None = (
        MegacamConfigurationDataSnrMode.NONE
    )
    etcPhotometry: (
        InstrumentConfigurationDataMegacamConfigurationDataPhotometry | None
    ) = None


class PhaseScheduleObservingGroupPhaseSchedule(BaseModel):
    earliestObserveDateMillis: Annotated[
        str | None,
        Field(description='The earliest moment to observe, in Unix time milliseconds.'),
    ] = None
    tolerance: TypesDuration | None = None
    period: TypesDuration | None = None
    periodTolerance: TypesDuration | None = None


class ObservingEphemeridesUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: PersistenceTargetData | None = None


class ObservingPointingOffsetGetResponse(BaseModel):
    success: bool | None = None
    entity: PersistencePointingOffsetData | None = None
    error: HttpErrors | None = None


class ObservingPointingOffsetListResponse(BaseModel):
    success: bool | None = None
    entity: list[PersistencePointingOffsetData] | None = None
    error: HttpErrors | None = None


class ObservingPointingOffsetUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: PersistencePointingOffsetData | None = None


class ObservingProgramInfo(BaseModel):
    programData: PersistenceProgramData | None = None
    rollupFields: ObservingRollupFields | None = None
    timeAccounting: PersistenceTimeAccountingData | None = None
    piInfo: ProgramInfoPiInfo | None = None
    version: int | None = None


class ObservingTargetListResponse(BaseModel):
    success: bool | None = None
    entity: list[PersistenceTargetData] | None = None
    error: HttpErrors | None = None


class ObservingTargetShowResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: PersistenceTargetData | None = None


class ObservingTargetUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: PersistenceTargetData | None = None


class ObservingTelescopePatternListResponse(BaseModel):
    success: bool | None = None
    telescope_pattern: list[PersistenceTelescopePatternData] | None = None
    error: HttpErrors | None = None


class ObservingTelescopePatternUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    telescope_pattern: PersistenceTelescopePatternData | None = None


class ObservingUpdateProgramCommentResponse(BaseModel):
    success: bool | None = None
    programData: PersistenceProgramData | None = None
    error: HttpErrors | None = None


class ObservingUpdateProgramCommentsResponse(BaseModel):
    success: bool | None = None
    programData: PersistenceProgramData | None = None
    error: HttpErrors | None = None


class PersistenceInstrumentConfigurationData(BaseModel):
    espadonsConfiguration: (
        InstrumentConfigurationDataEspadonsConfigurationData | None
    ) = None
    megacamConfiguration: InstrumentConfigurationDataMegacamConfigurationData | None = (
        None
    )
    wircamConfiguration: InstrumentConfigurationDataWircamConfigurationData | None = (
        None
    )
    sitelleConfiguration: InstrumentConfigurationDataSitelleConfigurationData | None = (
        None
    )
    spirouConfiguration: InstrumentConfigurationDataSpirouConfigurationData | None = (
        None
    )
    wenaConfiguration: InstrumentConfigurationDataWenaConfigurationData | None = None
    sybaseIcId: TypesBigInteger | None = None
    etimeOrSnr: PersistenceExposureTime | None = None
    sybaseConsId: TypesBigInteger | None = None
    tracking: InstrumentConfigurationDataTracking | None = (
        InstrumentConfigurationDataTracking.Unknown
    )


class PersistenceLegacyReel(BaseModel):
    reelOgToken: Annotated[
        str | None, Field(description='Token of the linked observing group.')
    ] = None
    delay: TypesDuration | None = None
    window: TypesDuration | None = None
    reelOgLabel: Annotated[
        int | None,
        Field(
            description='Label of the observing group which must be observed before this one.\n\nstorage: transient\napi_visibility: read only'
        ),
    ] = None


class PersistenceObservingTemplateData(BaseModel):
    instrumentConfiguration: PersistenceInstrumentConfigurationData | None = None
    constraint: PersistenceConstraint | None = None
    telescope_offset: PersistenceTelescopePatternData | None = None
    chargeModel: Annotated[
        str | None,
        Field(
            description='Used for calculating cost for this pattern\nInvokes code which reads the ExposureInstructions and\nattributes a cost to it.'
        ),
    ] = None
    itime: str | None = None
    calculateEtime: PersistenceExposureTime | None = None
    acquisitionTime: PersistenceExposureTime | None = None
    token: str | None = None
    associatedObservingBlocks: Annotated[
        list[TypesBigInteger] | None,
        Field(
            description='select ob.* from ob, prg, icseq where ob.prg_id = prg.id\nand prg.runid=<runid>\nand icseq.ob_id=ob.id and ob.con_id = <constraint.sybase_cons_id>\nand icseq.ic_id = <instrument_configuration.sybase_ic_id>;',
            title='When just creating an OT, this list is empty\nWhen this OT belongs to an OG, then any OBs in sybase that this OT is related too must be filled in.\nselect * from blah where (select id from prg where prg\nQuery to find related OBs is, select ob.* from ob, prg where ob.prg_id = prg.id and prg.runid=?     instrument_configuration.sybase_ic_id, constraint.sybase_cons_id',
        ),
    ] = None
    name: str | None = None
    totalExposureCount: int | None = None
    label: int | None = None
    version: Annotated[
        int | None,
        Field(
            description='storage: transient\napi_visibility: read only, incremented by the server',
            title='Increments when this object updates',
        ),
    ] = None
    telescopePatternToken: str | None = None
    telescopePatternScale: float | None = None
    megacamCumulativeSnrSystemGenerated: bool | None = None


class PersistencePhaseScheduleObservingGroup(BaseModel):
    observingBlock: ObservingGroupDataObservingBlock | None = None
    phaseSchedule: PhaseScheduleObservingGroupPhaseSchedule | None = None


class PersistenceTargetMonitoringObservingGroupTimeConstraint(BaseModel):
    numberOfIterations: Annotated[
        int | None, Field(description='How many observations to take.')
    ] = None
    minimumNumberOfIterations: Annotated[
        int | None,
        Field(
            description='Minimum number of observations which still provides science value.\n\nIf weather becomes an issue, this is used to determine if additional\nobservations should be tried, or the whole observing group aborted\nto prioritize other observations.\n\nCannot be greater than requested number of iterations.'
        ),
    ] = None
    timeInterval: TypesDuration | None = None
    timeIntervalToleranceMin: TypesDuration | None = None
    timeIntervalToleranceMax: TypesDuration | None = None
    t0Millis: Annotated[
        str | None,
        Field(
            description="Time the observing group should start being observed, in Unix time\nmilliseconds.\n\nIf omitted, CFHT will start observing at the QC's discretion."
        ),
    ] = None
    withinSameCameraRun: Annotated[
        bool | None,
        Field(
            description='Whether all iterations need to occur within the same camera run.'
        ),
    ] = None


class ObservingListProgramsResponse(BaseModel):
    success: bool | None = None
    entity: list[ObservingProgramInfo] | None = None
    error: HttpErrors | None = None


class ObservingObservingTemplateListResponse(BaseModel):
    success: bool | None = None
    entity: list[PersistenceObservingTemplateData] | None = None
    error: HttpErrors | None = None


class ObservingObservingTemplateUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    observing_template: PersistenceObservingTemplateData | None = None


class PersistenceObservingGroupContext(BaseModel):
    iterationCount: Annotated[
        int | None,
        Field(
            title='The iteration number this object was part of in the observing group'
        ),
    ] = None
    iterationTotal: Annotated[
        int | None,
        Field(title='The total number of iterations requested for the observing group'),
    ] = None
    iterationMinimum: Annotated[
        int | None,
        Field(
            title='Minimum number of iterations this OG needs to provide science value'
        ),
    ] = None
    window: Annotated[
        list[ObservingBlockConditionWindow] | None,
        Field(title='Sorted by from past -> future on the observe_after key'),
    ] = None
    observingGroupToken: str | None = None
    observingGroupPriority: PersistenceObservingGroupPriority | None = (
        PersistenceObservingGroupPriority.UNKNOWN_OG_PRIORITY
    )
    observingGroupState: ObservingGroupDataObservingGroupState | None = (
        ObservingGroupDataObservingGroupState.NOT_STARTED
    )
    observingGroupLabel: int | None = None
    observingGroupVersion: Annotated[
        int | None,
        Field(description='Increments every time the observing group changes.'),
    ] = None
    legacyReel: PersistenceLegacyReel | None = None
    single: bool | None = None
    targetMonitoring: PersistenceTargetMonitoringObservingGroupTimeConstraint | None = (
        None
    )
    phaseSchedule: PhaseScheduleObservingGroupPhaseSchedule | None = None
    timeAccounting: PersistenceTimeAccountingData | None = None
    exposureType: TypesExposureType | None = TypesExposureType.OBJECT
    useGroupDitherScheme: bool | None = None


class PersistenceTargetMonitoringObservingGroup(BaseModel):
    observingBlock: ObservingGroupDataObservingBlock | None = None
    timeConstraint: PersistenceTargetMonitoringObservingGroupTimeConstraint | None = (
        None
    )


class PersistenceExposureData(BaseModel):
    token: str | None = None
    obsid: str | None = None
    exposureNumber: int | None = None
    iteration: int | None = None
    parentExposureToken: str | None = None
    exposureStatus: ExposureDataExposureStatus | None = None
    observingTemplate: PersistenceObservingTemplateData | None = None
    target_data: PersistenceTargetData | None = None
    observingGroupContext: PersistenceObservingGroupContext | None = None
    allDerivationsComplete: Annotated[
        bool | None,
        Field(
            description='When false, there is data which is still being calculated for this exposure.\n\nData can still be displayed, but the client should attempt to refresh the data.'
        ),
    ] = None
    queueRunId: str | None = None
    cameraRunId: str | None = None
    prgRunId: str | None = None
    observingComponentToken: str | None = None
    subTotals: PersistenceSubTotalsData | None = None
    attribution: ExposureDataAttribution | None = None
    version: Annotated[
        int | None,
        Field(
            description='storage: transient\napi_visibility: read only, incremented by the server',
            title='Increments when this object updates',
        ),
    ] = None


class PersistenceObservingGroupData(BaseModel):
    token: Annotated[
        str | None, Field(description='Unique identifier for the observing group.')
    ] = None
    label: Annotated[
        int | None,
        Field(
            description='Index of the observing group within the program, set by the system\nautomatically. Used for reference in communications with QSO staff.\n\nstorage: transient\napi_visibility: read only'
        ),
    ] = None
    ogPriority: PersistenceObservingGroupPriority | None = (
        PersistenceObservingGroupPriority.UNKNOWN_OG_PRIORITY
    )
    singleObservingGroup: PersistenceSingleObservingGroup | None = None
    targetMonitoringObservingGroup: (
        PersistenceTargetMonitoringObservingGroup | None
    ) = None
    phaseScheduleObservingGroup: PersistencePhaseScheduleObservingGroup | None = None
    readObservingBlock: Annotated[
        list[ObservingGroupDataObservingBlock] | None,
        Field(
            description='The observing blocks that have been created based on the entered\nconfiguration.\n\napi_visibility: read only'
        ),
    ] = None
    observingBlockCondition: Annotated[
        dict[str, PersistenceObservingBlockCondition] | None,
        Field(
            description='The requirements that have been set for observing each observing blocks\nbased on the entered configuration.\n\napi_visibility: read only'
        ),
    ] = None
    minimumObservingBlockCount: Annotated[
        int | None,
        Field(
            description='This field is unused, please ignore.\n\napi_visibility: read only'
        ),
    ] = None
    timeAccounting: PersistenceTimeAccountingData | None = None
    state: ObservingGroupDataObservingGroupState | None = (
        ObservingGroupDataObservingGroupState.NOT_STARTED
    )
    version: Annotated[
        int | None,
        Field(
            description='Increments when this object updates.\n\nstorage: transient\napi_visibility: read only, incremented by the server'
        ),
    ] = None
    legacyReel: PersistenceLegacyReel | None = None
    timeConstraint: ObservingpersistenceTimeConstraint | None = None
    targetType: TypesExposureType | None = TypesExposureType.OBJECT
    ditherScheme: ObservingGroupDataDitherScheme | None = (
        ObservingGroupDataDitherScheme.NONE
    )
    lowSurfaceBrightness: Annotated[
        bool | None,
        Field(
            title='Indicates the observing group uses low surface brightness (LSB) mode.with'
        ),
    ] = None


class SnrBlockDataSnrBlockObservingComponents(BaseModel):
    observingComponentToken: Annotated[
        str | None, Field(title='the observing component')
    ] = None
    observingGroupToken: Annotated[
        str | None, Field(title='should not be here, should be in the parent')
    ] = None
    isPrimary: Annotated[bool | None, Field(title='is it the original oc?')] = None
    configuredExposures: int | None = None
    exposures: list[PersistenceExposureData] | None = None
    obLabel: int | None = None
    targetToken: str | None = None
    observingTemplateToken: str | None = None


class ObservingObservingGroupListResponse(BaseModel):
    success: bool | None = None
    entity: list[PersistenceObservingGroupData] | None = None
    error: HttpErrors | None = None


class ObservingObservingGroupUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: PersistenceObservingGroupData | None = None


class PersistenceSnrBlockData(BaseModel):
    token: str | None = None
    label: int | None = None
    cumulativeSnr: Annotated[
        float | None,
        Field(
            title='the total snr achieved of all exposures\n of all observing components of this snr block'
        ),
    ] = None
    carryForwardSnr: Annotated[
        float | None,
        Field(
            title='if the program is copied to a new program possibly for a new semester\n the cumulative snr will be moved to the carry_forward_snr and the\n carry forward snr will be counted in the cumulative snr of the new program'
        ),
    ] = None
    observingComponents: list[SnrBlockDataSnrBlockObservingComponents] | None = None
    version: int | None = None
    requestedTargetMagnitude: Annotated[
        float | None, Field(title='this will come from the target')
    ] = None
    requestedCumulativeSnr: Annotated[
        float | None, Field(title='this will come from the OT')
    ] = None
    requestedMinimumExposures: int | None = None
    totalExposures: Annotated[
        int | None,
        Field(title='counting the total validated exposures for this OC (OT/TARGET)'),
    ] = None
    primaryObservingGroupToken: str | None = None
    primaryObservingComponentToken: str | None = None
    primaryObservingGroupLabel: int | None = None
    totalConfiguredExposures: Annotated[
        int | None, Field(title='counting the total configured exposures for this OC')
    ] = None


class ObservingAddSingleToSnrBlockResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    snrBlock: PersistenceSnrBlockData | None = None
    observingGroup: PersistenceObservingGroupData | None = None


class ObservingSnrBlockListResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: list[PersistenceSnrBlockData] | None = None
