# Auto generated file, do not edit
# ruff: noqa: E741
# generated by datamodel-codegen:
#   filename:  cfhtopenapi.yaml
#   timestamp: 2026-08-12T17:56:39+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from aeonlib.cfht.base_model import CFHTBaseModel
from pydantic import ConfigDict, Field


class AddSingleToSnrBlockRequest(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    runid: Annotated[
        str | None, Field(description='Unique identifier of the science program.')
    ] = None
    snr_block_token: Annotated[
        str | None,
        Field(
            description='Unique identifier of an existing SNR block to create the new observing group for.'
        ),
    ] = None
    observing_group_token: Annotated[
        str | None,
        Field(
            description='Unique identifier of the observing group. If an observing group target with this token already exists, it will be updated, otherwise it will be created. Must begin with the program token followed by a dash, e.g. 20AE01-0123456789'
        ),
    ] = None


class Instrument(Enum):
    unknown = 'UNKNOWN'
    cfh12_k = 'CFH12K'
    megacam = 'MEGACAM'
    wircam = 'WIRCAM'
    espadons = 'ESPADONS'
    sitelle = 'SITELLE'
    spirou = 'SPIROU'
    wenaokeao = 'WENAOKEAO'


class AllocationDataAgency(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    letter: str | None = None
    name: str | None = None


class BigInteger(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    value: str | None = None


class CatalogIdentifier(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    catalog: Annotated[str | None, Field(description='Catalog to reference.')] = None
    identifier: Annotated[
        str | None,
        Field(
            description='Valid identifier in the catalog. Note: this ID will contain a catalog name, because spacing matters in catalogs, the full ID for an object is like M    4. Catalog is M, id is identifier could be 4, but to reference m4, you need the spaces. NB: These identity values can not be set in fits headers because they do not have to conform to the length restrictions.'
        ),
    ] = None


class ConfigDithering(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    is_staring: bool | None = None


class StartSequence(Enum):
    object = 'OBJECT'
    target = 'TARGET'
    sky = 'SKY'
    dark = 'DARK'
    flat = 'FLAT'
    snap = 'SNAP'
    bias = 'BIAS'
    focus = 'FOCUS'
    align = 'ALIGN'
    comparison = 'COMPARISON'
    acquire = 'ACQUIRE'
    fabry_perot = 'FABRY_PEROT'
    twilight_flats = 'TWILIGHT_FLATS'
    photometry = 'PHOTOMETRY'
    sfocus = 'SFOCUS'


class ConfigNodding(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    start_sequence: StartSequence | None = None
    target_db: float | None = None


class DoubleMinMax(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    min: float | None = None
    max: float | None = None


class DoubleValue(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    value: Annotated[float | None, Field(description='The double value.')] = None


class DisplayUnit(Enum):
    days = 'DAYS'
    hours = 'HOURS'
    minutes = 'MINUTES'
    seconds = 'SECONDS'


class Duration(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    millis: int | None = None
    display_unit: Annotated[
        DisplayUnit | None,
        Field(
            description='Only needed for rendering UI, should display the duration using the units specified. If unset, assume DAYS'
        ),
    ] = None


class DynamicExposureTimeLimit(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    minimum_multiplier: float | None = None
    maximum_multiplier: float | None = None


class Errors(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    message: list[str] | None = None


class EspadonsStatusExposureMeterProcessingResult(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    snr: float | None = None


class EspadonsStatusGuiderSeeingProcessingResult(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    guider_seeing: float | None = None


class ExposureDataAttribution(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    runid: str | None = None
    observing_block_display_label: Annotated[
        str | None,
        Field(
            description='If displaying the observing block to the user, this uniquely identifies it in the context of an observing group, i.e. OG3-2'
        ),
    ] = None
    observing_block_label: Annotated[
        int | None, Field(description='Label of the observing block')
    ] = None
    observing_block_token: Annotated[
        str | None,
        Field(
            description='Token of the observing block this exposure is attributed to.'
        ),
    ] = None
    observing_group_label: Annotated[
        int | None,
        Field(
            description='Label of the observing group this exposure is attributed to.'
        ),
    ] = None
    observing_group_token: Annotated[
        str | None,
        Field(
            description='Token of the observing group this exposure is attributed to.'
        ),
    ] = None
    observing_component_token: Annotated[
        str | None,
        Field(
            description='Token of the observing component this exposure is attributed to.'
        ),
    ] = None
    exposure_number: Annotated[
        int | None, Field(description='exposure number this exposure is attributed to.')
    ] = None
    queue_run: Annotated[
        str | None, Field(description='the queue run this exposure was taken under')
    ] = None
    attributing_agency: Annotated[str | None, Field(description='the agency id')] = None
    tac_rank: int | None = None
    tac_grade: str | None = None


class ExpStatus(Enum):
    unobserved = 'UNOBSERVED'
    observed = 'OBSERVED'
    processed = 'PROCESSED'
    graded = 'GRADED'
    validated = 'VALIDATED'
    rejected = 'REJECTED'


class ExposureDataWenaStatus(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )


class ExposureDataWircamStatus(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    iq_uncertainty: float | None = None
    absorption: float | None = None
    absorption_uncertainty: float | None = None
    number_of_stars_iq: int | None = None
    number_of_stars_absorption: int | None = None
    absolute_sky_level: float | None = None
    elongation: float | None = None
    mdcoords: int | None = None
    mdrepeat: int | None = None
    actual_filter: str | None = None
    iq: float | None = None


class ExposureStatusFile(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    absolute_path: Annotated[
        str | None,
        Field(
            description='Absolute path to directory file is homed in. Starts with / and ends with /.'
        ),
    ] = None
    base_name: Annotated[
        str | None, Field(description='Name of file without extension')
    ] = None
    ext: Annotated[str | None, Field(description='Name of extenion including .')] = None


class ExposureTime(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    desired_snr: float | None = None
    exposure_time_ms: int | None = None


class FindingChartDataApproval(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    approved_at_millis: int | None = None
    approved_by_usertoken: str | None = None


class FixedTargetProperMotion(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    ra_mas: Annotated[
        float | None,
        Field(
            description='Motion in the right ascension axis in milliarcseconds/year.'
        ),
    ] = None
    dec_mas: Annotated[
        float | None,
        Field(description='Motion in the declination axis in milliarcseconds/year.'),
    ] = None


class GoogleProtobufAny(CFHTBaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    field_type: Annotated[
        str | None,
        Field(alias='@type', description='The type of the serialized message.'),
    ] = None


class ITimeData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    exposure_time_millis: Annotated[
        int | None,
        Field(description='Time spent collecting photons (in milliseconds).'),
    ] = None
    overhead_time_millis: Annotated[
        int | None,
        Field(
            description='All other times required for taking the exposure (in milliseconds).'
        ),
    ] = None


class Tracking(Enum):
    unknown = 'Unknown'
    sid = 'SID'
    nonsid = 'NONSID'
    sid_nog = 'SID_NOG'
    nonsid_g = 'NONSID_G'


class ObservingMode(Enum):
    polarimetry = 'Polarimetry'
    spectroscopy_star_only = 'Spectroscopy_star_only'
    spectroscopy_star_sky = 'Spectroscopy_star_sky'


class ReadoutMode(Enum):
    normal = 'Normal'
    slow = 'Slow'
    fast = 'Fast'


class StokesParameter(Enum):
    q = 'Q'
    u = 'U'
    v = 'V'
    w = 'W'
    i = 'I'


class InstrumentConfigurationDataEspadonsConfigurationData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    observing_mode: ObservingMode | None = None
    readout_mode: ReadoutMode | None = None
    stokes_parameter: StokesParameter | None = None
    number_of_sequences: int | None = None
    number_of_exposures: int | None = None
    use_snr: bool | None = None
    snr_wave: float | None = None
    snr: float | None = None


class Filter(Enum):
    unknown = 'Unknown'
    u = 'u'
    g = 'g'
    i = 'i'
    r = 'r'
    z = 'z'
    gri = 'gri'
    ca_hk = 'CaHK'
    ha = 'Ha'
    ha_off = 'HaOFF'
    oiii = 'OIII'
    oiiioff = 'OIIIOFF'
    u_s = 'uS'
    g_s = 'gS'
    r_s = 'rS'
    i_s = 'iS'
    z_s = 'zS'
    n393_s = 'N393S'
    ha_s = 'HaS'
    ha_offs = 'HaOFFS'
    ti_os = 'TiOS'
    cns = 'CNS'
    oiiis = 'OIIIS'
    phgs = 'PHGS'
    m4112 = 'M4112'
    m4376 = 'M4376'


class Binning(Enum):
    one_one = 'one_one'
    two_two = 'two_two'
    three_three = 'three_three'
    four_four = 'four_four'


class SnrMode(Enum):
    none = 'NONE'
    standard = 'STANDARD'
    cumulative = 'CUMULATIVE'
    zero_point = 'ZERO_POINT'


class Filter1(Enum):
    unknown = 'UNKNOWN'
    none = 'NONE'
    c1 = 'C1'
    c2 = 'C2'
    c3 = 'C3'
    c4 = 'C4'
    sn1 = 'SN1'
    sn2 = 'SN2'
    sn3 = 'SN3'
    sn4 = 'SN4'
    sn5 = 'SN5'
    sn6 = 'SN6'


class Binning1(Enum):
    one_one = 'one_one'
    two_two = 'two_two'
    three_three = 'three_three'


class ResolutionMode(Enum):
    no_resolution_mode = 'no_resolution_mode'
    hires = 'hires'
    medres = 'medres'


class ObservingMode1(Enum):
    polarimetry = 'Polarimetry'
    star = 'Star'


class Mode(Enum):
    dark = 'Dark'
    fabry_perot = 'Fabry_Perot'
    wave_hc1 = 'Wave_Hc1'
    wave_hc2 = 'Wave_Hc2'
    flat = 'FLAT'


class SkyObservation(Enum):
    none = 'None'
    before = 'Before'
    after = 'After'
    before_and_after = 'BeforeAndAfter'


class InstrumentConfigurationDataWenaConfigurationData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )


class Filter2(Enum):
    unknown = 'UNKNOWN'
    w = 'W'
    h = 'H'
    j = 'J'
    ks = 'Ks'
    y = 'Y'
    h2 = 'H2'
    k_cont = 'KCont'
    ch4_on = 'CH4On'
    ch4_off = 'CH4Off'
    low_oh1 = 'LowOH1'
    low_oh2 = 'LowOH2'
    br_g = 'BrG'
    co = 'CO'
    c_onar = 'COnar'


class InstrumentConfigurationDataWircamConfigurationData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    filter: Filter2 | None = None
    is_microdithering: bool | None = None
    exposures_per_dp_position: Annotated[
        int | None, Field(description='Must always be > 0')
    ] = None
    accurate_pointing: bool | None = None
    defocus: float | None = None
    is_staring: bool | None = None


class Int32Value(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    value: Annotated[int | None, Field(description='The int32 value.')] = None


class Int64Value(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    value: Annotated[int | None, Field(description='The int64 value.')] = None


class LegacyReel(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    reel_og_token: Annotated[
        str | None, Field(description='Token of the linked observing group.')
    ] = None
    delay: Duration | None = None
    window: Duration | None = None
    reel_og_label: Annotated[
        int | None,
        Field(
            description='Label of the observing group which must be observed before this one. storage: transient api_visibility: read only'
        ),
    ] = None


class ListOfIdentifiers(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    catalog_identifier: list[CatalogIdentifier] | None = None


class MegacamStatusElixirProcessingResult(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    iq: float | None = None
    sky_background: float | None = None
    snr: float | None = None
    zeropoint: float | None = None


class ObservingBlockConditionRequisite(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    requisite_observing_block_index: Annotated[
        int | None,
        Field(
            description='This should match the index of the observing block in the read_observing_block list.'
        ),
    ] = None
    wait_period_min_millis: Annotated[
        int | None,
        Field(
            description='Minimum time to wait after requisite observing block exposure has been taken.'
        ),
    ] = None
    wait_period_millis: Annotated[
        int | None,
        Field(
            description='Optimal to wait after requisite observing block exposure has been taken.'
        ),
    ] = None
    wait_period_max_millis: Annotated[
        int | None,
        Field(
            description='Minimum time to wait after requisite observing block exposure has been taken.'
        ),
    ] = None
    unbounded: Annotated[
        bool | None,
        Field(
            description='If this observation can happen any time after the requisite.'
        ),
    ] = None


class ObservingBlockConditionWindow(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    observe_after: Annotated[
        int | None,
        Field(
            description='Start of the observation window, in Unix time milliseconds.'
        ),
    ] = None
    observe_before: Annotated[
        int | None,
        Field(description='End of the observation window, in Unix time milliseconds.'),
    ] = None


class ObservingBlockObservingComponent(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    target_token: Annotated[
        str | None,
        Field(
            description='Unique identifier of the target used in this observing component. When creating or updating an observing group, this must be an existing target, or on the map of the request to be created.'
        ),
    ] = None
    observing_template_token: Annotated[
        str | None,
        Field(
            description='Unique identifier of the observing template used in this observing component. When creating or updating an observing group, this must be an existing observing template, or on the map of the request to be created.'
        ),
    ] = None
    target_label: Annotated[
        int | None,
        Field(
            description='Label of the target used in this observing component. This value is only set on the read_observing_block. api_visibility: read only'
        ),
    ] = None
    observing_template_label: Annotated[
        int | None,
        Field(
            description='Label of the observing template used in this observing component. This value is only set on the read_observing_block. api_visibility: read only'
        ),
    ] = None
    snr_block_token: Annotated[
        str | None,
        Field(
            description='Unique identifier of the SNR block used in this observing component, if any. Must be set if and only if the observing component uses a MegaCam cumulative SNR mode observing template. If this is set when creating or updating an observing group, the observing component will be tied to the SNR block with this token if it already exists, otherwise a new SNR block will be created using this token.'
        ),
    ] = None


class ObservingGroupPriority(Enum):
    unknown_og_priority = 'UNKNOWN_OG_PRIORITY'
    high = 'HIGH'
    medium = 'MEDIUM'
    low = 'LOW'
    inactive = 'INACTIVE'


class ObservingGroupState(Enum):
    not_started = 'NOT_STARTED'
    observed = 'OBSERVED'
    started = 'STARTED'
    validated = 'VALIDATED'


class ExposureType(Enum):
    object = 'OBJECT'
    target = 'TARGET'
    sky = 'SKY'
    dark = 'DARK'
    flat = 'FLAT'
    snap = 'SNAP'
    bias = 'BIAS'
    focus = 'FOCUS'
    align = 'ALIGN'
    comparison = 'COMPARISON'
    acquire = 'ACQUIRE'
    fabry_perot = 'FABRY_PEROT'
    twilight_flats = 'TWILIGHT_FLATS'
    photometry = 'PHOTOMETRY'
    sfocus = 'SFOCUS'


class OgPriority(Enum):
    unknown_og_priority = 'UNKNOWN_OG_PRIORITY'
    high = 'HIGH'
    medium = 'MEDIUM'
    low = 'LOW'
    inactive = 'INACTIVE'


class State(Enum):
    not_started = 'NOT_STARTED'
    observed = 'OBSERVED'
    started = 'STARTED'
    validated = 'VALIDATED'


class TargetType(Enum):
    object = 'OBJECT'
    target = 'TARGET'
    sky = 'SKY'
    dark = 'DARK'
    flat = 'FLAT'
    snap = 'SNAP'
    bias = 'BIAS'
    focus = 'FOCUS'
    align = 'ALIGN'
    comparison = 'COMPARISON'
    acquire = 'ACQUIRE'
    fabry_perot = 'FABRY_PEROT'
    twilight_flats = 'TWILIGHT_FLATS'
    photometry = 'PHOTOMETRY'
    sfocus = 'SFOCUS'


class DitherScheme(Enum):
    none = 'NONE'
    standard = 'STANDARD'
    group = 'GROUP'


class ObservingGroupDataObservingBlock(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    observing_component: Annotated[
        list[ObservingBlockObservingComponent] | None,
        Field(
            description='List of observing components that comprise this observing block.'
        ),
    ] = None
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier for the observing block. api_visibility: operations read only'
        ),
    ] = None
    label: Annotated[
        int | None,
        Field(
            description='Index of the observing block within the program, set by the system automatically. Used for reference in communications with QSO staff. storage: transient api_visibility: read only'
        ),
    ] = None


class ObservingGroupDeleteResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None


class ObservingTemplateDeleteResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None


class OffsetCoordinate(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    ra_offset: Annotated[
        float | None,
        Field(
            description='Offset in the Right Ascension axis in arcsec of degrees.',
            ge=-1296000.0,
            le=1296000.0,
            title='Right Ascension Offset',
        ),
    ] = None
    dec_offset: Annotated[
        float | None,
        Field(
            description='Offset in the Declination axis in arcsec of degrees.',
            ge=-324000.0,
            le=324000.0,
            title='Declination Offset',
        ),
    ] = None
    exposure_number: Annotated[
        int | None, Field(description='Exposure number', le=99, title='Exposure number')
    ] = None


class PhaseScheduleObservingGroupPhaseSchedule(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    earliest_observe_date_millis: Annotated[
        int | None,
        Field(description='The earliest moment to observe, in Unix time milliseconds.'),
    ] = None
    tolerance: Duration | None = None
    period: Duration | None = None
    period_tolerance: Duration | None = None


class PhotometryAperture(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    optimal_aperture: bool | None = None
    fixed_aperture: Annotated[
        float | None, Field(description='Radius of the aperture in arcsec')
    ] = None
    ninety_six_percent_flux_aperture: bool | None = None


class PointingOffsetData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    token: str | None = None
    name: str | None = None
    offset: OffsetCoordinate | None = None
    label: int | None = None
    version: int | None = None
    user_token: Annotated[
        str | None,
        Field(
            description='this is the PI of the program that this entity will be recorded forif null should be derived using the program_data.contact_info.user_tokenif null, then a system ?? gross'
        ),
    ] = None
    instrument: Annotated[
        Instrument | None, Field(description='the instrument for the pointing')
    ] = None
    is_system: bool | None = None


class PointingOffsetDeleteResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None


class PointingOffsetGetResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    entity: PointingOffsetData | None = None
    error: Errors | None = None


class PointingOffsetListResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    entity: list[PointingOffsetData] | None = None
    error: Errors | None = None


class PointingOffsetUpdateRequest(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    runid: Annotated[
        str | None, Field(description='Unique identifier your science program.')
    ] = None
    token: str | None = None
    lock_version: Int32Value | None = None
    entity: PointingOffsetData | None = None


class PointingOffsetUpdateResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None
    entity: PointingOffsetData | None = None


class ProgramType(Enum):
    regular = 'REGULAR'
    target_of_opportunity = 'TARGET_OF_OPPORTUNITY'
    calibration = 'CALIBRATION'
    snapshot = 'SNAPSHOT'


class ProgramDataComments(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    question: str | None = None
    comment: str | None = None


class ProgramDataContactInfo(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    pi_first_name: str | None = None
    pi_last_name: str | None = None
    pi_email: str | None = None
    user_token: str | None = None


class ProgramInfoPiInfo(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    ldap_username: str | None = None
    email_address: str | None = None
    first_name: str | None = None
    last_name: str | None = None
    legacy_username: str | None = None
    user_token: str | None = None


class RollupValue(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    requested: int | None = None
    started: int | None = None
    observed: int | None = None
    validated: int | None = None


class SingleObservingGroup(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    observing_block: ObservingGroupDataObservingBlock | None = None


class CalibrationPosition(Enum):
    no_calibration_position = 'no_calibration_position'
    zenith = 'zenith'
    target = 'target'


class CalibrationMode(Enum):
    no_calibration_mode = 'no_calibration_mode'
    laser = 'laser'
    phase = 'phase'


class SitelleConfigurationDataCalibration(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    calibration_position: CalibrationPosition | None = None
    calibration_mode: CalibrationMode | None = None


class SitelleStatusCamera(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    iq: float | None = None
    iq_rms: float | None = None
    pixel_shift_x: float | None = None
    pixel_shift_y: float | None = None
    number_of_stars: int | None = None
    me: float | None = None


class SkyCoordinate(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    ra: Annotated[
        float | None,
        Field(
            description='Right Ascension in degrees.', le=360.0, title='Right Ascension'
        ),
    ] = None
    dec: Annotated[
        float | None,
        Field(
            description='Declination in degrees.',
            ge=-90.0,
            le=90.0,
            title='Declination',
        ),
    ] = None


class SpirouStatusExposureMeterProcessingResult(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    flux: float | None = None
    snr: float | None = None
    mid_exposure_date_millis: float | None = None
    spemsnr: Annotated[float | None, Field(description='Calculated SNR')] = None
    spemsnrc: float | None = None


class SpirouStatusGuiderProcessingResult(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    etime: float | None = None
    isustate: str | None = None
    sbdens_p: float | None = None
    hole_position_offset_x: float | None = None
    hole_position_offset_y: float | None = None
    star_to_null_position_offset_x: float | None = None
    star_to_null_position_offset_y: float | None = None
    magnitude_estimate: float | None = None
    seeing_estimate: float | None = None
    sgisust: Annotated[str | None, Field(description='per  160676372')] = None
    sggdst: str | None = None
    sgfrmrt: float | None = None
    sgetime: float | None = None
    sgnullx: float | None = None
    sgnully: float | None = None
    sgwinx0: float | None = None
    sgwiny0: float | None = None
    sgwinx1: float | None = None
    sgwiny1: float | None = None
    sgoffx0: float | None = None
    sgoffy0: float | None = None
    sgoffx1: float | None = None
    sgoffy1: float | None = None
    sgholex: float | None = None
    sgholey: float | None = None
    sgcholex: float | None = None
    sgcholey: float | None = None
    sgeholex: float | None = None
    sgeholey: float | None = None
    sgcstarx: float | None = None
    sgcstary: float | None = None
    sgestarx: float | None = None
    sgestary: float | None = None
    sgcnoffx: float | None = None
    sgcnoffy: float | None = None
    sgcsee: float | None = None
    sgesee: float | None = None
    sgcmagn: float | None = None
    sgemagn: float | None = None
    sgssee: float | None = None
    trg_type: str | None = None


class SpirouStatusPipelineProcessingResult(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    snr10: float | None = None
    snr34: float | None = None
    snr44: float | None = None
    dprtype: str | None = None
    ccfmask: float | None = None
    ccfmacpp: float | None = None
    ccfrv: float | None = None
    ccfcontr: float | None = None
    ccfrvc: float | None = None
    ccffwhm: float | None = None
    ccfmask_str: str | None = None


class Status(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    code: Annotated[
        int | None,
        Field(
            description='The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].'
        ),
    ] = None
    message: Annotated[
        str | None,
        Field(
            description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.'
        ),
    ] = None
    details: Annotated[
        list[GoogleProtobufAny] | None,
        Field(
            description='A list of messages that carry the error details.  There is a common set of message types for APIs to use.'
        ),
    ] = None


class SubTotalsData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    etime: RollupValue | None = None
    overheadtime: RollupValue | None = None
    exposure_count: RollupValue | None = None
    child_count: RollupValue | None = None
    etime_configured: RollupValue | None = None
    overhead_time_configured: RollupValue | None = None
    completeness: Annotated[
        float | None, Field(description='Percentage completed for the entity.')
    ] = None


class TargetDataFixedTarget(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    coordinate: SkyCoordinate | None = None
    proper_motion: FixedTargetProperMotion | None = None
    computed_coordinate: SkyCoordinate | None = None
    estimated_radial_velocity_kmps: DoubleValue | None = None


class TargetDataMagnitude(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    u: Annotated[DoubleValue | None, Field(alias='U')] = None
    b: Annotated[DoubleValue | None, Field(alias='B')] = None
    v: Annotated[DoubleValue | None, Field(alias='V')] = None
    r: Annotated[DoubleValue | None, Field(alias='R')] = None
    i: Annotated[DoubleValue | None, Field(alias='I')] = None
    g: Annotated[DoubleValue | None, Field(alias='G')] = None
    j: Annotated[DoubleValue | None, Field(alias='J')] = None
    h: Annotated[DoubleValue | None, Field(alias='H')] = None
    k: Annotated[DoubleValue | None, Field(alias='K')] = None
    uu: DoubleValue | None = None
    gg: DoubleValue | None = None
    rr: DoubleValue | None = None
    ii: DoubleValue | None = None
    zz: DoubleValue | None = None
    ab: Annotated[DoubleValue | None, Field(alias='AB')] = None


class TargetDeleteResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None


class TargetIdentifiers(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    catalog_identifier: Annotated[
        dict[str, ListOfIdentifiers] | None,
        Field(
            description='All catalogs resolved by simbad for this target key: catalog name, catalog_identifier.key === catalog_identifier.get(key).catalog value: catalog identifier.'
        ),
    ] = None
    two_mass: CatalogIdentifier | None = None
    gaia1: CatalogIdentifier | None = None
    gaia2: CatalogIdentifier | None = None
    resolved_catalog_identifier: CatalogIdentifier | None = None


class TargetMonitoringObservingGroupTimeConstraint(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    number_of_iterations: Annotated[
        int | None, Field(description='How many observations to take.')
    ] = None
    minimum_number_of_iterations: Annotated[
        int | None,
        Field(
            description='Minimum number of observations which still provides science value. If weather becomes an issue, this is used to determine if additional observations should be tried, or the whole observing group aborted to prioritize other observations. Cannot be greater than requested number of iterations.'
        ),
    ] = None
    time_interval: Duration | None = None
    time_interval_tolerance_min: Duration | None = None
    time_interval_tolerance_max: Duration | None = None
    t0_millis: Annotated[
        int | None,
        Field(
            description="Time the observing group should start being observed, in Unix time milliseconds. If omitted, CFHT will start observing at the QC's discretion."
        ),
    ] = None
    within_same_camera_run: Annotated[
        bool | None,
        Field(
            description='Whether all iterations need to occur within the same camera run.'
        ),
    ] = None


class View(Enum):
    requested = 'REQUESTED'
    actual = 'ACTUAL'


class TargetTimeData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    requested_integration_time: ITimeData | None = None
    actual_integration_time: ITimeData | None = None
    view: Annotated[
        View | None,
        Field(
            description='Which time clients should prefer showing users when presenting a single integration time for this data.\n\nREQUESTED - prefer requested_integration_time\nACTUAL - prefer actual_integration_time'
        ),
    ] = None
    exposure_count: Annotated[
        int | None,
        Field(
            description='The total number of exposures represented by the values here.\n\nThis value is the same for both views.'
        ),
    ] = None
    child_count: Annotated[
        int | None,
        Field(
            description='The total number of child entities represented by the values here.\n\nIf this is a program, these are observing groups.\nIf this is an observing group, these are observing blocks.\nIf this is an observing block, these are exposures.\n\nUseful for e.g. seeing the number of iterations configuredor completed on an Observing Group.\nThis value is the same for both views.'
        ),
    ] = None


class TelescopePatternDataConfig(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    name: str | None = None
    description: str | None = None
    charge_model: Annotated[
        str | None, Field(description='Used for calculating cost for this pattern')
    ] = None
    dithering: ConfigDithering | None = None
    nodding: ConfigNodding | None = None
    scale: float | None = None
    sybase_pat_id: BigInteger | None = None
    is_system: bool | None = None


class Type(Enum):
    object = 'OBJECT'
    target = 'TARGET'
    sky = 'SKY'
    dark = 'DARK'
    flat = 'FLAT'
    snap = 'SNAP'
    bias = 'BIAS'
    focus = 'FOCUS'
    align = 'ALIGN'
    comparison = 'COMPARISON'
    acquire = 'ACQUIRE'
    fabry_perot = 'FABRY_PEROT'
    twilight_flats = 'TWILIGHT_FLATS'
    photometry = 'PHOTOMETRY'
    sfocus = 'SFOCUS'


class TelescopePatternDataOffset(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    exposure_number: Annotated[
        int | None,
        Field(
            description='TODO: deprecate, no need to have duplicate information here.'
        ),
    ] = None
    offset: OffsetCoordinate | None = None
    type: Annotated[
        Type | None, Field(description='For dithering patterns type is always target')
    ] = None


class TelescopePatternDeleteResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None


class TimeAccountingStatus(Enum):
    not_started = 'NOT_STARTED'
    started = 'STARTED'
    observed = 'OBSERVED'
    validated = 'VALIDATED'


class TimeAccountingData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    configured_time: TargetTimeData | None = None
    charged_time: TargetTimeData | None = None
    validated_time_on_sky: TargetTimeData | None = None
    time_on_sky: TargetTimeData | None = None
    time_accounting_status: Annotated[
        TimeAccountingStatus | None,
        Field(description='Lifecycle state this entity is in.'),
    ] = None
    completion_ratio: Annotated[
        float | None,
        Field(
            description='Entity completion ratio, representing how much of the time configured has been charged.\n\nEqual to total charged time (as requested) divided by total configured time. For programs, if the total configured time is greater than the time allocated to the program, we divide by the time allocated instead.\nNote that if a program has INACTIVE observing groups that already have charged time, this could result in an inflated value here.',
            le=1.0,
        ),
    ] = None


class TimeConstraint(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    window: Annotated[
        list[ObservingBlockConditionWindow] | None,
        Field(
            description='Time windows during which the observation can be made. Windows can not overlap, and will always be stored in temporal order.'
        ),
    ] = None


class UpdateProgramCommentRequest(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    runid: Annotated[
        str | None, Field(description='Unique identifier for your science program')
    ] = None
    comment: Annotated[
        str | None, Field(description='Comment set by the PI for the CFHT QSO Team')
    ] = None


class UpdateProgramCommentsRequest(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    runid: Annotated[
        str | None, Field(description='Unique identifier for your science program')
    ] = None
    program_comment: Annotated[
        str | None, Field(description='Comment set by the PI for the CFHT QSO Team')
    ] = None
    operations_comment: Annotated[
        str | None, Field(description='Comment set by the CFHT QSO Team')
    ] = None


class UpenaProcessingResultH2oMm(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    raw_density: float | None = None
    at_zenith: float | None = None


class AllocationData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    run_id: str | None = None
    time_allocated_millis: int | None = None
    tac_rank: int | None = None
    tac_grade: str | None = None
    instrument: Instrument | None = None
    agency: AllocationDataAgency | None = None
    cfht_rank: int | None = None


class Constraint(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    image_quality: DoubleMinMax | None = None
    sky_background_max: float | None = None
    airmass_max: float | None = None
    extinction_max: float | None = None
    moon_distance_arc_length_min: float | None = None
    photometric: bool | None = None
    name: str | None = None
    sybase_cons_id: BigInteger | None = None
    h2o_vapor_max: float | None = None
    read_sky_background_name: str | None = None
    sky_background_name: str | None = None


class EspadonsStatusUpenaProcessingResult(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    iq: float | None = None
    h2o_column_density_from_telluric_lines: float | None = None
    radial_velocity_corrections: float | None = None
    snr_per_ccd_bin: float | None = None
    snr_per_spec_bin: float | None = None
    actual_wavelength: float | None = None
    snr_per_ccd_bin_polar: float | None = None
    snr_per_spec_bin_polar: float | None = None
    h2o_mm_data: UpenaProcessingResultH2oMm | None = None


class ExposureDataEspadonsStatus(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    instr_mode: str | None = None
    actual_wavelength: float | None = None
    snr_exp_meter: float | None = None
    snr_wave_meas_int: float | None = None
    snr_wave_meas_pol: float | None = None
    snr_meas_int_per_ccd_bin: float | None = None
    snr_meas_int_per_spec_bin: float | None = None
    snr_meas_polar_ccd_bin: float | None = None
    snr_meas_polar_spec_bin: float | None = None
    trg_type: str | None = None
    guider_seeing: float | None = None
    guider_seeing_processing_results: (
        EspadonsStatusGuiderSeeingProcessingResult | None
    ) = None
    exposure_meter_processing_results: (
        EspadonsStatusExposureMeterProcessingResult | None
    ) = None
    upena_processing_results: EspadonsStatusUpenaProcessingResult | None = None
    observation_type: str | None = None


class ExposureDataMegacamStatus(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    iq: float | None = None
    skybg: float | None = None
    elixir_eval: int | None = None
    elixir_seval: str | None = None
    snr: float | None = None
    atmospheric_transmission: float | None = None
    elixir_zeropoint: float | None = None
    actual_filter: str | None = None
    elixir_processing_result: MegacamStatusElixirProcessingResult | None = None


class ExposureDataSitelleStatus(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    camera_a: SitelleStatusCamera | None = None
    camera_b: SitelleStatusCamera | None = None
    relative_extinction: float | None = None
    relative_extinction_rms: float | None = None
    actual_filter: str | None = None


class ExposureDataSpirouStatus(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    acqtime: float | None = None
    acqtime1: str | None = None
    asic_num: str | None = None
    sca_id: str | None = None
    muxtype: int | None = None
    noutputs: int | None = None
    nadcs: int | None = None
    pddector: int | None = None
    clkoff: int | None = None
    warmtst: int | None = None
    clocking: int | None = None
    glbreset: int | None = None
    frmode: int | None = None
    camlink: int | None = None
    expmode: int | None = None
    nresets: int | None = None
    frmtime: float | None = None
    exptime: float | None = None
    acqtype: int | None = None
    datamode: int | None = None
    datlevel: int | None = None
    asicgain: int | None = None
    nomgain: int | None = None
    ampreset: int | None = None
    ktcremov: int | None = None
    srccur: int | None = None
    ampinput: int | None = None
    v4v3v2v1: str | None = None
    units: str | None = None
    tstation: str | None = None
    hxrgver: str | None = None
    mclk: float | None = None
    inttime: float | None = None
    frameno: int | None = None
    sb_adc_s: str | None = None
    sbadc1_p: float | None = None
    sbadc2_p: float | None = None
    sbcali_p: str | None = None
    sbdens_p: float | None = None
    sbrhb1_p: str | None = None
    sbrhb2_p: str | None = None
    sbetem_p: str | None = None
    sb_inj_t: float | None = None
    sb_pol_t: float | None = None
    sb_cs1_t: float | None = None
    sb_cs2_t: float | None = None
    sb_cb1_t: float | None = None
    sb_cb2_t: float | None = None
    sbiavl1s: str | None = None
    sbiavl2s: str | None = None
    sbetel_s: str | None = None
    sb_csc_s: str | None = None
    sbcref_p: str | None = None
    sbccas_p: str | None = None
    sbcden_p: float | None = None
    sbagit_s: str | None = None
    sbcmir_p: str | None = None
    sbclhc1s: str | None = None
    sbclhc1w: str | None = None
    sbclhc1c: float | None = None
    sbclhc2s: str | None = None
    sbclhc2w: str | None = None
    sbclhc2c: float | None = None
    sbclwl_s: str | None = None
    sbclwl_c: float | None = None
    sbwlsh_s: str | None = None
    sbctec_s: str | None = None
    sbctecct: float | None = None
    sbctecht: float | None = None
    sbccprit: float | None = None
    sbcccu_t: float | None = None
    sbccprot: float | None = None
    sbcfbi_t: float | None = None
    sbcwls_t: float | None = None
    sbclsuat: float | None = None
    sbcfpi_t: float | None = None
    sbcfpe_t: float | None = None
    sbcfpb_p: float | None = None
    sbvga_cp: float | None = None
    sbvga_ip: float | None = None
    sbvgb_cp: float | None = None
    sbvgb_ip: float | None = None
    sbmk00_t: float | None = None
    sbmk01_t: float | None = None
    sbmk02_t: float | None = None
    sbmk03_t: float | None = None
    sbmk04_t: float | None = None
    sbmk05_t: float | None = None
    sbmk06_t: float | None = None
    sbmk07_t: float | None = None
    sbls000t: float | None = None
    sbls001t: float | None = None
    sbls002t: float | None = None
    sbls003t: float | None = None
    sbls004t: float | None = None
    sbls005t: float | None = None
    sbls006t: float | None = None
    sbls007t: float | None = None
    sbls008t: float | None = None
    sbls009t: float | None = None
    sbls010t: float | None = None
    sbls011t: float | None = None
    sbls100t: float | None = None
    sbls101t: float | None = None
    sbls102t: float | None = None
    sbls103t: float | None = None
    sbls104t: float | None = None
    sbls105t: float | None = None
    sbls106t: float | None = None
    sbls107t: float | None = None
    sbls108t: float | None = None
    sbls109t: float | None = None
    sbls110t: float | None = None
    sbls111t: float | None = None
    sbl00i_t: float | None = None
    sbl00h_v: float | None = None
    sbl01i_t: float | None = None
    sbl01h_v: float | None = None
    sbl02i_t: float | None = None
    sbl02h_v: float | None = None
    sbl03i_t: float | None = None
    sbl03h_v: float | None = None
    sbl04i_t: float | None = None
    sbl04h_v: float | None = None
    sbl05i_t: float | None = None
    sbl05h_v: float | None = None
    sbl06i_t: float | None = None
    sbl06h_v: float | None = None
    sbl07i_t: float | None = None
    sbl07h_v: float | None = None
    sbl08i_t: float | None = None
    sbl08h_v: float | None = None
    sbl09i_t: float | None = None
    sbl09h_v: float | None = None
    sbl10i_t: float | None = None
    sbl10h_v: float | None = None
    sbl11i_t: float | None = None
    sbl11h_v: float | None = None
    sbl12i_t: float | None = None
    sbl12h_v: float | None = None
    sbl13i_t: float | None = None
    sbl13h_v: float | None = None
    seadc1_p: float | None = None
    seadc2_p: float | None = None
    sedens_p_deprecated: int | None = None
    sedens_p: float | None = None
    se_inj_t: float | None = None
    se_pol_t: float | None = None
    se_cs1_t: float | None = None
    se_cs2_t: float | None = None
    se_cb1_t: float | None = None
    se_cb2_t: float | None = None
    sectecct: float | None = None
    sectecht: float | None = None
    seccprit: float | None = None
    secccu_t: float | None = None
    seccprot: float | None = None
    secfbi_t: float | None = None
    secwls_t: float | None = None
    seclhc1c: float | None = None
    seclhc2c: float | None = None
    seclwl_c: float | None = None
    seclsuat: float | None = None
    secfpi_t: float | None = None
    secfpe_t: float | None = None
    secfpb_p: float | None = None
    sevga_cp: float | None = None
    sevga_ip: float | None = None
    sevgb_cp: float | None = None
    sevgb_ip: float | None = None
    semk00_t: float | None = None
    semk01_t: float | None = None
    semk02_t: float | None = None
    semk03_t: float | None = None
    semk04_t: float | None = None
    semk05_t: float | None = None
    semk06_t: float | None = None
    semk07_t: float | None = None
    sels000t: float | None = None
    sels001t: float | None = None
    sels002t: float | None = None
    sels003t: float | None = None
    sels004t: float | None = None
    sels005t: float | None = None
    sels006t: float | None = None
    sels007t: float | None = None
    sels008t: float | None = None
    sels009t: float | None = None
    sels010t: float | None = None
    sels011t: float | None = None
    sels100t: float | None = None
    sels101t: float | None = None
    sels102t: float | None = None
    sels103t: float | None = None
    sels104t: float | None = None
    sels105t: float | None = None
    sels106t: float | None = None
    sels107t: float | None = None
    sels108t: float | None = None
    sels109t: float | None = None
    sels110t: float | None = None
    sels111t: float | None = None
    sel00i_t: float | None = None
    sel00h_v: float | None = None
    sel01i_t: float | None = None
    sel01h_v: float | None = None
    sel02i_t: float | None = None
    sel02h_v: float | None = None
    sel03i_t: float | None = None
    sel03h_v: float | None = None
    sel04i_t: float | None = None
    sel04h_v: float | None = None
    sel05i_t: float | None = None
    sel05h_v: float | None = None
    sel06i_t: float | None = None
    sel06h_v: float | None = None
    sel07i_t: float | None = None
    sel07h_v: float | None = None
    sel08i_t: float | None = None
    sel08h_v: float | None = None
    sel09i_t: float | None = None
    sel09h_v: float | None = None
    sel10i_t: float | None = None
    sel10h_v: float | None = None
    sel11i_t: float | None = None
    sel11h_v: float | None = None
    sel12i_t: float | None = None
    sel12h_v: float | None = None
    sel13i_t: float | None = None
    sel13h_v: float | None = None
    guider_processing: SpirouStatusGuiderProcessingResult | None = None
    exposure_meter_processing: SpirouStatusExposureMeterProcessingResult | None = None
    pipeline_processing: SpirouStatusPipelineProcessingResult | None = None


class FindingChartData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    comment: str | None = None
    url: str | None = None
    token: str | None = None
    staff_approval: FindingChartDataApproval | None = None
    pi_approval: FindingChartDataApproval | None = None
    target_token: str | None = None


class InstrumentConfigurationDataSitelleConfigurationData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    filter: Filter1 | None = None
    binning: Binning1 | None = None
    resolution: int | None = None
    snrwavelength: Annotated[
        float | None,
        Field(description='This should be on target too , sitell, espedons, spirou'),
    ] = None
    calibration: SitelleConfigurationDataCalibration | None = None
    resolution_mode: ResolutionMode | None = None
    needs_precision: bool | None = None
    needs_flux_calibration: bool | None = None
    needs_target_calibration: bool | None = None


class InstrumentConfigurationDataSpirouConfigurationData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    template_name: Annotated[str | None, Field(description='Deprecated fields')] = None
    observing_mode: ObservingMode1 | None = None
    stokes_parameter: StokesParameter | None = None
    mode: Mode | None = None
    sky_observation: SkyObservation | None = None
    number_of_sequences: Annotated[
        int | None,
        Field(
            description='Each sequence is 1 exposure for Star mode and 4 exposures for ObservingMode'
        ),
    ] = None
    use_snr: Annotated[
        bool | None, Field(description='when true - use SNR for stoping exposures')
    ] = None
    sky_etime_millis: Int64Value | None = None


class MegacamConfigurationDataPhotometry(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    aperture: PhotometryAperture | None = None
    psf: bool | None = None


class MovingTargetEphemeris(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    mjd: Annotated[
        float | None,
        Field(
            description='Modified Julian date when the target is at this coordinate.'
        ),
    ] = None
    coordinate: SkyCoordinate | None = None
    computed_coordinate: SkyCoordinate | None = None


class ObservingBlockCondition(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    pre_requisite: Annotated[
        list[ObservingBlockConditionRequisite] | None,
        Field(
            description='Pre-requisite conditions before each observing block can be started. The index of items in this list corresponds directly to the index of the observing block on the observing group i.e. this list is one-to-one with read_observing_block.'
        ),
    ] = None
    window: Annotated[
        list[ObservingBlockConditionWindow] | None,
        Field(
            description='Time windows during which the observing block can be observed. Windows can not overlap, and will always be stored in temporal order.'
        ),
    ] = None


class ObservingGroupContext(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    iteration_count: Annotated[
        int | None,
        Field(
            description='The iteration number this object was part of in the observing group'
        ),
    ] = None
    iteration_total: Annotated[
        int | None,
        Field(
            description='The total number of iterations requested for the observing group'
        ),
    ] = None
    iteration_minimum: Annotated[
        int | None,
        Field(
            description='Minimum number of iterations this OG needs to provide science value'
        ),
    ] = None
    window: Annotated[
        list[ObservingBlockConditionWindow] | None,
        Field(description='Sorted by from past -> future on the observe_after key'),
    ] = None
    observing_group_token: str | None = None
    observing_group_priority: ObservingGroupPriority | None = None
    observing_group_state: ObservingGroupState | None = None
    observing_group_label: int | None = None
    observing_group_version: Annotated[
        int | None,
        Field(description='Increments every time the observing group changes.'),
    ] = None
    legacy_reel: LegacyReel | None = None
    single: bool | None = None
    target_monitoring: TargetMonitoringObservingGroupTimeConstraint | None = None
    phase_schedule: PhaseScheduleObservingGroupPhaseSchedule | None = None
    time_accounting: TimeAccountingData | None = None
    exposure_type: Annotated[ExposureType | None, Field(alias='exposureType')] = None
    use_group_dither_scheme: bool | None = None


class PhaseScheduleObservingGroup(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    observing_block: ObservingGroupDataObservingBlock | None = None
    phase_schedule: PhaseScheduleObservingGroupPhaseSchedule | None = None


class ProgramData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    title: str | None = None
    abstract: str | None = None
    contact_info: ProgramDataContactInfo | None = None
    comment: list[ProgramDataComments] | None = None
    sybase_pi_user_id: Annotated[str | None, Field(alias='sybasePiUserId')] = None
    sub_totals: SubTotalsData | None = None
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier for the program. Used interchangeably with "runid".'
        ),
    ] = None
    time_allocation: list[AllocationData] | None = None
    release_date_millis: int | None = None
    metadata_release_date_millis: int | None = None
    comment_field: str | None = None
    program_type: ProgramType | None = None
    distribution_hash: str | None = None
    time_accounting: TimeAccountingData | None = None
    operations_comment_field: str | None = None
    last_data_acquisition_notification_date_millis: int | None = None
    dynamic_exposure_time_limit: DynamicExposureTimeLimit | None = None


class RollupFields(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    i_time: RollupValue | None = None
    i_time_configured: RollupValue | None = None
    sub_totals: SubTotalsData | None = None


class TargetDataLinkedTargetIdentifiers(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    pi_confirmed_identifiers: TargetIdentifiers | None = None
    custom_target: Annotated[
        bool | None,
        Field(
            description='Used to indicate this is a target without known identifiers.'
        ),
    ] = None


class TargetDataMovingTarget(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    ephemeris_point: Annotated[
        list[MovingTargetEphemeris] | None,
        Field(
            description="The ephemerides that define the path of motion for the target. Must be provided using topocentric astrometric coordinates. Do not provide apparent coordinates. CFHT strongly recommends the use of JPL Horizons System for generating the proper coordinates. CFHT's observatory code is T14. At least five distinct positions must be provided that span the desired observing period. The first position should be well in advance of the observation. The positions do not need to be uniformly sampled throughout the desired observing period. The points will be interpolated to determine the position of the target at the time of observation, at which point there must be at least one ephemeris point defined in the past, and at least four defined in the future."
        ),
    ] = None


class TargetMonitoringObservingGroup(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    observing_block: ObservingGroupDataObservingBlock | None = None
    time_constraint: TargetMonitoringObservingGroupTimeConstraint | None = None


class TelescopePatternData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    offsets: Annotated[
        list[TelescopePatternDataOffset] | None,
        Field(
            description='Should only be set if manually specifying custom dithering patterns'
        ),
    ] = None
    config: TelescopePatternDataConfig | None = None
    token: str | None = None
    label: int | None = None
    version: int | None = None
    user_token: str | None = None
    instrument: Instrument | None = None
    is_system: bool | None = None
    name: str | None = None
    offset_coordinate: list[OffsetCoordinate] | None = None


class TelescopePatternListResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    entity: list[TelescopePatternData] | None = None
    error: Errors | None = None


class TelescopePatternUpdateRequest(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    runid: str | None = None
    token: str | None = None
    lock_version: Int32Value | None = None
    entity: TelescopePatternData | None = None


class TelescopePatternUpdateResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None
    entity: TelescopePatternData | None = None


class UpdateProgramCommentResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    program_data: ProgramData | None = None
    error: Errors | None = None


class UpdateProgramCommentsResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    program_data: ProgramData | None = None
    error: Errors | None = None


class EphemeridesUpdateRequest(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    runid: Annotated[
        str | None, Field(description='Unique identifier of the science program.')
    ] = None
    token: Annotated[str | None, Field(description='Unique identifier of the target.')] = (
        None
    )
    ephemeris: Annotated[
        list[MovingTargetEphemeris] | None,
        Field(description='List of ephemerides to set on the target.'),
    ] = None


class ExposureDataExposureStatus(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    megacam_status: ExposureDataMegacamStatus | None = None
    wircam_status: ExposureDataWircamStatus | None = None
    espadons_status: ExposureDataEspadonsStatus | None = None
    sitelle_status: ExposureDataSitelleStatus | None = None
    spirou_status: ExposureDataSpirouStatus | None = None
    wena_status: ExposureDataWenaStatus | None = None
    exposure_time: ExposureTime | None = None
    exp_date_mjd: float | None = None
    queue_name: str | None = None
    exp_type: str | None = None
    exp_status: ExpStatus | None = None
    is_photometric: bool | None = None
    obs_comment: str | None = None
    seq_comment: str | None = None
    actual_pointing: SkyCoordinate | None = None
    actual_sky: float | None = None
    actual_airmass: float | None = None
    actual_moondist: float | None = None
    observer_comment: str | None = None
    qc_comment: str | None = None
    file: ExposureStatusFile | None = None
    credited_qcoordinator: str | None = None
    credited_observer: str | None = None
    grade: int | None = None
    read_obs_date_utc: str | None = None
    read_obs_date_hst: str | None = None
    read_actual_sky_name: str | None = None
    ra: Annotated[str | None, Field(description='Values from headers')] = None
    dec: str | None = None
    cmmtobs: str | None = None
    cmmtseq: str | None = None
    pi_name: str | None = None
    nexp: str | None = None
    cmpltexp: str | None = None
    ha: str | None = None
    read_obs_date_millis: int | None = None
    object: str | None = None


class InstrumentConfigurationDataMegacamConfigurationData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    filter: Filter | None = None
    binning: Binning | None = None
    is_dynamic_exposure_time: Annotated[
        bool | None,
        Field(
            description="TODO: is this needed billy? Can we use presence of snr or not to decide? I THINK SO.  We have the capability to calculate SNR on every exposure, but we aren't necessarily doing SNR mode observations with everything"
        ),
    ] = None
    minimum_exposures: int | None = None
    min_exptime_ms: int | None = None
    max_exptime_ms: int | None = None
    mag_ab: Annotated[
        float | None,
        Field(
            alias='magAB',
            description='TODO: interesting field here because associated with the target, but in the legacy mp snr mode, the mag is carried with the IC! so have to go back to this :(',
        ),
    ] = None
    snr_mode: SnrMode | None = None
    etc_photometry: MegacamConfigurationDataPhotometry | None = None


class ObservingGroupData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    token: Annotated[
        str | None, Field(description='Unique identifier for the observing group.')
    ] = None
    label: Annotated[
        int | None,
        Field(
            description='Index of the observing group within the program, set by the system automatically. Used for reference in communications with QSO staff. storage: transient api_visibility: read only'
        ),
    ] = None
    og_priority: Annotated[
        OgPriority | None,
        Field(
            description='Priority of observing this observing group, relative to other observing groups within the same program.'
        ),
    ] = None
    single_observing_group: SingleObservingGroup | None = None
    target_monitoring_observing_group: TargetMonitoringObservingGroup | None = None
    phase_schedule_observing_group: PhaseScheduleObservingGroup | None = None
    read_observing_block: Annotated[
        list[ObservingGroupDataObservingBlock] | None,
        Field(
            description='The observing blocks that have been created based on the entered configuration. api_visibility: read only'
        ),
    ] = None
    observing_block_condition: Annotated[
        dict[str, ObservingBlockCondition] | None,
        Field(
            description='The requirements that have been set for observing each observing blocks based on the entered configuration. api_visibility: read only'
        ),
    ] = None
    minimum_observing_block_count: Annotated[
        int | None,
        Field(
            description='This field is unused, please ignore. api_visibility: read only'
        ),
    ] = None
    time_accounting: TimeAccountingData | None = None
    state: Annotated[
        State | None,
        Field(
            description='State of the observing group, based off of the time accounting status.'
        ),
    ] = None
    version: Annotated[
        int | None,
        Field(
            description='Increments when this object updates. storage: transient api_visibility: read only, incremented by the server'
        ),
    ] = None
    legacy_reel: LegacyReel | None = None
    time_constraint: TimeConstraint | None = None
    target_type: Annotated[
        TargetType | None,
        Field(
            description='This can be used to configure calibration observing groups. For internal use only. api_visibility: operations write only'
        ),
    ] = None
    dither_scheme: Annotated[
        DitherScheme | None,
        Field(
            description='Used to customize the order of observation when observing multiple targets with the same telescope pattern within this observing group.'
        ),
    ] = None
    low_surface_brightness: Annotated[
        bool | None,
        Field(
            description='Indicates the observing group uses low surface brightness (LSB) mode.with'
        ),
    ] = None


class ObservingGroupListResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    entity: list[ObservingGroupData] | None = None
    error: Errors | None = None


class ObservingGroupUpdateResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None
    entity: ObservingGroupData | None = None


class ProgramInfo(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    program_data: ProgramData | None = None
    rollup_fields: RollupFields | None = None
    time_accounting: TimeAccountingData | None = None
    pi_info: ProgramInfoPiInfo | None = None
    version: int | None = None


class TargetData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier for the target. When creating a new target, this will be inferred from the request data if left blank here. Must begin with the program token followed by a dash, e.g. 20AE01-0123456789'
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(
            description='Name for the target entered by PI, or primary name as resolved by CDS. Will become OBJECT in the FITS header. Required. Length limited to 39 characters. Allowed characters are letters, numbers, spaces, or any of: !@#$%^&*()_-+.,?/[]<>'
        ),
    ] = None
    label: Annotated[
        int | None,
        Field(
            description='Index of the target within the program, set by the system automatically. Used for reference to targets in communications with QSO staff. storage: transient api_visibility: read only'
        ),
    ] = None
    version: Annotated[
        int | None,
        Field(
            description='Increments when this object updates. storage: transient api_visibility: read only, incremented by the server'
        ),
    ] = None
    fixed_target: TargetDataFixedTarget | None = None
    moving_target: TargetDataMovingTarget | None = None
    magnitude: TargetDataMagnitude | None = None
    temperature_effective: Annotated[
        float | None,
        Field(
            description='The estimated/measured effective temperature, in Kelvin. Required for targets observed with SPIRou or ESPaDOnS. Not used for MegaCam.'
        ),
    ] = None
    standard_star: Annotated[
        bool | None,
        Field(
            description='Whether the star is a "standard" star, to be observed each time other science targets are observed. Not used for MegaCam.'
        ),
    ] = None
    linked_target_identifiers: TargetDataLinkedTargetIdentifiers | None = None
    finding_chart: Annotated[
        list[FindingChartData] | None,
        Field(
            description='A read-only view of the finding charts for this target. To create or update finding charts, see the FindingChartService. storage: transient api_visibility: read only'
        ),
    ] = None
    pointing_offset_token: Annotated[
        str | None,
        Field(
            description='The token of a pointing offset which should be used when observing this target. To view or manage pointing offsets, see the PointingOffsetService.'
        ),
    ] = None
    pointing_offset: PointingOffsetData | None = None


class TargetListResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    entity: list[TargetData] | None = None
    error: Errors | None = None


class TargetShowResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None
    entity: TargetData | None = None


class TargetUpdateRequest(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    runid: Annotated[
        str | None, Field(description='Unique identifier of the science program.')
    ] = None
    entity: TargetData | None = None
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier of the target. If a target with this token already exists, it will be updated, otherwise it will be created. Must begin with the program token followed by a dash, e.g. 20AE01-0123456789'
        ),
    ] = None
    lock_version: Int32Value | None = None
    instrument: Annotated[
        Instrument | None,
        Field(
            description='If specified, instrument-specific validation checks will be performed.'
        ),
    ] = None


class TargetUpdateResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None
    entity: TargetData | None = None


class EphemeridesUpdateResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None
    entity: TargetData | None = None


class InstrumentConfigurationData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    espadons_configuration: (
        InstrumentConfigurationDataEspadonsConfigurationData | None
    ) = None
    megacam_configuration: (
        InstrumentConfigurationDataMegacamConfigurationData | None
    ) = None
    wircam_configuration: InstrumentConfigurationDataWircamConfigurationData | None = (
        None
    )
    sitelle_configuration: (
        InstrumentConfigurationDataSitelleConfigurationData | None
    ) = None
    spirou_configuration: InstrumentConfigurationDataSpirouConfigurationData | None = (
        None
    )
    wena_configuration: InstrumentConfigurationDataWenaConfigurationData | None = None
    sybase_ic_id: BigInteger | None = None
    etime_or_snr: ExposureTime | None = None
    sybase_cons_id: BigInteger | None = None
    tracking: Tracking | None = None


class ListProgramsResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    entity: list[ProgramInfo] | None = None
    error: Errors | None = None


class ObservingTemplateData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    instrument_configuration: InstrumentConfigurationData | None = None
    constraint: Constraint | None = None
    telescope_pattern: TelescopePatternData | None = None
    charge_model: Annotated[
        str | None,
        Field(
            description='Used for calculating cost for this pattern Invokes code which reads the ExposureInstructions and attributes a cost to it.'
        ),
    ] = None
    itime: int | None = None
    calculate_etime: ExposureTime | None = None
    acquisition_time: ExposureTime | None = None
    token: str | None = None
    associated_observing_blocks: Annotated[
        list[BigInteger] | None,
        Field(
            description='When just creating an OT, this list is empty When this OT belongs to an OG, then any OBs in sybase that this OT is related too must be filled in. select * from blah where (select id from prg where prg Query to find related OBs is, select ob.* from ob, prg where ob.prg_id = prg.id and prg.runid=?     instrument_configuration.sybase_ic_id, constraint.sybase_cons_idselect ob.* from ob, prg, icseq where ob.prg_id = prg.idand prg.runid=<runid>and icseq.ob_id=ob.id and ob.con_id = <constraint.sybase_cons_id>and icseq.ic_id = <instrument_configuration.sybase_ic_id>;'
        ),
    ] = None
    name: str | None = None
    total_exposure_count: int | None = None
    label: int | None = None
    version: Annotated[
        int | None,
        Field(
            description='Increments when this object updates storage: transient api_visibility: read only, incremented by the server'
        ),
    ] = None
    telescope_pattern_token: str | None = None
    telescope_pattern_scale: float | None = None
    megacam_cumulative_snr_system_generated: bool | None = None


class ObservingTemplateListResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    entity: list[ObservingTemplateData] | None = None
    error: Errors | None = None


class ObservingTemplateUpdateRequest(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    runid: str | None = None
    token: str | None = None
    entity: ObservingTemplateData | None = None
    lock_version: Int32Value | None = None


class ObservingTemplateUpdateResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None
    entity: ObservingTemplateData | None = None


class ExposureData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    token: str | None = None
    obsid: str | None = None
    exposure_number: int | None = None
    iteration: int | None = None
    parent_exposure_token: str | None = None
    exposure_status: ExposureDataExposureStatus | None = None
    observing_template: ObservingTemplateData | None = None
    target: TargetData | None = None
    observing_group_context: ObservingGroupContext | None = None
    all_derivations_complete: Annotated[
        bool | None,
        Field(
            description='When false, there is data which is still being calculated for this exposure. Data can still be displayed, but the client should attempt to refresh the data.'
        ),
    ] = None
    queue_run_id: str | None = None
    camera_run_id: str | None = None
    prg_run_id: str | None = None
    observing_component_token: str | None = None
    sub_totals: SubTotalsData | None = None
    attribution: ExposureDataAttribution | None = None
    version: Annotated[
        int | None,
        Field(
            description='Increments when this object updates storage: transient api_visibility: read only, incremented by the server'
        ),
    ] = None


class ObservingGroupUpdateRequest(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    runid: Annotated[
        str | None, Field(description='Unique identifier of the science program.')
    ] = None
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier of the observing group. If an observing group target with this token already exists, it will be updated, otherwise it will be created. Must begin with the program token followed by a dash, e.g. 20AE01-0123456789'
        ),
    ] = None
    entity: ObservingGroupData | None = None
    target: Annotated[
        dict[str, TargetData] | None,
        Field(
            description='If creating or updating targets with this request, set the data here. Key is the unique identifier of the target and must be prefixed with the runid. Value is the target data and must be valid. Otherwise, the whole request will fail. Observing components can then reference the unique identifier (the map key) in this same request.'
        ),
    ] = None
    observing_template: Annotated[
        dict[str, ObservingTemplateData] | None,
        Field(
            description='If creating or updating observing templates with this request, set the data here. Key is the unique identifier of the observing template and must be prefixed with the runid. Value is the observing template data and must be valid. Otherwise, the whole request will fail. Observing components can then reference the unique identifier (the map key) in this same request.'
        ),
    ] = None
    lock_version: Int32Value | None = None


class SnrBlockDataSnrBlockObservingComponents(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    observing_component_token: Annotated[
        str | None, Field(description='the observing component')
    ] = None
    observing_group_token: Annotated[
        str | None, Field(description='should not be here, should be in the parent')
    ] = None
    is_primary: Annotated[bool | None, Field(description='is it the original oc?')] = (
        None
    )
    configured_exposures: int | None = None
    exposures: list[ExposureData] | None = None
    ob_label: int | None = None
    target_token: str | None = None
    observing_template_token: str | None = None


class SnrBlockData(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    token: str | None = None
    label: int | None = None
    cumulative_snr: Annotated[
        float | None,
        Field(
            description='the total snr achieved of all exposures  of all observing components of this snr block'
        ),
    ] = None
    carry_forward_snr: Annotated[
        float | None,
        Field(
            description='if the program is copied to a new program possibly for a new semester  the cumulative snr will be moved to the carry_forward_snr and the  carry forward snr will be counted in the cumulative snr of the new program'
        ),
    ] = None
    observing_components: list[SnrBlockDataSnrBlockObservingComponents] | None = None
    version: int | None = None
    requested_target_magnitude: Annotated[
        float | None, Field(description='this will come from the target')
    ] = None
    requested_cumulative_snr: Annotated[
        float | None, Field(description='this will come from the OT')
    ] = None
    requested_minimum_exposures: int | None = None
    total_exposures: Annotated[
        int | None,
        Field(
            description='counting the total validated exposures for this OC (OT/TARGET)'
        ),
    ] = None
    primary_observing_group_token: str | None = None
    primary_observing_component_token: str | None = None
    primary_observing_group_label: int | None = None
    total_configured_exposures: Annotated[
        int | None,
        Field(description='counting the total configured exposures for this OC'),
    ] = None


class SnrBlockListResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None
    entity: list[SnrBlockData] | None = None


class AddSingleToSnrBlockResponse(CFHTBaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    success: bool | None = None
    error: Errors | None = None
    snr_block: SnrBlockData | None = None
    observing_group: ObservingGroupData | None = None
