# Auto generated file, do not edit
# ruff: noqa: E741
# generated by datamodel-codegen:
#   filename:  cfht.openapi3.json
#   timestamp: 2026-07-02T00:42:01+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import Base64Str, BaseModel, Field


class AllocationDataAgency(BaseModel):
    letter: str | None = None
    name: str | None = None


class CalibrationCalibrationMode(Enum):
    no_calibration_mode = 'no_calibration_mode'
    laser = 'laser'
    phase = 'phase'


class CalibrationCalibrationPosition(Enum):
    no_calibration_position = 'no_calibration_position'
    zenith = 'zenith'
    target = 'target'


class ConfigDithering(BaseModel):
    is_staring: Annotated[bool | None, Field(alias='isStaring')] = None


class EspadonsStatusGuiderSeeingProcessingResult(BaseModel):
    guider_seeing: Annotated[float | None, Field(alias='guiderSeeing')] = None


class ExposureDataAttribution(BaseModel):
    runid: str | None = None
    observing_block_label: Annotated[
        str | None,
        Field(
            title='If displaying the observing block to the user, this uniquely identifies it in the context\nof an observing group, i.e. OG3-2'
        ),
    ] = None
    observing_block_label_int: Annotated[
        int | None, Field(title='Label of the observing block')
    ] = None
    observing_block_token: Annotated[
        str | None,
        Field(
            alias='observingBlockToken',
            description='Token of the observing block this exposure is attributed to.',
        ),
    ] = None
    observing_group_label: Annotated[
        int | None,
        Field(
            alias='observingGroupLabel',
            description='Label of the observing group this exposure is attributed to.',
        ),
    ] = None
    observing_group_token: Annotated[
        str | None,
        Field(
            alias='observingGroupToken',
            description='Token of the observing group this exposure is attributed to.',
        ),
    ] = None
    observing_component_token: Annotated[
        str | None,
        Field(
            alias='observingComponentToken',
            description='Token of the observing component this exposure is attributed to.',
        ),
    ] = None
    exposure_number: Annotated[
        int | None,
        Field(
            alias='exposureNumber',
            description='exposure number this exposure is attributed to.',
        ),
    ] = None
    instrument_run: Annotated[
        str | None, Field(title='the queue run this exposure was taken under')
    ] = None
    attributing_agency: Annotated[
        str | None, Field(alias='attributingAgency', title='the agency id')
    ] = None
    tac_rank: Annotated[int | None, Field(alias='tacRank')] = None
    tac_grade: Annotated[str | None, Field(alias='tacGrade')] = None


class ExposureDataEspadonsStatusExposureMeterProcessingResult(BaseModel):
    snr: float | None = None


class ExposureDataSpirouStatusExposureMeterProcessingResult(BaseModel):
    flux: float | None = None
    snr: float | None = None
    mid_exposure_date_millis: Annotated[
        float | None, Field(alias='midExposureDateMillis')
    ] = None
    spemsnr: Annotated[float | None, Field(title='Calculated SNR')] = None
    spemsnrc: float | None = None


class ExposureDataWenaStatus(BaseModel):
    pass


class ExposureDataWircamStatus(BaseModel):
    iq_uncertainty: Annotated[float | None, Field(alias='iqUncertainty')] = None
    absorption: float | None = None
    absorption_uncertainty: Annotated[
        float | None, Field(alias='absorptionUncertainty')
    ] = None
    number_of_stars_iq: Annotated[int | None, Field(alias='numberOfStarsIq')] = None
    number_of_stars_absorption: Annotated[
        int | None, Field(alias='numberOfStarsAbsorption')
    ] = None
    absolute_sky_level: Annotated[float | None, Field(alias='absoluteSkyLevel')] = None
    elongation: float | None = None
    mdcoords: int | None = None
    mdrepeat: int | None = None
    actual_filter: Annotated[str | None, Field(alias='actualFilter')] = None
    iq: float | None = None


class ExposureStatusFile(BaseModel):
    absolute_path: Annotated[
        str | None,
        Field(
            alias='absolutePath',
            description='Absolute path to directory file is homed in. Starts with / and ends with /.',
        ),
    ] = None
    base_name: Annotated[
        str | None, Field(alias='baseName', title='Name of file without extension')
    ] = None
    ext: Annotated[str | None, Field(description='Name of extenion including .')] = None


class FindingChartDataApproval(BaseModel):
    approved_at_millis: Annotated[str | None, Field(alias='approvedAtMillis')] = None
    approved_by_usertoken: Annotated[str | None, Field(alias='approvedByUsertoken')] = (
        None
    )


class FixedTargetProperMotion(BaseModel):
    ra_mas: Annotated[
        float | None,
        Field(
            alias='raMas',
            description='Motion in the right ascension axis in milliarcseconds/year.',
        ),
    ] = None
    dec_mas: Annotated[
        float | None,
        Field(
            alias='decMas',
            description='Motion in the declination axis in milliarcseconds/year.',
        ),
    ] = None


class InstrumentConfigurationDataEspadonsConfigurationDataOObservingMode(Enum):
    polarimetry = 'Polarimetry'
    spectroscopy_star_only = 'Spectroscopy_star_only'
    spectroscopy_star_sky = 'Spectroscopy_star_sky'


class InstrumentConfigurationDataMegacamConfigurationDataBinning(Enum):
    one_one = 'one_one'
    two_two = 'two_two'
    three_three = 'three_three'
    four_four = 'four_four'


class InstrumentConfigurationDataMegacamConfigurationDataFilter(Enum):
    unknown = 'Unknown'
    u = 'u'
    g = 'g'
    i = 'i'
    r = 'r'
    z = 'z'
    gri = 'gri'
    ca_hk = 'CaHK'
    ha = 'Ha'
    ha_off = 'HaOFF'
    oiii = 'OIII'
    oiiioff = 'OIIIOFF'
    u_s = 'uS'
    g_s = 'gS'
    r_s = 'rS'
    i_s = 'iS'
    z_s = 'zS'
    n393_s = 'N393S'
    ha_s = 'HaS'
    ha_offs = 'HaOFFS'
    ti_os = 'TiOS'
    cns = 'CNS'
    oiiis = 'OIIIS'
    phgs = 'PHGS'
    m4112 = 'M4112'
    m4376 = 'M4376'


class InstrumentConfigurationDataSitelleConfigurationDataBinning(Enum):
    one_one = 'one_one'
    two_two = 'two_two'
    three_three = 'three_three'


class InstrumentConfigurationDataSitelleConfigurationDataFilter(Enum):
    unknown = 'UNKNOWN'
    none = 'NONE'
    c1 = 'C1'
    c2 = 'C2'
    c3 = 'C3'
    c4 = 'C4'
    sn1 = 'SN1'
    sn2 = 'SN2'
    sn3 = 'SN3'
    sn4 = 'SN4'
    sn5 = 'SN5'
    sn6 = 'SN6'


class InstrumentConfigurationDataSpirouConfigurationDataOObservingMode(Enum):
    polarimetry = 'Polarimetry'
    star = 'Star'


class InstrumentConfigurationDataTracking(Enum):
    unknown = 'Unknown'
    sid = 'SID'
    nonsid = 'NONSID'
    sid_nog = 'SID_NOG'
    nonsid_g = 'NONSID_G'


class InstrumentConfigurationDataWenaConfigurationData(BaseModel):
    pass


class InstrumentConfigurationDataWircamConfigurationDataFilter(Enum):
    unknown = 'UNKNOWN'
    w = 'W'
    h = 'H'
    j = 'J'
    ks = 'Ks'
    y = 'Y'
    h2 = 'H2'
    k_cont = 'KCont'
    ch4_on = 'CH4On'
    ch4_off = 'CH4Off'
    low_oh1 = 'LowOH1'
    low_oh2 = 'LowOH2'
    br_g = 'BrG'
    co = 'CO'
    c_onar = 'COnar'


class MMode(Enum):
    dark = 'Dark'
    fabry_perot = 'Fabry_Perot'
    wave_hc1 = 'Wave_Hc1'
    wave_hc2 = 'Wave_Hc2'
    flat = 'FLAT'


class MegacamConfigurationDataSnrMode(Enum):
    none = 'NONE'
    standard = 'STANDARD'
    cumulative = 'CUMULATIVE'
    zero_point = 'ZERO_POINT'


class MegacamStatusElixirProcessingResult(BaseModel):
    iq: float | None = None
    sky_background: Annotated[float | None, Field(alias='skyBackground')] = None
    snr: float | None = None
    zeropoint: float | None = None


class ObservingBlockConditionRequisite(BaseModel):
    requisite_observing_block_index: Annotated[
        int | None,
        Field(
            alias='requisiteObservingBlockIndex',
            description='This should match the index of the observing block in the\nread_observing_block list.',
        ),
    ] = None
    wait_period_min_millis: Annotated[
        str | None,
        Field(
            alias='waitPeriodMinMillis',
            description='Minimum time to wait after requisite observing block exposure has\nbeen taken.',
        ),
    ] = None
    wait_period_millis: Annotated[
        str | None,
        Field(
            alias='waitPeriodMillis',
            description='Optimal to wait after requisite observing block exposure has\nbeen taken.',
        ),
    ] = None
    wait_period_max_millis: Annotated[
        str | None,
        Field(
            alias='waitPeriodMaxMillis',
            description='Minimum time to wait after requisite observing block exposure has\nbeen taken.',
        ),
    ] = None
    unbounded: Annotated[
        bool | None,
        Field(
            description='If this observation can happen any time after the requisite.'
        ),
    ] = None


class ObservingBlockConditionWindow(BaseModel):
    observe_after: Annotated[
        str | None,
        Field(
            alias='observeAfter',
            description='Start of the observation window, in Unix time milliseconds.',
        ),
    ] = None
    observe_before: Annotated[
        str | None,
        Field(
            alias='observeBefore',
            description='End of the observation window, in Unix time milliseconds.',
        ),
    ] = None


class ObservingBlockObservingComponent(BaseModel):
    target_token: Annotated[
        str | None,
        Field(
            alias='targetToken',
            description='Unique identifier of the target used in this observing component.\n\nWhen creating or updating an observing group, this must be an\nexisting target, or on the map of the request to be created.',
        ),
    ] = None
    observing_template_token: Annotated[
        str | None,
        Field(
            alias='observingTemplateToken',
            description='Unique identifier of the observing template used in this\nobserving component.\n\nWhen creating or updating an observing group, this must be an\nexisting observing template, or on the map of the request to be\ncreated.',
        ),
    ] = None
    target_label: Annotated[
        int | None,
        Field(
            alias='targetLabel',
            description='Label of the target used in this observing component.\nThis value is only set on the read_observing_block.\n\napi_visibility: read only',
        ),
    ] = None
    observing_template_label: Annotated[
        int | None,
        Field(
            alias='observingTemplateLabel',
            description='Label of the observing template used in this observing component.\nThis value is only set on the read_observing_block.\n\napi_visibility: read only',
        ),
    ] = None
    snr_block_token: Annotated[
        str | None,
        Field(
            alias='snrBlockToken',
            description='Unique identifier of the SNR block used in this observing\ncomponent, if any. Must be set if and only if the observing\ncomponent uses a MegaCam cumulative SNR mode observing template.\n\nIf this is set when creating or updating an observing group,\nthe observing component will be tied to the SNR block with this\ntoken if it already exists, otherwise a new SNR block will be\ncreated using this token.',
        ),
    ] = None


class ObservingGroupDataDitherScheme(Enum):
    none = 'NONE'
    standard = 'STANDARD'
    group = 'GROUP'


class ObservingGroupDataObservingBlock(BaseModel):
    observing_component: Annotated[
        list[ObservingBlockObservingComponent] | None,
        Field(
            alias='observingComponent',
            description='List of observing components that comprise this observing block.',
        ),
    ] = None
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier for the observing block.\n\napi_visibility: operations read only'
        ),
    ] = None
    label: Annotated[
        int | None,
        Field(
            description='Index of the observing block within the program, set by the system\nautomatically. Used for reference in communications with QSO staff.\n\nstorage: transient\napi_visibility: read only'
        ),
    ] = None


class ObservingGroupDataObservingGroupState(Enum):
    not_started = 'NOT_STARTED'
    observed = 'OBSERVED'
    started = 'STARTED'
    validated = 'VALIDATED'


class PhotometryAperture(BaseModel):
    optimal_aperture: Annotated[bool | None, Field(alias='optimalAperture')] = None
    fixed_aperture: Annotated[
        float | None,
        Field(alias='fixedAperture', title='Radius of the aperture in arcsec'),
    ] = None
    ninety_six_percent_flux_aperture: Annotated[
        bool | None, Field(alias='ninetySixPercentFluxAperture')
    ] = None


class ProgramDataComments(BaseModel):
    question: str | None = None
    comment: str | None = None


class ProgramDataContactInfo(BaseModel):
    pi_first_name: Annotated[str | None, Field(alias='piFirstName')] = None
    pi_last_name: Annotated[str | None, Field(alias='piLastName')] = None
    pi_email: Annotated[str | None, Field(alias='piEmail')] = None
    user_token: Annotated[str | None, Field(alias='userToken')] = None


class ProgramDataProgramType(Enum):
    regular = 'REGULAR'
    target_of_opportunity = 'TARGET_OF_OPPORTUNITY'
    calibration = 'CALIBRATION'
    snapshot = 'SNAPSHOT'


class ProgramInfoPiInfo(BaseModel):
    ldap_username: Annotated[str | None, Field(alias='ldapUsername')] = None
    email_address: Annotated[str | None, Field(alias='emailAddress')] = None
    first_name: Annotated[str | None, Field(alias='firstName')] = None
    last_name: Annotated[str | None, Field(alias='lastName')] = None
    legacy_username: Annotated[str | None, Field(alias='legacyUsername')] = None
    user_token: Annotated[str | None, Field(alias='userToken')] = None


class RReadoutMode(Enum):
    normal = 'Normal'
    slow = 'Slow'
    fast = 'Fast'


class SitelleConfigurationDataCalibration(BaseModel):
    calibration_position: Annotated[
        CalibrationCalibrationPosition | None, Field(alias='calibrationPosition')
    ] = CalibrationCalibrationPosition.no_calibration_position
    calibration_mode: Annotated[
        CalibrationCalibrationMode | None, Field(alias='calibrationMode')
    ] = CalibrationCalibrationMode.no_calibration_mode


class SitelleConfigurationDataResolutionMode(Enum):
    no_resolution_mode = 'no_resolution_mode'
    hires = 'hires'
    medres = 'medres'


class SitelleStatusCamera(BaseModel):
    iq: float | None = None
    iq_rms: Annotated[float | None, Field(alias='iqRms')] = None
    pixel_shift_x: Annotated[float | None, Field(alias='pixelShiftX')] = None
    pixel_shift_y: Annotated[float | None, Field(alias='pixelShiftY')] = None
    number_of_stars: Annotated[int | None, Field(alias='numberOfStars')] = None
    me: float | None = None


class SpirouConfigurationDataSkyObservation(Enum):
    none = 'None'
    before = 'Before'
    after = 'After'
    before_and_after = 'BeforeAndAfter'


class SpirouStatusGuiderProcessingResult(BaseModel):
    etime: float | None = None
    isustate: str | None = None
    sbdens_p: Annotated[float | None, Field(alias='sbdensP')] = None
    hole_position_offset_x: Annotated[float | None, Field(alias='holePositionOffsetX')] = (
        None
    )
    hole_position_offset_y: Annotated[float | None, Field(alias='holePositionOffsetY')] = (
        None
    )
    star_to_null_position_offset_x: Annotated[
        float | None, Field(alias='starToNullPositionOffsetX')
    ] = None
    star_to_null_position_offset_y: Annotated[
        float | None, Field(alias='starToNullPositionOffsetY')
    ] = None
    magnitude_estimate: Annotated[float | None, Field(alias='magnitudeEstimate')] = None
    seeing_estimate: Annotated[float | None, Field(alias='seeingEstimate')] = None
    sgisust: Annotated[str | None, Field(title='per  160676372')] = None
    sggdst: str | None = None
    sgfrmrt: float | None = None
    sgetime: float | None = None
    sgnullx: float | None = None
    sgnully: float | None = None
    sgwinx0: float | None = None
    sgwiny0: float | None = None
    sgwinx1: float | None = None
    sgwiny1: float | None = None
    sgoffx0: float | None = None
    sgoffy0: float | None = None
    sgoffx1: float | None = None
    sgoffy1: float | None = None
    sgholex: float | None = None
    sgholey: float | None = None
    sgcholex: float | None = None
    sgcholey: float | None = None
    sgeholex: float | None = None
    sgeholey: float | None = None
    sgcstarx: float | None = None
    sgcstary: float | None = None
    sgestarx: float | None = None
    sgestary: float | None = None
    sgcnoffx: float | None = None
    sgcnoffy: float | None = None
    sgcsee: float | None = None
    sgesee: float | None = None
    sgcmagn: float | None = None
    sgemagn: float | None = None
    sgssee: float | None = None
    trg_type: Annotated[str | None, Field(alias='trgType')] = None


class SpirouStatusPipelineProcessingResult(BaseModel):
    snr10: float | None = None
    snr34: float | None = None
    snr44: float | None = None
    dprtype: str | None = None
    ccfmask: float | None = None
    ccfmacpp: float | None = None
    ccfrv: float | None = None
    ccfcontr: float | None = None
    ccfrvc: float | None = None
    ccffwhm: float | None = None
    ccfmask_str: Annotated[str | None, Field(alias='ccfmaskStr')] = None


class TargetDataMagnitude(BaseModel):
    u: Annotated[float | None, Field(alias='U', title='U-band magnitude')] = None
    b: Annotated[float | None, Field(alias='B', title='B-band magnitude')] = None
    v: Annotated[
        float | None,
        Field(
            alias='V',
            description='Required for targets observed with ESPaDonS.',
            title='V-band magnitude',
        ),
    ] = None
    r: Annotated[float | None, Field(alias='R', title='R-band magnitude')] = None
    i: Annotated[float | None, Field(alias='I', title='I-band magnitude')] = None
    g: Annotated[float | None, Field(alias='G', title='G-band magnitude')] = None
    j: Annotated[float | None, Field(alias='J', title='J-band magnitude')] = None
    h: Annotated[
        float | None,
        Field(
            alias='H',
            description='Required for targets observed with SPIRou.',
            title='H-band magnitude',
        ),
    ] = None
    k: Annotated[float | None, Field(alias='K', title='K-band magnitude')] = None
    uu: Annotated[float | None, Field(title='u-band magnitude')] = None
    gg: Annotated[float | None, Field(title='g-band magnitude')] = None
    rr: Annotated[float | None, Field(title='r-band magnitude')] = None
    ii: Annotated[float | None, Field(title='i-band magnitude')] = None
    zz: Annotated[float | None, Field(title='z-band magnitude')] = None
    ab: Annotated[
        float | None,
        Field(
            alias='AB',
            description='Required for targets observed with MegaCam.',
            title='AB magnitude',
        ),
    ] = None


class TargetListRequestTargetType(Enum):
    all = 'ALL'
    fixed = 'FIXED'
    moving = 'MOVING'


class TargetTimeDataView(Enum):
    requested = 'REQUESTED'
    actual = 'ACTUAL'


class TimeAccountingDataTimeAccountingStatus(Enum):
    not_started = 'NOT_STARTED'
    started = 'STARTED'
    observed = 'OBSERVED'
    validated = 'VALIDATED'


class UpenaProcessingResulth2oMm(BaseModel):
    raw_density: Annotated[float | None, Field(alias='rawDensity')] = None
    at_zenith: Annotated[float | None, Field(alias='atZenith')] = None


class HttpErrors(BaseModel):
    messages: list[str] | None = None


class ObservingObservingGroupDeleteResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None


class ObservingObservingTemplateDeleteResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None


class ObservingPointingOffsetDeleteResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None


class ObservingTargetDeleteResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None


class ObservingTelescopePatternDeleteResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None


class ObservingpersistenceTimeConstraint(BaseModel):
    window: Annotated[
        list[ObservingBlockConditionWindow] | None,
        Field(
            description='Time windows during which the observation can be made.\n\nWindows can not overlap, and will always be stored in temporal order.'
        ),
    ] = None


class PersistenceCatalogIdentifier(BaseModel):
    catalog: Annotated[str | None, Field(description='Catalog to reference.')] = None
    identifier: Annotated[
        str | None,
        Field(
            description='Valid identifier in the catalog.\n\nNote: this ID will contain a catalog name, because spacing matters in catalogs, the full ID for an object is like\nM    4. Catalog is M, id is identifier could be 4, but to reference m4, you need the spaces.\n\nNB: These identity values can not be set in fits headers because they do not have to conform to\nthe length restrictions.'
        ),
    ] = None


class PersistenceExposureTime(BaseModel):
    desired_snr: Annotated[float | None, Field(alias='desiredSnr')] = None
    exposure_time_ms: Annotated[str | None, Field(alias='exposureTimeMs')] = None


class PersistenceFindingChartData(BaseModel):
    comment: str | None = None
    url: str | None = None
    token: str | None = None
    staff_approval: Annotated[
        FindingChartDataApproval | None, Field(alias='staffApproval')
    ] = None
    pi_approval: Annotated[FindingChartDataApproval | None, Field(alias='piApproval')] = (
        None
    )
    target_token: Annotated[str | None, Field(alias='targetToken')] = None


class PersistenceITimeData(BaseModel):
    exposure_time_millis: Annotated[
        str | None,
        Field(
            alias='exposureTimeMillis',
            description='Time spent collecting photons (in milliseconds).',
        ),
    ] = None
    overhead_time_millis: Annotated[
        str | None,
        Field(
            alias='overheadTimeMillis',
            description='All other times required for taking the exposure (in milliseconds).',
        ),
    ] = None


class PersistenceListOfIdentifiers(BaseModel):
    catalog_identifier: Annotated[
        list[PersistenceCatalogIdentifier] | None, Field(alias='catalogIdentifier')
    ] = None


class PersistenceObservingBlockCondition(BaseModel):
    pre_requisite: Annotated[
        list[ObservingBlockConditionRequisite] | None,
        Field(
            alias='preRequisite',
            description='Pre-requisite conditions before each observing block can be started.\nThe index of items in this list corresponds directly to the index of the\nobserving block on the observing group i.e. this list is one-to-one with\nread_observing_block.',
        ),
    ] = None
    window: Annotated[
        list[ObservingBlockConditionWindow] | None,
        Field(
            description='Time windows during which the observing block can be observed.\n\nWindows can not overlap, and will always be stored in temporal order.'
        ),
    ] = None


class PersistenceObservingGroupPriority(Enum):
    unknown_og_priority = 'UNKNOWN_OG_PRIORITY'
    high = 'HIGH'
    medium = 'MEDIUM'
    low = 'LOW'
    inactive = 'INACTIVE'


class PersistenceRollupValue(BaseModel):
    requested: str | None = None
    started: str | None = None
    observed: str | None = None
    validated: str | None = None


class PersistenceSingleObservingGroup(BaseModel):
    observing_block: Annotated[
        ObservingGroupDataObservingBlock | None, Field(alias='observingBlock')
    ] = None


class PersistenceState(Enum):
    unobserved = 'UNOBSERVED'
    observed = 'OBSERVED'
    processed = 'PROCESSED'
    graded = 'GRADED'
    validated = 'VALIDATED'
    rejected = 'REJECTED'


class PersistenceStokesParameter(Enum):
    q = 'Q'
    u = 'U'
    v = 'V'
    w = 'W'
    i = 'I'


class PersistenceSubTotalsData(BaseModel):
    etime: PersistenceRollupValue | None = None
    overheadtime: PersistenceRollupValue | None = None
    exposure_count: Annotated[
        PersistenceRollupValue | None, Field(alias='exposureCount')
    ] = None
    child_count: Annotated[PersistenceRollupValue | None, Field(alias='childCount')] = (
        None
    )
    etime_configured: Annotated[
        PersistenceRollupValue | None, Field(alias='etimeConfigured')
    ] = None
    overhead_time_configured: Annotated[
        PersistenceRollupValue | None, Field(alias='overheadTimeConfigured')
    ] = None
    completeness: Annotated[
        float | None, Field(description='Percentage completed for the entity.')
    ] = None


class PersistenceTargetIdentifiers(BaseModel):
    catalog_identifier: Annotated[
        dict[str, PersistenceListOfIdentifiers] | None,
        Field(
            alias='catalogIdentifier',
            description='key: catalog name, catalog_identifier.key === catalog_identifier.get(key).catalog\nvalue: catalog identifier.',
            title='All catalogs resolved by simbad for this target',
        ),
    ] = None
    two_mass: Annotated[PersistenceCatalogIdentifier | None, Field(alias='twoMass')] = (
        None
    )
    gaia1: PersistenceCatalogIdentifier | None = None
    gaia2: PersistenceCatalogIdentifier | None = None
    resolved_catalog_identifier: Annotated[
        PersistenceCatalogIdentifier | None, Field(alias='resolvedCatalogIdentifier')
    ] = None


class PersistenceTargetTimeData(BaseModel):
    requested_integration_time: Annotated[
        PersistenceITimeData | None, Field(alias='requestedIntegrationTime')
    ] = None
    actual_integration_time: Annotated[
        PersistenceITimeData | None, Field(alias='actualIntegrationTime')
    ] = None
    view: TargetTimeDataView | None = TargetTimeDataView.requested
    exposure_count: Annotated[
        int | None,
        Field(
            alias='exposureCount',
            description='The total number of exposures represented by the values here.\n\nThis value is the same for both views.',
        ),
    ] = None
    child_count: Annotated[
        int | None,
        Field(
            alias='childCount',
            description='The total number of child entities represented by the values here.\n\nIf this is a program, these are observing groups.\nIf this is an observing group, these are observing blocks.\nIf this is an observing block, these are exposures.\n\nUseful for e.g. seeing the number of iterations configuredor completed on an Observing Group.\nThis value is the same for both views.',
        ),
    ] = None


class PersistenceTimeAccountingData(BaseModel):
    configured_time: Annotated[
        PersistenceTargetTimeData | None, Field(alias='configuredTime')
    ] = None
    charged_time: Annotated[
        PersistenceTargetTimeData | None, Field(alias='chargedTime')
    ] = None
    validated_time_on_sky: Annotated[
        PersistenceTargetTimeData | None, Field(alias='validatedTimeOnSky')
    ] = None
    time_on_sky: Annotated[PersistenceTargetTimeData | None, Field(alias='timeOnSky')] = (
        None
    )
    time_accounting_status: Annotated[
        TimeAccountingDataTimeAccountingStatus | None,
        Field(alias='timeAccountingStatus'),
    ] = TimeAccountingDataTimeAccountingStatus.not_started
    completion_ratio: Annotated[
        float | None,
        Field(
            alias='completionRatio',
            description='Entity completion ratio, representing how much of the time configured has been charged.\n\nEqual to total charged time (as requested) divided by total configured time. For programs, if the total configured time is greater than the time allocated to the program, we divide by the time allocated instead.\nNote that if a program has INACTIVE observing groups that already have charged time, this could result in an inflated value here.',
            le=1.0,
        ),
    ] = None


class ProtobufAny(BaseModel):
    type_url: Annotated[str | None, Field(alias='typeUrl')] = None
    value: Annotated[
        Base64Str | None,
        Field(
            pattern='^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'
        ),
    ] = None


class RpcStatus(BaseModel):
    code: int | None = None
    message: str | None = None
    details: list[ProtobufAny] | None = None


class TypesBigInteger(BaseModel):
    value: str | None = None


class TypesDoubleMinMax(BaseModel):
    min: float | None = None
    max: float | None = None


class TypesDurationUnit(Enum):
    days = 'DAYS'
    hours = 'HOURS'
    minutes = 'MINUTES'
    seconds = 'SECONDS'


class TypesExposureType(Enum):
    object = 'OBJECT'
    target = 'TARGET'
    sky = 'SKY'
    dark = 'DARK'
    flat = 'FLAT'
    snap = 'SNAP'
    bias = 'BIAS'
    focus = 'FOCUS'
    align = 'ALIGN'
    comparison = 'COMPARISON'
    acquire = 'ACQUIRE'
    fabry_perot = 'FABRY_PEROT'
    twilight_flats = 'TWILIGHT_FLATS'
    photometry = 'PHOTOMETRY'
    sfocus = 'SFOCUS'


class TypesInstrumentType(Enum):
    unknown = 'UNKNOWN'
    cfh12_k = 'CFH12K'
    megacam = 'MEGACAM'
    wircam = 'WIRCAM'
    espadons = 'ESPADONS'
    sitelle = 'SITELLE'
    spirou = 'SPIROU'
    wenaokeao = 'WENAOKEAO'


class TypesOffsetCoordinate(BaseModel):
    ra_offset: Annotated[
        float | None,
        Field(
            alias='raOffset',
            description='Offset in the Right Ascension axis in arcsec of degrees.',
            ge=-1296000.0,
            le=1296000.0,
            title='Right Ascension Offset',
        ),
    ] = None
    dec_offset: Annotated[
        float | None,
        Field(
            alias='decOffset',
            description='Offset in the Declination axis in arcsec of degrees.',
            ge=-324000.0,
            le=324000.0,
            title='Declination Offset',
        ),
    ] = None
    exposure_number: Annotated[
        float | None,
        Field(
            alias='exposureNumber',
            description='Exposure number',
            le=99.0,
            title='Exposure number',
        ),
    ] = None


class TypesSkyCoordinate(BaseModel):
    ra: Annotated[
        float | None,
        Field(
            description='Right Ascension in degrees.', le=360.0, title='Right Ascension'
        ),
    ] = None
    dec: Annotated[
        float | None,
        Field(
            description='Declination in degrees.',
            ge=-90.0,
            le=90.0,
            title='Declination',
        ),
    ] = None


class ConfigNodding(BaseModel):
    start_sequence: Annotated[
        TypesExposureType | None, Field(alias='startSequence')
    ] = TypesExposureType.object
    target_db: Annotated[float | None, Field(alias='targetDb')] = None


class EspadonsStatusUpenaProcessingResult(BaseModel):
    iq: float | None = None
    h2o_column_density_from_telluric_lines: Annotated[
        float | None, Field(alias='h2oColumnDensityFromTelluricLines')
    ] = None
    radial_velocity_corrections: Annotated[
        float | None, Field(alias='radialVelocityCorrections')
    ] = None
    snr_per_ccd_bin: Annotated[float | None, Field(alias='snrPerCcdBin')] = None
    snr_per_spec_bin: Annotated[float | None, Field(alias='snrPerSpecBin')] = None
    actual_wavelength: Annotated[float | None, Field(alias='actualWavelength')] = None
    snr_per_ccd_bin_polar: Annotated[float | None, Field(alias='snrPerCcdBinPolar')] = (
        None
    )
    snr_per_spec_bin_polar: Annotated[float | None, Field(alias='snrPerSpecBinPolar')] = (
        None
    )
    h2o_mm_data: Annotated[UpenaProcessingResulth2oMm | None, Field(alias='h2oMmData')] = (
        None
    )


class ExposureDataEspadonsStatus(BaseModel):
    instr_mode: Annotated[str | None, Field(alias='instrMode')] = None
    actual_wavelength: Annotated[float | None, Field(alias='actualWavelength')] = None
    snr_exp_meter: Annotated[float | None, Field(alias='snrExpMeter')] = None
    snr_wave_meas_int: Annotated[float | None, Field(alias='snrWaveMeasInt')] = None
    snr_wave_meas_pol: Annotated[float | None, Field(alias='snrWaveMeasPol')] = None
    snr_meas_int_per_ccd_bin: Annotated[
        float | None, Field(alias='snrMeasIntPerCcdBin')
    ] = None
    snr_meas_int_per_spec_bin: Annotated[
        float | None, Field(alias='snrMeasIntPerSpecBin')
    ] = None
    snr_meas_polar_ccd_bin: Annotated[float | None, Field(alias='snrMeasPolarCcdBin')] = (
        None
    )
    snr_meas_polar_spec_bin: Annotated[float | None, Field(alias='snrMeasPolarSpecBin')] = (
        None
    )
    trg_type: Annotated[str | None, Field(alias='trgType')] = None
    guider_seeing: Annotated[float | None, Field(alias='guiderSeeing')] = None
    guider_seeing_processing_results: Annotated[
        EspadonsStatusGuiderSeeingProcessingResult | None,
        Field(alias='guiderSeeingProcessingResults'),
    ] = None
    exposure_meter_processing_results: Annotated[
        ExposureDataEspadonsStatusExposureMeterProcessingResult | None,
        Field(alias='exposureMeterProcessingResults'),
    ] = None
    upena_processing_results: Annotated[
        EspadonsStatusUpenaProcessingResult | None,
        Field(alias='upenaProcessingResults'),
    ] = None
    observation_type: Annotated[str | None, Field(alias='observationType')] = None


class ExposureDataMegacamStatus(BaseModel):
    iq: float | None = None
    skybg: float | None = None
    elixir_eval: Annotated[int | None, Field(alias='elixirEval')] = None
    elixir_seval: Annotated[str | None, Field(alias='elixirSeval')] = None
    snr: float | None = None
    atmospheric_transmission: Annotated[
        float | None, Field(alias='atmosphericTransmission')
    ] = None
    elixir_zeropoint: Annotated[float | None, Field(alias='elixirZeropoint')] = None
    actual_filter: Annotated[str | None, Field(alias='actualFilter')] = None
    elixir_processing_result: Annotated[
        MegacamStatusElixirProcessingResult | None,
        Field(alias='elixirProcessingResult'),
    ] = None


class ExposureDataSitelleStatus(BaseModel):
    camera_a: Annotated[SitelleStatusCamera | None, Field(alias='cameraA')] = None
    camera_b: Annotated[SitelleStatusCamera | None, Field(alias='cameraB')] = None
    relative_extinction: Annotated[float | None, Field(alias='relativeExtinction')] = (
        None
    )
    relative_extinction_rms: Annotated[
        float | None, Field(alias='relativeExtinctionRms')
    ] = None
    actual_filter: Annotated[str | None, Field(alias='actualFilter')] = None


class ExposureDataSpirouStatus(BaseModel):
    acqtime: float | None = None
    acqtime1: str | None = None
    asic_num: Annotated[str | None, Field(alias='asicNum')] = None
    sca_id: Annotated[str | None, Field(alias='scaId')] = None
    muxtype: int | None = None
    noutputs: int | None = None
    nadcs: int | None = None
    pddector: int | None = None
    clkoff: int | None = None
    warmtst: int | None = None
    clocking: int | None = None
    glbreset: int | None = None
    frmode: int | None = None
    camlink: int | None = None
    expmode: int | None = None
    nresets: int | None = None
    frmtime: float | None = None
    exptime: float | None = None
    acqtype: int | None = None
    datamode: int | None = None
    datlevel: int | None = None
    asicgain: int | None = None
    nomgain: int | None = None
    ampreset: int | None = None
    ktcremov: int | None = None
    srccur: int | None = None
    ampinput: int | None = None
    v4v3v2v1: str | None = None
    units: str | None = None
    tstation: str | None = None
    hxrgver: str | None = None
    mclk: float | None = None
    inttime: float | None = None
    frameno: int | None = None
    sb_adc_s: Annotated[str | None, Field(alias='sbAdcS')] = None
    sbadc1_p: Annotated[float | None, Field(alias='sbadc1P')] = None
    sbadc2_p: Annotated[float | None, Field(alias='sbadc2P')] = None
    sbcali_p: Annotated[str | None, Field(alias='sbcaliP')] = None
    sbdens_p: Annotated[float | None, Field(alias='sbdensP')] = None
    sbrhb1_p: Annotated[str | None, Field(alias='sbrhb1P')] = None
    sbrhb2_p: Annotated[str | None, Field(alias='sbrhb2P')] = None
    sbetem_p: Annotated[str | None, Field(alias='sbetemP')] = None
    sb_inj_t: Annotated[float | None, Field(alias='sbInjT')] = None
    sb_pol_t: Annotated[float | None, Field(alias='sbPolT')] = None
    sb_cs1_t: Annotated[float | None, Field(alias='sbCs1T')] = None
    sb_cs2_t: Annotated[float | None, Field(alias='sbCs2T')] = None
    sb_cb1_t: Annotated[float | None, Field(alias='sbCb1T')] = None
    sb_cb2_t: Annotated[float | None, Field(alias='sbCb2T')] = None
    sbiavl1s: str | None = None
    sbiavl2s: str | None = None
    sbetel_s: Annotated[str | None, Field(alias='sbetelS')] = None
    sb_csc_s: Annotated[str | None, Field(alias='sbCscS')] = None
    sbcref_p: Annotated[str | None, Field(alias='sbcrefP')] = None
    sbccas_p: Annotated[str | None, Field(alias='sbccasP')] = None
    sbcden_p: Annotated[float | None, Field(alias='sbcdenP')] = None
    sbagit_s: Annotated[str | None, Field(alias='sbagitS')] = None
    sbcmir_p: Annotated[str | None, Field(alias='sbcmirP')] = None
    sbclhc1s: str | None = None
    sbclhc1w: str | None = None
    sbclhc1c: float | None = None
    sbclhc2s: str | None = None
    sbclhc2w: str | None = None
    sbclhc2c: float | None = None
    sbclwl_s: Annotated[str | None, Field(alias='sbclwlS')] = None
    sbclwl_c: Annotated[float | None, Field(alias='sbclwlC')] = None
    sbwlsh_s: Annotated[str | None, Field(alias='sbwlshS')] = None
    sbctec_s: Annotated[str | None, Field(alias='sbctecS')] = None
    sbctecct: float | None = None
    sbctecht: float | None = None
    sbccprit: float | None = None
    sbcccu_t: Annotated[float | None, Field(alias='sbcccuT')] = None
    sbccprot: float | None = None
    sbcfbi_t: Annotated[float | None, Field(alias='sbcfbiT')] = None
    sbcwls_t: Annotated[float | None, Field(alias='sbcwlsT')] = None
    sbclsuat: float | None = None
    sbcfpi_t: Annotated[float | None, Field(alias='sbcfpiT')] = None
    sbcfpe_t: Annotated[float | None, Field(alias='sbcfpeT')] = None
    sbcfpb_p: Annotated[float | None, Field(alias='sbcfpbP')] = None
    sbvga_cp: Annotated[float | None, Field(alias='sbvgaCp')] = None
    sbvga_ip: Annotated[float | None, Field(alias='sbvgaIp')] = None
    sbvgb_cp: Annotated[float | None, Field(alias='sbvgbCp')] = None
    sbvgb_ip: Annotated[float | None, Field(alias='sbvgbIp')] = None
    sbmk00_t: Annotated[float | None, Field(alias='sbmk00T')] = None
    sbmk01_t: Annotated[float | None, Field(alias='sbmk01T')] = None
    sbmk02_t: Annotated[float | None, Field(alias='sbmk02T')] = None
    sbmk03_t: Annotated[float | None, Field(alias='sbmk03T')] = None
    sbmk04_t: Annotated[float | None, Field(alias='sbmk04T')] = None
    sbmk05_t: Annotated[float | None, Field(alias='sbmk05T')] = None
    sbmk06_t: Annotated[float | None, Field(alias='sbmk06T')] = None
    sbmk07_t: Annotated[float | None, Field(alias='sbmk07T')] = None
    sbls000t: float | None = None
    sbls001t: float | None = None
    sbls002t: float | None = None
    sbls003t: float | None = None
    sbls004t: float | None = None
    sbls005t: float | None = None
    sbls006t: float | None = None
    sbls007t: float | None = None
    sbls008t: float | None = None
    sbls009t: float | None = None
    sbls010t: float | None = None
    sbls011t: float | None = None
    sbls100t: float | None = None
    sbls101t: float | None = None
    sbls102t: float | None = None
    sbls103t: float | None = None
    sbls104t: float | None = None
    sbls105t: float | None = None
    sbls106t: float | None = None
    sbls107t: float | None = None
    sbls108t: float | None = None
    sbls109t: float | None = None
    sbls110t: float | None = None
    sbls111t: float | None = None
    sbl00i_t: Annotated[float | None, Field(alias='sbl00iT')] = None
    sbl00h_v: Annotated[float | None, Field(alias='sbl00hV')] = None
    sbl01i_t: Annotated[float | None, Field(alias='sbl01iT')] = None
    sbl01h_v: Annotated[float | None, Field(alias='sbl01hV')] = None
    sbl02i_t: Annotated[float | None, Field(alias='sbl02iT')] = None
    sbl02h_v: Annotated[float | None, Field(alias='sbl02hV')] = None
    sbl03i_t: Annotated[float | None, Field(alias='sbl03iT')] = None
    sbl03h_v: Annotated[float | None, Field(alias='sbl03hV')] = None
    sbl04i_t: Annotated[float | None, Field(alias='sbl04iT')] = None
    sbl04h_v: Annotated[float | None, Field(alias='sbl04hV')] = None
    sbl05i_t: Annotated[float | None, Field(alias='sbl05iT')] = None
    sbl05h_v: Annotated[float | None, Field(alias='sbl05hV')] = None
    sbl06i_t: Annotated[float | None, Field(alias='sbl06iT')] = None
    sbl06h_v: Annotated[float | None, Field(alias='sbl06hV')] = None
    sbl07i_t: Annotated[float | None, Field(alias='sbl07iT')] = None
    sbl07h_v: Annotated[float | None, Field(alias='sbl07hV')] = None
    sbl08i_t: Annotated[float | None, Field(alias='sbl08iT')] = None
    sbl08h_v: Annotated[float | None, Field(alias='sbl08hV')] = None
    sbl09i_t: Annotated[float | None, Field(alias='sbl09iT')] = None
    sbl09h_v: Annotated[float | None, Field(alias='sbl09hV')] = None
    sbl10i_t: Annotated[float | None, Field(alias='sbl10iT')] = None
    sbl10h_v: Annotated[float | None, Field(alias='sbl10hV')] = None
    sbl11i_t: Annotated[float | None, Field(alias='sbl11iT')] = None
    sbl11h_v: Annotated[float | None, Field(alias='sbl11hV')] = None
    sbl12i_t: Annotated[float | None, Field(alias='sbl12iT')] = None
    sbl12h_v: Annotated[float | None, Field(alias='sbl12hV')] = None
    sbl13i_t: Annotated[float | None, Field(alias='sbl13iT')] = None
    sbl13h_v: Annotated[float | None, Field(alias='sbl13hV')] = None
    seadc1_p: Annotated[float | None, Field(alias='seadc1P')] = None
    seadc2_p: Annotated[float | None, Field(alias='seadc2P')] = None
    sedens_p: int | None = None
    sedens_p_float: float | None = None
    se_inj_t: Annotated[float | None, Field(alias='seInjT')] = None
    se_pol_t: Annotated[float | None, Field(alias='sePolT')] = None
    se_cs1_t: Annotated[float | None, Field(alias='seCs1T')] = None
    se_cs2_t: Annotated[float | None, Field(alias='seCs2T')] = None
    se_cb1_t: Annotated[float | None, Field(alias='seCb1T')] = None
    se_cb2_t: Annotated[float | None, Field(alias='seCb2T')] = None
    sectecct: float | None = None
    sectecht: float | None = None
    seccprit: float | None = None
    secccu_t: Annotated[float | None, Field(alias='secccuT')] = None
    seccprot: float | None = None
    secfbi_t: Annotated[float | None, Field(alias='secfbiT')] = None
    secwls_t: Annotated[float | None, Field(alias='secwlsT')] = None
    seclhc1c: float | None = None
    seclhc2c: float | None = None
    seclwl_c: Annotated[float | None, Field(alias='seclwlC')] = None
    seclsuat: float | None = None
    secfpi_t: Annotated[float | None, Field(alias='secfpiT')] = None
    secfpe_t: Annotated[float | None, Field(alias='secfpeT')] = None
    secfpb_p: Annotated[float | None, Field(alias='secfpbP')] = None
    sevga_cp: Annotated[float | None, Field(alias='sevgaCp')] = None
    sevga_ip: Annotated[float | None, Field(alias='sevgaIp')] = None
    sevgb_cp: Annotated[float | None, Field(alias='sevgbCp')] = None
    sevgb_ip: Annotated[float | None, Field(alias='sevgbIp')] = None
    semk00_t: Annotated[float | None, Field(alias='semk00T')] = None
    semk01_t: Annotated[float | None, Field(alias='semk01T')] = None
    semk02_t: Annotated[float | None, Field(alias='semk02T')] = None
    semk03_t: Annotated[float | None, Field(alias='semk03T')] = None
    semk04_t: Annotated[float | None, Field(alias='semk04T')] = None
    semk05_t: Annotated[float | None, Field(alias='semk05T')] = None
    semk06_t: Annotated[float | None, Field(alias='semk06T')] = None
    semk07_t: Annotated[float | None, Field(alias='semk07T')] = None
    sels000t: float | None = None
    sels001t: float | None = None
    sels002t: float | None = None
    sels003t: float | None = None
    sels004t: float | None = None
    sels005t: float | None = None
    sels006t: float | None = None
    sels007t: float | None = None
    sels008t: float | None = None
    sels009t: float | None = None
    sels010t: float | None = None
    sels011t: float | None = None
    sels100t: float | None = None
    sels101t: float | None = None
    sels102t: float | None = None
    sels103t: float | None = None
    sels104t: float | None = None
    sels105t: float | None = None
    sels106t: float | None = None
    sels107t: float | None = None
    sels108t: float | None = None
    sels109t: float | None = None
    sels110t: float | None = None
    sels111t: float | None = None
    sel00i_t: Annotated[float | None, Field(alias='sel00iT')] = None
    sel00h_v: Annotated[float | None, Field(alias='sel00hV')] = None
    sel01i_t: Annotated[float | None, Field(alias='sel01iT')] = None
    sel01h_v: Annotated[float | None, Field(alias='sel01hV')] = None
    sel02i_t: Annotated[float | None, Field(alias='sel02iT')] = None
    sel02h_v: Annotated[float | None, Field(alias='sel02hV')] = None
    sel03i_t: Annotated[float | None, Field(alias='sel03iT')] = None
    sel03h_v: Annotated[float | None, Field(alias='sel03hV')] = None
    sel04i_t: Annotated[float | None, Field(alias='sel04iT')] = None
    sel04h_v: Annotated[float | None, Field(alias='sel04hV')] = None
    sel05i_t: Annotated[float | None, Field(alias='sel05iT')] = None
    sel05h_v: Annotated[float | None, Field(alias='sel05hV')] = None
    sel06i_t: Annotated[float | None, Field(alias='sel06iT')] = None
    sel06h_v: Annotated[float | None, Field(alias='sel06hV')] = None
    sel07i_t: Annotated[float | None, Field(alias='sel07iT')] = None
    sel07h_v: Annotated[float | None, Field(alias='sel07hV')] = None
    sel08i_t: Annotated[float | None, Field(alias='sel08iT')] = None
    sel08h_v: Annotated[float | None, Field(alias='sel08hV')] = None
    sel09i_t: Annotated[float | None, Field(alias='sel09iT')] = None
    sel09h_v: Annotated[float | None, Field(alias='sel09hV')] = None
    sel10i_t: Annotated[float | None, Field(alias='sel10iT')] = None
    sel10h_v: Annotated[float | None, Field(alias='sel10hV')] = None
    sel11i_t: Annotated[float | None, Field(alias='sel11iT')] = None
    sel11h_v: Annotated[float | None, Field(alias='sel11hV')] = None
    sel12i_t: Annotated[float | None, Field(alias='sel12iT')] = None
    sel12h_v: Annotated[float | None, Field(alias='sel12hV')] = None
    sel13i_t: Annotated[float | None, Field(alias='sel13iT')] = None
    sel13h_v: Annotated[float | None, Field(alias='sel13hV')] = None
    guider_processing: Annotated[
        SpirouStatusGuiderProcessingResult | None, Field(alias='guiderProcessing')
    ] = None
    exposure_meter_processing: Annotated[
        ExposureDataSpirouStatusExposureMeterProcessingResult | None,
        Field(alias='exposureMeterProcessing'),
    ] = None
    pipeline_processing: Annotated[
        SpirouStatusPipelineProcessingResult | None, Field(alias='pipelineProcessing')
    ] = None


class InstrumentConfigurationDataEspadonsConfigurationData(BaseModel):
    observing_mode: Annotated[
        InstrumentConfigurationDataEspadonsConfigurationDataOObservingMode | None,
        Field(alias='observingMode'),
    ] = InstrumentConfigurationDataEspadonsConfigurationDataOObservingMode.polarimetry
    readout_mode: Annotated[RReadoutMode | None, Field(alias='readoutMode')] = (
        RReadoutMode.normal
    )
    stokes_parameter: Annotated[
        PersistenceStokesParameter | None, Field(alias='stokesParameter')
    ] = PersistenceStokesParameter.q
    number_of_sequences: Annotated[int | None, Field(alias='numberOfSequences')] = None
    number_of_exposures: Annotated[int | None, Field(alias='numberOfExposures')] = None
    needs_snr: bool | None = None
    snr_wave: Annotated[float | None, Field(alias='snrWave')] = None
    snr: float | None = None


class InstrumentConfigurationDataMegacamConfigurationDataPhotometry(BaseModel):
    aperture: PhotometryAperture | None = None
    psf: bool | None = None


class InstrumentConfigurationDataSitelleConfigurationData(BaseModel):
    filter: InstrumentConfigurationDataSitelleConfigurationDataFilter | None = (
        InstrumentConfigurationDataSitelleConfigurationDataFilter.unknown
    )
    binning: InstrumentConfigurationDataSitelleConfigurationDataBinning | None = (
        InstrumentConfigurationDataSitelleConfigurationDataBinning.one_one
    )
    resolution: int | None = None
    snrwavelength: Annotated[
        float | None,
        Field(title='This should be on target too , sitell, espedons, spirou'),
    ] = None
    calibration: SitelleConfigurationDataCalibration | None = None
    resolution_mode: Annotated[
        SitelleConfigurationDataResolutionMode | None, Field(alias='resolutionMode')
    ] = SitelleConfigurationDataResolutionMode.no_resolution_mode
    needs_precision: Annotated[bool | None, Field(alias='needsPrecision')] = None
    needs_flux_calibration: Annotated[bool | None, Field(alias='needsFluxCalibration')] = (
        None
    )
    needs_target_calibration: Annotated[
        bool | None, Field(alias='needsTargetCalibration')
    ] = None


class InstrumentConfigurationDataSpirouConfigurationData(BaseModel):
    template_name: Annotated[
        str | None, Field(alias='templateName', title='Deprecated fields')
    ] = None
    observing_mode: Annotated[
        InstrumentConfigurationDataSpirouConfigurationDataOObservingMode | None,
        Field(alias='observingMode'),
    ] = InstrumentConfigurationDataSpirouConfigurationDataOObservingMode.polarimetry
    stokes_parameter: Annotated[
        PersistenceStokesParameter | None, Field(alias='stokesParameter')
    ] = PersistenceStokesParameter.q
    mode: MMode | None = MMode.dark
    sky_observation: Annotated[
        SpirouConfigurationDataSkyObservation | None, Field(alias='skyObservation')
    ] = SpirouConfigurationDataSkyObservation.none
    number_of_sequences: Annotated[
        int | None,
        Field(
            alias='numberOfSequences',
            title='Each sequence is 1 exposure for Star mode and 4 exposures for ObservingMode',
        ),
    ] = None
    use_snr: Annotated[
        bool | None,
        Field(alias='useSnr', title='when true - use SNR for stoping exposures'),
    ] = None
    sky_etime_millis: Annotated[
        str | None,
        Field(
            alias='skyEtimeMillis',
            title='Used to override the etime for the sky_observation',
        ),
    ] = None


class InstrumentConfigurationDataWircamConfigurationData(BaseModel):
    filter: InstrumentConfigurationDataWircamConfigurationDataFilter | None = (
        InstrumentConfigurationDataWircamConfigurationDataFilter.unknown
    )
    is_microdithering: Annotated[bool | None, Field(alias='isMicrodithering')] = None
    exposures_per_dp_position: Annotated[
        int | None, Field(alias='exposuresPerDpPosition', title='Must always be > 0')
    ] = None
    accurate_pointing: Annotated[bool | None, Field(alias='accuratePointing')] = None
    defocus: float | None = None
    is_staring: Annotated[bool | None, Field(alias='isStaring')] = None


class MovingTargetEphemeris(BaseModel):
    mjd: Annotated[
        float | None,
        Field(
            description='Modified Julian date when the target is at this coordinate.'
        ),
    ] = None
    coordinate: TypesSkyCoordinate | None = None
    computed_coordinate: Annotated[
        TypesSkyCoordinate | None, Field(alias='computedCoordinate')
    ] = None


class TargetDataFixedTarget(BaseModel):
    coordinate: TypesSkyCoordinate | None = None
    proper_motion: Annotated[
        FixedTargetProperMotion | None, Field(alias='properMotion')
    ] = None
    computed_coordinate: Annotated[
        TypesSkyCoordinate | None, Field(alias='computedCoordinate')
    ] = None
    estimated_radial_velocity_kmps: Annotated[
        float | None,
        Field(
            alias='estimatedRadialVelocityKmps',
            description='Expected radial velocity of the target in kilometers/second.\n\nUsed for targets observed with SPIRou.',
        ),
    ] = None


class TargetDataLinkedTargetIdentifiers(BaseModel):
    pi_confirmed_identifiers: Annotated[
        PersistenceTargetIdentifiers | None, Field(alias='piConfirmedIdentifiers')
    ] = None
    custom_target: Annotated[
        bool | None,
        Field(
            alias='customTarget',
            description='Used to indicate this is a target without known identifiers.',
        ),
    ] = None


class TargetDataMovingTarget(BaseModel):
    ephemeris_point: Annotated[
        list[MovingTargetEphemeris] | None,
        Field(
            alias='ephemerisPoint',
            description="The ephemerides that define the path of motion for the target.\n\nMust be provided using topocentric astrometric coordinates.\nDo not provide apparent coordinates.\nCFHT strongly recommends the use of JPL Horizons System for\ngenerating the proper coordinates. CFHT's observatory code is T14.\n\nAt least five distinct positions must be provided that span the\ndesired observing period. The first position should be well in\nadvance of the observation. The positions do not need to be\nuniformly sampled throughout the desired observing period.\n\nThe points will be interpolated to determine the position of the\ntarget at the time of observation, at which point there must be\nat least one ephemeris point defined in the past, and at least\nfour defined in the future.",
        ),
    ] = None


class TelescopePatternDataConfig(BaseModel):
    name: str | None = None
    description: str | None = None
    charge_model: Annotated[
        str | None,
        Field(alias='chargeModel', title='Used for calculating cost for this pattern'),
    ] = None
    dithering: ConfigDithering | None = None
    nodding: ConfigNodding | None = None
    scale: float | None = None
    sybase_pat_id: Annotated[TypesBigInteger | None, Field(alias='sybasePatId')] = None
    is_system: Annotated[bool | None, Field(alias='isSystem')] = None


class TelescopePatternDataOffset(BaseModel):
    exposure_number: Annotated[
        int | None,
        Field(
            alias='exposureNumber',
            description='TODO: deprecate, no need to have duplicate information here.',
        ),
    ] = None
    offset: TypesOffsetCoordinate | None = None
    type: TypesExposureType | None = TypesExposureType.object


class ObservingRollupFields(BaseModel):
    i_time: Annotated[PersistenceRollupValue | None, Field(alias='iTime')] = None
    i_time_configured: Annotated[
        PersistenceRollupValue | None, Field(alias='iTimeConfigured')
    ] = None
    sub_totals: Annotated[PersistenceSubTotalsData | None, Field(alias='subTotals')] = (
        None
    )


class PersistenceAllocationData(BaseModel):
    run_id: Annotated[str | None, Field(alias='runId')] = None
    time_allocated_millis: Annotated[str | None, Field(alias='timeAllocatedMillis')] = (
        None
    )
    tac_rank: Annotated[int | None, Field(alias='tacRank')] = None
    tac_grade: Annotated[str | None, Field(alias='tacGrade')] = None
    instrument: TypesInstrumentType | None = TypesInstrumentType.unknown
    agency: AllocationDataAgency | None = None
    cfht_rank: Annotated[int | None, Field(alias='cfhtRank')] = None


class PersistenceConstraint(BaseModel):
    image_quality: Annotated[TypesDoubleMinMax | None, Field(alias='imageQuality')] = (
        None
    )
    sky_background_max: Annotated[float | None, Field(alias='skyBackgroundMax')] = None
    airmass_max: Annotated[float | None, Field(alias='airmassMax')] = None
    extinction_max: Annotated[float | None, Field(alias='extinctionMax')] = None
    moon_distance_arc_length_min: Annotated[
        float | None, Field(alias='moonDistanceArcLengthMin')
    ] = None
    photometric: bool | None = None
    name: str | None = None
    sybase_cons_id: Annotated[TypesBigInteger | None, Field(alias='sybaseConsId')] = (
        None
    )
    h2o_vapor_max: Annotated[float | None, Field(alias='h2oVaporMax')] = None
    read_sky_background_name: Annotated[
        str | None, Field(alias='readSkyBackgroundName')
    ] = None
    sky_background_name: Annotated[str | None, Field(alias='skyBackgroundName')] = None


class PersistencePointingOffsetData(BaseModel):
    token: str | None = None
    name: str | None = None
    offset: TypesOffsetCoordinate | None = None
    label: int | None = None
    version: int | None = None
    user_token: Annotated[
        str | None,
        Field(
            alias='userToken',
            title='this is the PI of the program that this entity will be recorded for\nif null should be derived using the program_data.contact_info.user_token\nif null, then a system ?? gross',
        ),
    ] = None
    instrument: TypesInstrumentType | None = TypesInstrumentType.unknown
    is_system: Annotated[bool | None, Field(alias='isSystem')] = None


class PersistenceProgramData(BaseModel):
    title: str | None = None
    abstract: str | None = None
    contact_info: Annotated[ProgramDataContactInfo | None, Field(alias='contactInfo')] = (
        None
    )
    comment: list[ProgramDataComments] | None = None
    sybase_pi_user_id: Annotated[str | None, Field(alias='sybasePiUserId')] = None
    sub_totals: Annotated[PersistenceSubTotalsData | None, Field(alias='subTotals')] = (
        None
    )
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier for the program. Used interchangeably with "runid".'
        ),
    ] = None
    time_allocation: Annotated[
        list[PersistenceAllocationData] | None, Field(alias='timeAllocation')
    ] = None
    release_date_millis: Annotated[str | None, Field(alias='releaseDateMillis')] = None
    metadata_release_date_millis: Annotated[
        str | None, Field(alias='metadataReleaseDateMillis')
    ] = None
    comment_field: Annotated[str | None, Field(alias='commentField')] = None
    program_type: Annotated[
        ProgramDataProgramType | None, Field(alias='programType')
    ] = ProgramDataProgramType.regular
    distribution_hash: Annotated[str | None, Field(alias='distributionHash')] = None
    time_accounting: Annotated[
        PersistenceTimeAccountingData | None, Field(alias='timeAccounting')
    ] = None
    operations_comment_field: Annotated[
        str | None, Field(alias='operationsCommentField')
    ] = None
    last_data_acquisition_notification_date_millis: Annotated[
        str | None, Field(alias='lastDataAcquisitionNotificationDateMillis')
    ] = None


class PersistenceTargetData(BaseModel):
    token: Annotated[
        str | None,
        Field(
            description='Unique identifier for the target.\n\nWhen creating a new target, this will be inferred from the request data\nif left blank here.\n\nMust begin with the program token followed by a dash, e.g.\n20AE01-0123456789'
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(
            description='Name for the target entered by PI, or primary name as resolved by CDS.\n\nWill become OBJECT in the FITS header.\n\nRequired.\nLength limited to 39 characters.\nAllowed characters are letters, numbers, spaces, or any of:\n!@#$%^&*()_-+.,?/[]<>'
        ),
    ] = None
    label: Annotated[
        int | None,
        Field(
            description='Index of the target within the program, set by the system automatically.\nUsed for reference to targets in communications with QSO staff.\n\nstorage: transient\napi_visibility: read only'
        ),
    ] = None
    version: Annotated[
        int | None,
        Field(
            description='Increments when this object updates.\n\nstorage: transient\napi_visibility: read only, incremented by the server'
        ),
    ] = None
    fixed_target: Annotated[TargetDataFixedTarget | None, Field(alias='fixedTarget')] = (
        None
    )
    moving_target: Annotated[TargetDataMovingTarget | None, Field(alias='movingTarget')] = (
        None
    )
    magnitude: TargetDataMagnitude | None = None
    temperature_effective: Annotated[
        float | None,
        Field(
            alias='temperatureEffective',
            description='The estimated/measured effective temperature, in Kelvin.\n\nRequired for targets observed with SPIRou or ESPaDOnS.\nNot used for MegaCam.',
        ),
    ] = None
    standard_star: Annotated[
        bool | None,
        Field(
            alias='standardStar',
            description='Whether the star is a "standard" star, to be observed each time other\nscience targets are observed.\n\nNot used for MegaCam.',
        ),
    ] = None
    linked_target_identifiers: Annotated[
        TargetDataLinkedTargetIdentifiers | None, Field(alias='linkedTargetIdentifiers')
    ] = None
    finding_chart: Annotated[
        list[PersistenceFindingChartData] | None,
        Field(
            alias='findingChart',
            description='A read-only view of the finding charts for this target.\nTo create or update finding charts, see the FindingChartService.\n\nstorage: transient\napi_visibility: read only',
        ),
    ] = None
    pointing_offset_token: Annotated[
        str | None,
        Field(
            alias='pointingOffsetToken',
            description='The token of a pointing offset which should be used when observing\nthis target.\n\nTo view or manage pointing offsets, see the PointingOffsetService.',
        ),
    ] = None
    pointing_offset: Annotated[
        PersistencePointingOffsetData | None, Field(alias='pointingOffset')
    ] = None


class PersistenceTelescopePatternData(BaseModel):
    offsets: Annotated[
        list[TelescopePatternDataOffset] | None,
        Field(
            title='Should only be set if manually specifying custom dithering patterns'
        ),
    ] = None
    config: TelescopePatternDataConfig | None = None
    token: str | None = None
    label: int | None = None
    version: int | None = None
    user_token: Annotated[str | None, Field(alias='userToken')] = None
    instrument: TypesInstrumentType | None = TypesInstrumentType.unknown
    is_system: Annotated[bool | None, Field(alias='isSystem')] = None
    name: str | None = None
    offset_coordinate: Annotated[
        list[TypesOffsetCoordinate] | None, Field(alias='offsetCoordinate')
    ] = None


class TypesDuration(BaseModel):
    millis: str | None = None
    display_unit: Annotated[
        TypesDurationUnit | None, Field(alias='displayUnit')
    ] = TypesDurationUnit.days


class ExposureDataExposureStatus(BaseModel):
    megacam_status: Annotated[
        ExposureDataMegacamStatus | None, Field(alias='megacamStatus')
    ] = None
    wircam_status: Annotated[
        ExposureDataWircamStatus | None, Field(alias='wircamStatus')
    ] = None
    espadons_status: Annotated[
        ExposureDataEspadonsStatus | None, Field(alias='espadonsStatus')
    ] = None
    sitelle_status: Annotated[
        ExposureDataSitelleStatus | None, Field(alias='sitelleStatus')
    ] = None
    spirou_status: Annotated[
        ExposureDataSpirouStatus | None, Field(alias='spirouStatus')
    ] = None
    wena_status: Annotated[ExposureDataWenaStatus | None, Field(alias='wenaStatus')] = (
        None
    )
    exposure_time: Annotated[
        PersistenceExposureTime | None, Field(alias='exposureTime')
    ] = None
    exp_date_mjd: Annotated[float | None, Field(alias='expDateMjd')] = None
    queue_name: Annotated[str | None, Field(alias='queueName')] = None
    exp_type: Annotated[str | None, Field(alias='expType')] = None
    exp_status: Annotated[
        PersistenceState | None, Field(alias='expStatus')
    ] = PersistenceState.unobserved
    is_photometric: Annotated[bool | None, Field(alias='isPhotometric')] = None
    obs_comment: Annotated[str | None, Field(alias='obsComment')] = None
    seq_comment: Annotated[str | None, Field(alias='seqComment')] = None
    actual_pointing: Annotated[TypesSkyCoordinate | None, Field(alias='actualPointing')] = (
        None
    )
    actual_sky: Annotated[float | None, Field(alias='actualSky')] = None
    actual_airmass: Annotated[float | None, Field(alias='actualAirmass')] = None
    actual_moondist: Annotated[float | None, Field(alias='actualMoondist')] = None
    observer_comment: Annotated[str | None, Field(alias='observerComment')] = None
    qc_comment: Annotated[str | None, Field(alias='qcComment')] = None
    file: ExposureStatusFile | None = None
    credited_qcoordinator: Annotated[str | None, Field(alias='creditedQcoordinator')] = (
        None
    )
    credited_observer: Annotated[str | None, Field(alias='creditedObserver')] = None
    grade: int | None = None
    read_obs_date_utc: Annotated[str | None, Field(alias='readObsDateUtc')] = None
    read_obs_date_hst: Annotated[str | None, Field(alias='readObsDateHst')] = None
    read_actual_sky_name: Annotated[str | None, Field(alias='readActualSkyName')] = None
    ra: Annotated[str | None, Field(title='Values from headers')] = None
    dec: str | None = None
    cmmtobs: str | None = None
    cmmtseq: str | None = None
    pi_name: Annotated[str | None, Field(alias='piName')] = None
    nexp: str | None = None
    cmpltexp: str | None = None
    ha: str | None = None
    read_obs_date_millis: Annotated[str | None, Field(alias='readObsDateMillis')] = None
    object: str | None = None


class InstrumentConfigurationDataMegacamConfigurationData(BaseModel):
    filter: InstrumentConfigurationDataMegacamConfigurationDataFilter | None = (
        InstrumentConfigurationDataMegacamConfigurationDataFilter.unknown
    )
    binning: InstrumentConfigurationDataMegacamConfigurationDataBinning | None = (
        InstrumentConfigurationDataMegacamConfigurationDataBinning.one_one
    )
    is_dynamic_exposure_time: Annotated[
        bool | None,
        Field(
            alias='isDynamicExposureTime',
            title="TODO: is this needed billy? Can we use presence of snr or not to decide?\nI THINK SO.  We have the capability to calculate SNR on every exposure, but we aren't necessarily doing SNR mode observations with everything",
        ),
    ] = None
    minimum_exposures: Annotated[int | None, Field(alias='minimumExposures')] = None
    min_exptime_ms: Annotated[str | None, Field(alias='minExptimeMs')] = None
    max_exptime_ms: Annotated[str | None, Field(alias='maxExptimeMs')] = None
    mag_ab: Annotated[
        float | None,
        Field(
            alias='magAB',
            title='TODO: interesting field here because associated with the target, but in the legacy mp snr mode, the mag is carried with the IC! so have to go back to this :(',
        ),
    ] = None
    snr_mode: Annotated[
        MegacamConfigurationDataSnrMode | None, Field(alias='snrMode')
    ] = MegacamConfigurationDataSnrMode.none
    etc_photometry: Annotated[
        InstrumentConfigurationDataMegacamConfigurationDataPhotometry | None,
        Field(alias='etcPhotometry'),
    ] = None


class PhaseScheduleObservingGroupPhaseSchedule(BaseModel):
    earliest_observe_date_millis: Annotated[
        str | None,
        Field(
            alias='earliestObserveDateMillis',
            description='The earliest moment to observe, in Unix time milliseconds.',
        ),
    ] = None
    tolerance: TypesDuration | None = None
    period: TypesDuration | None = None
    period_tolerance: Annotated[TypesDuration | None, Field(alias='periodTolerance')] = (
        None
    )


class ObservingEphemeridesUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: PersistenceTargetData | None = None


class ObservingPointingOffsetGetResponse(BaseModel):
    success: bool | None = None
    entity: PersistencePointingOffsetData | None = None
    error: HttpErrors | None = None


class ObservingPointingOffsetListResponse(BaseModel):
    success: bool | None = None
    entity: list[PersistencePointingOffsetData] | None = None
    error: HttpErrors | None = None


class ObservingPointingOffsetUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: PersistencePointingOffsetData | None = None


class ObservingProgramInfo(BaseModel):
    program_data: Annotated[PersistenceProgramData | None, Field(alias='programData')] = (
        None
    )
    rollup_fields: Annotated[ObservingRollupFields | None, Field(alias='rollupFields')] = (
        None
    )
    time_accounting: Annotated[
        PersistenceTimeAccountingData | None, Field(alias='timeAccounting')
    ] = None
    pi_info: Annotated[ProgramInfoPiInfo | None, Field(alias='piInfo')] = None
    version: int | None = None


class ObservingTargetListResponse(BaseModel):
    success: bool | None = None
    entity: list[PersistenceTargetData] | None = None
    error: HttpErrors | None = None


class ObservingTargetShowResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: PersistenceTargetData | None = None


class ObservingTargetUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: PersistenceTargetData | None = None


class ObservingTelescopePatternListResponse(BaseModel):
    success: bool | None = None
    telescope_pattern: list[PersistenceTelescopePatternData] | None = None
    error: HttpErrors | None = None


class ObservingTelescopePatternUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    telescope_pattern: PersistenceTelescopePatternData | None = None


class ObservingUpdateProgramCommentResponse(BaseModel):
    success: bool | None = None
    program_data: Annotated[PersistenceProgramData | None, Field(alias='programData')] = (
        None
    )
    error: HttpErrors | None = None


class ObservingUpdateProgramCommentsResponse(BaseModel):
    success: bool | None = None
    program_data: Annotated[PersistenceProgramData | None, Field(alias='programData')] = (
        None
    )
    error: HttpErrors | None = None


class PersistenceInstrumentConfigurationData(BaseModel):
    espadons_configuration: Annotated[
        InstrumentConfigurationDataEspadonsConfigurationData | None,
        Field(alias='espadonsConfiguration'),
    ] = None
    megacam_configuration: Annotated[
        InstrumentConfigurationDataMegacamConfigurationData | None,
        Field(alias='megacamConfiguration'),
    ] = None
    wircam_configuration: Annotated[
        InstrumentConfigurationDataWircamConfigurationData | None,
        Field(alias='wircamConfiguration'),
    ] = None
    sitelle_configuration: Annotated[
        InstrumentConfigurationDataSitelleConfigurationData | None,
        Field(alias='sitelleConfiguration'),
    ] = None
    spirou_configuration: Annotated[
        InstrumentConfigurationDataSpirouConfigurationData | None,
        Field(alias='spirouConfiguration'),
    ] = None
    wena_configuration: Annotated[
        InstrumentConfigurationDataWenaConfigurationData | None,
        Field(alias='wenaConfiguration'),
    ] = None
    sybase_ic_id: Annotated[TypesBigInteger | None, Field(alias='sybaseIcId')] = None
    etime_or_snr: Annotated[PersistenceExposureTime | None, Field(alias='etimeOrSnr')] = (
        None
    )
    sybase_cons_id: Annotated[TypesBigInteger | None, Field(alias='sybaseConsId')] = (
        None
    )
    tracking: InstrumentConfigurationDataTracking | None = (
        InstrumentConfigurationDataTracking.unknown
    )


class PersistenceLegacyReel(BaseModel):
    reel_og_token: Annotated[
        str | None,
        Field(alias='reelOgToken', description='Token of the linked observing group.'),
    ] = None
    delay: TypesDuration | None = None
    window: TypesDuration | None = None
    reel_og_label: Annotated[
        int | None,
        Field(
            alias='reelOgLabel',
            description='Label of the observing group which must be observed before this one.\n\nstorage: transient\napi_visibility: read only',
        ),
    ] = None


class PersistenceObservingTemplateData(BaseModel):
    instrument_configuration: Annotated[
        PersistenceInstrumentConfigurationData | None,
        Field(alias='instrumentConfiguration'),
    ] = None
    constraint: PersistenceConstraint | None = None
    telescope_offset: PersistenceTelescopePatternData | None = None
    charge_model: Annotated[
        str | None,
        Field(
            alias='chargeModel',
            description='Used for calculating cost for this pattern\nInvokes code which reads the ExposureInstructions and\nattributes a cost to it.',
        ),
    ] = None
    itime: str | None = None
    calculate_etime: Annotated[
        PersistenceExposureTime | None, Field(alias='calculateEtime')
    ] = None
    acquisition_time: Annotated[
        PersistenceExposureTime | None, Field(alias='acquisitionTime')
    ] = None
    token: str | None = None
    associated_observing_blocks: Annotated[
        list[TypesBigInteger] | None,
        Field(
            alias='associatedObservingBlocks',
            description='select ob.* from ob, prg, icseq where ob.prg_id = prg.id\nand prg.runid=<runid>\nand icseq.ob_id=ob.id and ob.con_id = <constraint.sybase_cons_id>\nand icseq.ic_id = <instrument_configuration.sybase_ic_id>;',
            title='When just creating an OT, this list is empty\nWhen this OT belongs to an OG, then any OBs in sybase that this OT is related too must be filled in.\nselect * from blah where (select id from prg where prg\nQuery to find related OBs is, select ob.* from ob, prg where ob.prg_id = prg.id and prg.runid=?     instrument_configuration.sybase_ic_id, constraint.sybase_cons_id',
        ),
    ] = None
    name: str | None = None
    total_exposure_count: Annotated[int | None, Field(alias='totalExposureCount')] = (
        None
    )
    label: int | None = None
    version: Annotated[
        int | None,
        Field(
            description='storage: transient\napi_visibility: read only, incremented by the server',
            title='Increments when this object updates',
        ),
    ] = None
    telescope_pattern_token: Annotated[str | None, Field(alias='telescopePatternToken')] = (
        None
    )
    telescope_pattern_scale: Annotated[
        float | None, Field(alias='telescopePatternScale')
    ] = None
    megacam_cumulative_snr_system_generated: Annotated[
        bool | None, Field(alias='megacamCumulativeSnrSystemGenerated')
    ] = None


class PersistencePhaseScheduleObservingGroup(BaseModel):
    observing_block: Annotated[
        ObservingGroupDataObservingBlock | None, Field(alias='observingBlock')
    ] = None
    phase_schedule: Annotated[
        PhaseScheduleObservingGroupPhaseSchedule | None, Field(alias='phaseSchedule')
    ] = None


class PersistenceTargetMonitoringObservingGroupTimeConstraint(BaseModel):
    number_of_iterations: Annotated[
        int | None,
        Field(alias='numberOfIterations', description='How many observations to take.'),
    ] = None
    minimum_number_of_iterations: Annotated[
        int | None,
        Field(
            alias='minimumNumberOfIterations',
            description='Minimum number of observations which still provides science value.\n\nIf weather becomes an issue, this is used to determine if additional\nobservations should be tried, or the whole observing group aborted\nto prioritize other observations.\n\nCannot be greater than requested number of iterations.',
        ),
    ] = None
    time_interval: Annotated[TypesDuration | None, Field(alias='timeInterval')] = None
    time_interval_tolerance_min: Annotated[
        TypesDuration | None, Field(alias='timeIntervalToleranceMin')
    ] = None
    time_interval_tolerance_max: Annotated[
        TypesDuration | None, Field(alias='timeIntervalToleranceMax')
    ] = None
    t0_millis: Annotated[
        str | None,
        Field(
            alias='t0Millis',
            description="Time the observing group should start being observed, in Unix time\nmilliseconds.\n\nIf omitted, CFHT will start observing at the QC's discretion.",
        ),
    ] = None
    within_same_camera_run: Annotated[
        bool | None,
        Field(
            alias='withinSameCameraRun',
            description='Whether all iterations need to occur within the same camera run.',
        ),
    ] = None


class ObservingListProgramsResponse(BaseModel):
    success: bool | None = None
    entity: list[ObservingProgramInfo] | None = None
    error: HttpErrors | None = None


class ObservingObservingTemplateListResponse(BaseModel):
    success: bool | None = None
    entity: list[PersistenceObservingTemplateData] | None = None
    error: HttpErrors | None = None


class ObservingObservingTemplateUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    observing_template: PersistenceObservingTemplateData | None = None


class PersistenceObservingGroupContext(BaseModel):
    iteration_count: Annotated[
        int | None,
        Field(
            alias='iterationCount',
            title='The iteration number this object was part of in the observing group',
        ),
    ] = None
    iteration_total: Annotated[
        int | None,
        Field(
            alias='iterationTotal',
            title='The total number of iterations requested for the observing group',
        ),
    ] = None
    iteration_minimum: Annotated[
        int | None,
        Field(
            alias='iterationMinimum',
            title='Minimum number of iterations this OG needs to provide science value',
        ),
    ] = None
    window: Annotated[
        list[ObservingBlockConditionWindow] | None,
        Field(title='Sorted by from past -> future on the observe_after key'),
    ] = None
    observing_group_token: Annotated[str | None, Field(alias='observingGroupToken')] = (
        None
    )
    observing_group_priority: Annotated[
        PersistenceObservingGroupPriority | None, Field(alias='observingGroupPriority')
    ] = PersistenceObservingGroupPriority.unknown_og_priority
    observing_group_state: Annotated[
        ObservingGroupDataObservingGroupState | None, Field(alias='observingGroupState')
    ] = ObservingGroupDataObservingGroupState.not_started
    observing_group_label: Annotated[int | None, Field(alias='observingGroupLabel')] = (
        None
    )
    observing_group_version: Annotated[
        int | None,
        Field(
            alias='observingGroupVersion',
            description='Increments every time the observing group changes.',
        ),
    ] = None
    legacy_reel: Annotated[PersistenceLegacyReel | None, Field(alias='legacyReel')] = (
        None
    )
    single: bool | None = None
    target_monitoring: Annotated[
        PersistenceTargetMonitoringObservingGroupTimeConstraint | None,
        Field(alias='targetMonitoring'),
    ] = None
    phase_schedule: Annotated[
        PhaseScheduleObservingGroupPhaseSchedule | None, Field(alias='phaseSchedule')
    ] = None
    time_accounting: Annotated[
        PersistenceTimeAccountingData | None, Field(alias='timeAccounting')
    ] = None
    exposure_type: Annotated[
        TypesExposureType | None, Field(alias='exposureType')
    ] = TypesExposureType.object
    use_group_dither_scheme: Annotated[bool | None, Field(alias='useGroupDitherScheme')] = (
        None
    )


class PersistenceTargetMonitoringObservingGroup(BaseModel):
    observing_block: Annotated[
        ObservingGroupDataObservingBlock | None, Field(alias='observingBlock')
    ] = None
    time_constraint: Annotated[
        PersistenceTargetMonitoringObservingGroupTimeConstraint | None,
        Field(alias='timeConstraint'),
    ] = None


class PersistenceExposureData(BaseModel):
    token: str | None = None
    obsid: str | None = None
    exposure_number: Annotated[int | None, Field(alias='exposureNumber')] = None
    iteration: int | None = None
    parent_exposure_token: Annotated[str | None, Field(alias='parentExposureToken')] = (
        None
    )
    exposure_status: Annotated[
        ExposureDataExposureStatus | None, Field(alias='exposureStatus')
    ] = None
    observing_template: Annotated[
        PersistenceObservingTemplateData | None, Field(alias='observingTemplate')
    ] = None
    target_data: PersistenceTargetData | None = None
    observing_group_context: Annotated[
        PersistenceObservingGroupContext | None, Field(alias='observingGroupContext')
    ] = None
    all_derivations_complete: Annotated[
        bool | None,
        Field(
            alias='allDerivationsComplete',
            description='When false, there is data which is still being calculated for this exposure.\n\nData can still be displayed, but the client should attempt to refresh the data.',
        ),
    ] = None
    queue_run_id: Annotated[str | None, Field(alias='queueRunId')] = None
    camera_run_id: Annotated[str | None, Field(alias='cameraRunId')] = None
    prg_run_id: Annotated[str | None, Field(alias='prgRunId')] = None
    observing_component_token: Annotated[
        str | None, Field(alias='observingComponentToken')
    ] = None
    sub_totals: Annotated[PersistenceSubTotalsData | None, Field(alias='subTotals')] = (
        None
    )
    attribution: ExposureDataAttribution | None = None
    version: Annotated[
        int | None,
        Field(
            description='storage: transient\napi_visibility: read only, incremented by the server',
            title='Increments when this object updates',
        ),
    ] = None


class PersistenceObservingGroupData(BaseModel):
    token: Annotated[
        str | None, Field(description='Unique identifier for the observing group.')
    ] = None
    label: Annotated[
        int | None,
        Field(
            description='Index of the observing group within the program, set by the system\nautomatically. Used for reference in communications with QSO staff.\n\nstorage: transient\napi_visibility: read only'
        ),
    ] = None
    og_priority: Annotated[
        PersistenceObservingGroupPriority | None, Field(alias='ogPriority')
    ] = PersistenceObservingGroupPriority.unknown_og_priority
    single_observing_group: Annotated[
        PersistenceSingleObservingGroup | None, Field(alias='singleObservingGroup')
    ] = None
    target_monitoring_observing_group: Annotated[
        PersistenceTargetMonitoringObservingGroup | None,
        Field(alias='targetMonitoringObservingGroup'),
    ] = None
    phase_schedule_observing_group: Annotated[
        PersistencePhaseScheduleObservingGroup | None,
        Field(alias='phaseScheduleObservingGroup'),
    ] = None
    read_observing_block: Annotated[
        list[ObservingGroupDataObservingBlock] | None,
        Field(
            alias='readObservingBlock',
            description='The observing blocks that have been created based on the entered\nconfiguration.\n\napi_visibility: read only',
        ),
    ] = None
    observing_block_condition: Annotated[
        dict[str, PersistenceObservingBlockCondition] | None,
        Field(
            alias='observingBlockCondition',
            description='The requirements that have been set for observing each observing blocks\nbased on the entered configuration.\n\napi_visibility: read only',
        ),
    ] = None
    minimum_observing_block_count: Annotated[
        int | None,
        Field(
            alias='minimumObservingBlockCount',
            description='This field is unused, please ignore.\n\napi_visibility: read only',
        ),
    ] = None
    time_accounting: Annotated[
        PersistenceTimeAccountingData | None, Field(alias='timeAccounting')
    ] = None
    state: ObservingGroupDataObservingGroupState | None = (
        ObservingGroupDataObservingGroupState.not_started
    )
    version: Annotated[
        int | None,
        Field(
            description='Increments when this object updates.\n\nstorage: transient\napi_visibility: read only, incremented by the server'
        ),
    ] = None
    legacy_reel: Annotated[PersistenceLegacyReel | None, Field(alias='legacyReel')] = (
        None
    )
    time_constraint: Annotated[
        ObservingpersistenceTimeConstraint | None, Field(alias='timeConstraint')
    ] = None
    target_type: Annotated[
        TypesExposureType | None, Field(alias='targetType')
    ] = TypesExposureType.object
    dither_scheme: Annotated[
        ObservingGroupDataDitherScheme | None, Field(alias='ditherScheme')
    ] = ObservingGroupDataDitherScheme.none
    low_surface_brightness: Annotated[
        bool | None,
        Field(
            alias='lowSurfaceBrightness',
            title='Indicates the observing group uses low surface brightness (LSB) mode.with',
        ),
    ] = None


class SnrBlockDataSnrBlockObservingComponents(BaseModel):
    observing_component_token: Annotated[
        str | None,
        Field(alias='observingComponentToken', title='the observing component'),
    ] = None
    observing_group_token: Annotated[
        str | None,
        Field(
            alias='observingGroupToken',
            title='should not be here, should be in the parent',
        ),
    ] = None
    is_primary: Annotated[
        bool | None, Field(alias='isPrimary', title='is it the original oc?')
    ] = None
    configured_exposures: Annotated[int | None, Field(alias='configuredExposures')] = (
        None
    )
    exposures: list[PersistenceExposureData] | None = None
    ob_label: Annotated[int | None, Field(alias='obLabel')] = None
    target_token: Annotated[str | None, Field(alias='targetToken')] = None
    observing_template_token: Annotated[
        str | None, Field(alias='observingTemplateToken')
    ] = None


class ObservingObservingGroupListResponse(BaseModel):
    success: bool | None = None
    entity: list[PersistenceObservingGroupData] | None = None
    error: HttpErrors | None = None


class ObservingObservingGroupUpdateResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: PersistenceObservingGroupData | None = None


class PersistenceSnrBlockData(BaseModel):
    token: str | None = None
    label: int | None = None
    cumulative_snr: Annotated[
        float | None,
        Field(
            alias='cumulativeSnr',
            title='the total snr achieved of all exposures\n of all observing components of this snr block',
        ),
    ] = None
    carry_forward_snr: Annotated[
        float | None,
        Field(
            alias='carryForwardSnr',
            title='if the program is copied to a new program possibly for a new semester\n the cumulative snr will be moved to the carry_forward_snr and the\n carry forward snr will be counted in the cumulative snr of the new program',
        ),
    ] = None
    observing_components: Annotated[
        list[SnrBlockDataSnrBlockObservingComponents] | None,
        Field(alias='observingComponents'),
    ] = None
    version: int | None = None
    requested_target_magnitude: Annotated[
        float | None,
        Field(alias='requestedTargetMagnitude', title='this will come from the target'),
    ] = None
    requested_cumulative_snr: Annotated[
        float | None,
        Field(alias='requestedCumulativeSnr', title='this will come from the OT'),
    ] = None
    requested_minimum_exposures: Annotated[
        int | None, Field(alias='requestedMinimumExposures')
    ] = None
    total_exposures: Annotated[
        int | None,
        Field(
            alias='totalExposures',
            title='counting the total validated exposures for this OC (OT/TARGET)',
        ),
    ] = None
    primary_observing_group_token: Annotated[
        str | None, Field(alias='primaryObservingGroupToken')
    ] = None
    primary_observing_component_token: Annotated[
        str | None, Field(alias='primaryObservingComponentToken')
    ] = None
    primary_observing_group_label: Annotated[
        int | None, Field(alias='primaryObservingGroupLabel')
    ] = None
    total_configured_exposures: Annotated[
        int | None,
        Field(
            alias='totalConfiguredExposures',
            title='counting the total configured exposures for this OC',
        ),
    ] = None


class ObservingAddSingleToSnrBlockResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    snr_block: Annotated[PersistenceSnrBlockData | None, Field(alias='snrBlock')] = None
    observing_group: Annotated[
        PersistenceObservingGroupData | None, Field(alias='observingGroup')
    ] = None


class ObservingSnrBlockListResponse(BaseModel):
    success: bool | None = None
    error: HttpErrors | None = None
    entity: list[PersistenceSnrBlockData] | None = None
